In [5]:
platformID = 'FBE'

## import libraries

In [6]:
import os
import zipfile

from tqdm import tqdm 
from datetime import datetime

import pandas as pd
pd.set_option('display.max_colwidth', None)

import numpy as np

import re

import missingno as msno
import matplotlib.pyplot as plt
import seaborn as sns 

import psycopg2

## import helper

In [7]:
import sys
from pathlib import Path

try:
    # Works in Python scripts
    helper_path = Path(__file__).resolve().parent.parent / "helper"
except NameError:
    # Works in Jupyter notebooks
    helper_path = Path().resolve().parent / "helper"

sys.path.insert(0, str(helper_path))

# Now import your modules 
from config import gam_info

from functions import lookup_loader
import test_functions

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

In [ ]:
lookup = lookup_loader(gam_info, platformID, '3',
                       with_country=True)
week_tester = lookup['week_tester']
socialmedia_accounts = lookup['socialmedia_accounts']
country_codes = lookup['country_codes']

✅ Test FBE_3_00 passed: lookup DataFrame is not empty.
...updating logbook...

✅ Test FBE_3_01 passed: No combinations occurs more than once a week.
...updating logbook...

✅ Test FBE_3_02 passed: No empty values in lookup.
...updating logbook...

✅ Test FBE_3_03 passed: lookup DataFrame is not empty.
...updating logbook...

✅ Test FBE_3_04 passed: No combinations occurs more than once a week.
...updating logbook...

✅ Test FBE_3_05 passed: No empty values in lookup.
...updating logbook...

✅ Test FBE_3_06 passed: lookup DataFrame is not empty.
...updating logbook...

✅ Test FBE_3_07 passed: No combinations occurs more than once a week.
...updating logbook...

✅ Test FBE_3_08 passed: No empty values in lookup.
...updating logbook...

# Unique Viewers

In [ ]:
facebook_engagements_reach = pd.read_csv(f"../data/processed/{platformID}/{gam_info['file_timeinfo']}_{platformID}_REDSHIFT.csv",)
facebook_engagements_reach['w/c'] = pd.to_datetime(facebook_engagements_reach['w/c'])

In [ ]:
facebook_engagements_reach.sort_values(['w/c'])['w/c'].unique()

<DatetimeArray>
['2025-03-31 00:00:00', '2025-04-07 00:00:00', '2025-04-14 00:00:00',
 '2025-04-21 00:00:00', '2025-04-28 00:00:00', '2025-05-05 00:00:00',
 '2025-05-12 00:00:00', '2025-05-19 00:00:00', '2025-05-26 00:00:00',
 '2025-06-02 00:00:00', '2025-06-09 00:00:00', '2025-06-16 00:00:00',
 '2025-06-23 00:00:00', '2025-06-30 00:00:00', '2025-07-07 00:00:00',
 '2025-07-14 00:00:00', '2025-07-21 00:00:00', '2025-07-28 00:00:00',
 '2025-08-04 00:00:00', '2025-08-11 00:00:00', '2025-08-18 00:00:00',
 '2025-08-25 00:00:00', '2025-09-01 00:00:00', '2025-09-08 00:00:00',
 '2025-09-15 00:00:00', '2025-09-22 00:00:00', '2025-09-29 00:00:00',
 '2025-10-06 00:00:00', '2025-10-13 00:00:00', '2025-10-20 00:00:00',
 '2025-10-27 00:00:00', '2025-11-03 00:00:00', '2025-11-10 00:00:00',
 '2025-11-17 00:00:00', '2025-11-24 00:00:00', '2025-12-01 00:00:00',
 '2025-12-08 00:00:00', '2025-12-15 00:00:00', '2025-12-22 00:00:00',
 '2025-12-29 00:00:00', '2026-01-05 00:00:00', '2026-01-12 00:00:00']
Length: 42, dtype: datetime64[ns]

# Country

In [ ]:
country_raw = pd.read_csv(f"../data/processed/{platformID}/{gam_info['file_timeinfo']}_{platformID}_REDSHIFT_COUNTRY.csv")
country_raw['w/c'] = pd.to_datetime(country_raw['w/c'])

cols = ['Channel ID', 'Channel Name', 'w/c', 'PlaceID', 'country_%']
country_df = country_raw[cols]
country_df['PlatformID'] = platformID
country_df.head()

           Channel ID  Channel Name        w/c PlaceID  country_% PlatformID
0  FBE832942320102956  BBC Trending 2025-03-31     ITA   0.009834        FBE
1  FBE832942320102956  BBC Trending 2025-03-31     GER   0.012933        FBE
2  FBE832942320102956  BBC Trending 2025-03-31     FRA   0.008038        FBE
3  FBE832942320102956  BBC Trending 2025-03-31     IRE   0.004621        FBE
4  FBE832942320102956  BBC Trending 2025-03-31     BAN   0.053732        FBE

In [ ]:
country_df.sort_values(['w/c'])['w/c'].unique()

<DatetimeArray>
['2025-03-31 00:00:00', '2025-04-07 00:00:00', '2025-04-14 00:00:00',
 '2025-04-21 00:00:00', '2025-04-28 00:00:00', '2025-05-05 00:00:00',
 '2025-05-12 00:00:00', '2025-05-19 00:00:00', '2025-05-26 00:00:00',
 '2025-06-02 00:00:00', '2025-06-09 00:00:00', '2025-06-16 00:00:00',
 '2025-06-23 00:00:00', '2025-06-30 00:00:00', '2025-07-07 00:00:00',
 '2025-07-14 00:00:00', '2025-07-21 00:00:00', '2025-07-28 00:00:00',
 '2025-08-04 00:00:00', '2025-08-11 00:00:00', '2025-08-18 00:00:00',
 '2025-08-25 00:00:00', '2025-09-01 00:00:00', '2025-09-08 00:00:00',
 '2025-09-15 00:00:00', '2025-09-22 00:00:00', '2025-09-29 00:00:00',
 '2025-10-06 00:00:00', '2025-10-13 00:00:00', '2025-10-20 00:00:00',
 '2025-10-27 00:00:00', '2025-11-03 00:00:00', '2025-11-10 00:00:00',
 '2025-11-17 00:00:00', '2025-11-24 00:00:00', '2025-12-01 00:00:00',
 '2025-12-08 00:00:00', '2025-12-15 00:00:00', '2025-12-22 00:00:00',
 '2025-12-29 00:00:00', '2026-01-05 00:00:00', '2026-01-12 00:00:00']
Length: 42, dtype: datetime64[ns]

# combine engagements & country

In [ ]:
country_df[(country_df['Channel ID'] == 'FBE630866223444617') 
    #& (country_df['w/c'].isin(['2025-06-23', '2025-06-30']))
    ]

,Channel ID,Channel Name,w/c,PlaceID,country_%,PlatformID
193233,FBE630866223444617,NaN,2025-06-23,ALG,0.004225,FBE
193234,FBE630866223444617,NaN,2025-06-23,ANG,0.000542,FBE
193235,FBE630866223444617,NaN,2025-06-23,ARG,0.000262,FBE
193236,FBE630866223444617,NaN,2025-06-23,AUS,0.002099,FBE
193237,FBE630866223444617,NaN,2025-06-23,BAN,0.000262,FBE
...,...,...,...,...,...,...
194754,FBE630866223444617,NaN,2026-01-12,UAE,0.000273,FBE
194755,FBE630866223444617,NaN,2026-01-12,UK,0.113187,FBE
194756,FBE630866223444617,NaN,2026-01-12,UKR,0.001746,FBE
194757,FBE630866223444617,NaN,2026-01-12,USA,0.016414,FBE
194758,FBE630866223444617,NaN,2026-01-12,VIE,0.000138,FBE

In [ ]:
reach_df_raw = facebook_engagements_reach.merge(country_df, on=['Channel ID', 'w/c'], how='outer', 
                                            indicator=True)
print(reach_df_raw._merge.value_counts())
reach_df_left = reach_df_raw[reach_df_raw['_merge'] == 'left_only'].drop(columns=['_merge'])
reach_df = reach_df_raw[reach_df_raw['_merge'] == 'both'].drop(columns=['_merge'])

'''
reach_df_inner = reach_df_raw[reach_df_raw['_merge'] == 'both'].drop(columns=['_merge'])
reach_df_avg = reach_df_left[facebook_engagements_reach.columns].merge(avg_country_df, 
                                    on=['Channel ID', 'w/c'], how='left', indicator=True)

reach_df = pd.concat([reach_df_inner, reach_df_avg])'''

_merge
both          193637
right_only      1122
left_only          0
Name: count, dtype: int64

"\nreach_df_inner = reach_df_raw[reach_df_raw['_merge'] == 'both'].drop(columns=['_merge'])\nreach_df_avg = reach_df_left[facebook_engagements_reach.columns].merge(avg_country_df, \n                                    on=['Channel ID', 'w/c'], how='left', indicator=True)\n\nreach_df = pd.concat([reach_df_inner, reach_df_avg])"

In [ ]:
metric_col = ['country_%', 'engaged_reach']
for col in metric_col:
    reach_df[col] = reach_df[col].fillna(0)
    
reach_df['uv_by_country'] = reach_df['country_%'] * reach_df['engaged_reach']
reach_df = reach_df[reach_df['uv_by_country'] > 0]
# TODO investigate why there should be duplicates here
reach_df = reach_df.drop_duplicates()

print(reach_df.shape)
reach_df = reach_df.dropna(subset='uv_by_country')
print(reach_df.shape)

(192722, 9)
(192722, 9)

In [ ]:
# missing weeks per page_id
test_functions.test_weeks_presence_per_account(key='w/c',
                                               channel_id_col=['Channel ID'],
                                               main_data=reach_df,
                                               week_lookup=week_tester[['w/c']],
                                               channel_lookup=socialmedia_accounts,
                                               test_number=f"{platformID}_3_09",
                                               test_step="Check all weeks present for each account")

❌ Missing weeks from Start onward:
              Channel ID      Start End        w/c
210   FBE102775241582303 2020-04-01 NaT 2025-03-31
211   FBE102775241582303 2020-04-01 NaT 2025-04-07
212   FBE102775241582303 2020-04-01 NaT 2025-04-14
1725  FBE171824429536304 2025-04-02 NaT 2025-04-28
214   FBE102775241582303 2020-04-01 NaT 2025-04-28
215   FBE102775241582303 2020-04-01 NaT 2025-05-05
216   FBE102775241582303 2020-04-01 NaT 2025-05-12
1727  FBE171824429536304 2025-04-02 NaT 2025-05-12
217   FBE102775241582303 2020-04-01 NaT 2025-05-19
218   FBE102775241582303 2020-04-01 NaT 2025-05-26
1729  FBE171824429536304 2025-04-02 NaT 2025-05-26
219   FBE102775241582303 2020-04-01 NaT 2025-06-02
220   FBE102775241582303 2020-04-01 NaT 2025-06-09
221   FBE102775241582303 2020-04-01 NaT 2025-06-16
222   FBE102775241582303 2020-04-01 NaT 2025-06-23
226   FBE102775241582303 2020-04-01 NaT 2025-07-21
227   FBE102775241582303 2020-04-01 NaT 2025-07-28
228   FBE102775241582303 2020-04-01 NaT 2025-08-04
859   FBE127284984048667 2020-04-01 NaT 2025-08-11
229   FBE102775241582303 2020-04-01 NaT 2025-08-11
1742  FBE171824429536304 2025-04-02 NaT 2025-08-25
232   FBE102775241582303 2020-04-01 NaT 2025-09-01
1743  FBE171824429536304 2025-04-02 NaT 2025-09-01
1744  FBE171824429536304 2025-04-02 NaT 2025-09-08
234   FBE102775241582303 2020-04-01 NaT 2025-09-15
1745  FBE171824429536304 2025-04-02 NaT 2025-09-15
1746  FBE171824429536304 2025-04-02 NaT 2025-09-22
1747  FBE171824429536304 2025-04-02 NaT 2025-09-29
1748  FBE171824429536304 2025-04-02 NaT 2025-10-06
237   FBE102775241582303 2020-04-01 NaT 2025-10-06
1749  FBE171824429536304 2025-04-02 NaT 2025-10-13
1750  FBE171824429536304 2025-04-02 NaT 2025-10-20
239   FBE102775241582303 2020-04-01 NaT 2025-10-20
240   FBE102775241582303 2020-04-01 NaT 2025-10-27
1751  FBE171824429536304 2025-04-02 NaT 2025-10-27
241   FBE102775241582303 2020-04-01 NaT 2025-11-03
1752  FBE171824429536304 2025-04-02 NaT 2025-11-03
1753  FBE171824429536304 2025-04-02 NaT 2025-11-10
243   FBE102775241582303 2020-04-01 NaT 2025-11-17
1754  FBE171824429536304 2025-04-02 NaT 2025-11-17
1755  FBE171824429536304 2025-04-02 NaT 2025-11-24
1756  FBE171824429536304 2025-04-02 NaT 2025-12-01
1757  FBE171824429536304 2025-04-02 NaT 2025-12-08
1758  FBE171824429536304 2025-04-02 NaT 2025-12-15
1759  FBE171824429536304 2025-04-02 NaT 2025-12-22
1760  FBE171824429536304 2025-04-02 NaT 2025-12-29
1761  FBE171824429536304 2025-04-02 NaT 2026-01-05
1762  FBE171824429536304 2025-04-02 NaT 2026-01-12

Summary of missing weeks per channel_id_col:
           Channel ID  missing_week_count
2  FBE171824429536304                  24
0  FBE102775241582303                  23
1  FBE127284984048667                   1
...updating logbook...

              Channel ID      Start End        w/c
210   FBE102775241582303 2020-04-01 NaT 2025-03-31
211   FBE102775241582303 2020-04-01 NaT 2025-04-07
212   FBE102775241582303 2020-04-01 NaT 2025-04-14
1725  FBE171824429536304 2025-04-02 NaT 2025-04-28
214   FBE102775241582303 2020-04-01 NaT 2025-04-28
215   FBE102775241582303 2020-04-01 NaT 2025-05-05
216   FBE102775241582303 2020-04-01 NaT 2025-05-12
1727  FBE171824429536304 2025-04-02 NaT 2025-05-12
217   FBE102775241582303 2020-04-01 NaT 2025-05-19
218   FBE102775241582303 2020-04-01 NaT 2025-05-26
1729  FBE171824429536304 2025-04-02 NaT 2025-05-26
219   FBE102775241582303 2020-04-01 NaT 2025-06-02
220   FBE102775241582303 2020-04-01 NaT 2025-06-09
221   FBE102775241582303 2020-04-01 NaT 2025-06-16
222   FBE102775241582303 2020-04-01 NaT 2025-06-23
226   FBE102775241582303 2020-04-01 NaT 2025-07-21
227   FBE102775241582303 2020-04-01 NaT 2025-07-28
228   FBE102775241582303 2020-04-01 NaT 2025-08-04
859   FBE127284984048667 2020-04-01 NaT 2025-08-11
229   FBE102775241582303 2020-04-01 NaT 2025-08-11
1742  FBE171824429536304 2025-04-02 NaT 2025-08-25
232   FBE102775241582303 2020-04-01 NaT 2025-09-01
1743  FBE171824429536304 2025-04-02 NaT 2025-09-01
1744  FBE171824429536304 2025-04-02 NaT 2025-09-08
234   FBE102775241582303 2020-04-01 NaT 2025-09-15
1745  FBE171824429536304 2025-04-02 NaT 2025-09-15
1746  FBE171824429536304 2025-04-02 NaT 2025-09-22
1747  FBE171824429536304 2025-04-02 NaT 2025-09-29
1748  FBE171824429536304 2025-04-02 NaT 2025-10-06
237   FBE102775241582303 2020-04-01 NaT 2025-10-06
1749  FBE171824429536304 2025-04-02 NaT 2025-10-13
1750  FBE171824429536304 2025-04-02 NaT 2025-10-20
239   FBE102775241582303 2020-04-01 NaT 2025-10-20
240   FBE102775241582303 2020-04-01 NaT 2025-10-27
1751  FBE171824429536304 2025-04-02 NaT 2025-10-27
241   FBE102775241582303 2020-04-01 NaT 2025-11-03
1752  FBE171824429536304 2025-04-02 NaT 2025-11-03
1753  FBE171824429536304 2025-04-02 NaT 2025-11-10
243   FBE102775241582303 2020-04-01 NaT 2025-11-17
1754  FBE171824429536304 2025-04-02 NaT 2025-11-17
1755  FBE171824429536304 2025-04-02 NaT 2025-11-24
1756  FBE171824429536304 2025-04-02 NaT 2025-12-01
1757  FBE171824429536304 2025-04-02 NaT 2025-12-08
1758  FBE171824429536304 2025-04-02 NaT 2025-12-15
1759  FBE171824429536304 2025-04-02 NaT 2025-12-22
1760  FBE171824429536304 2025-04-02 NaT 2025-12-29
1761  FBE171824429536304 2025-04-02 NaT 2026-01-05
1762  FBE171824429536304 2025-04-02 NaT 2026-01-12

In [ ]:
reach_df.sort_values(['w/c'])['w/c'].unique()

<DatetimeArray>
['2025-03-31 00:00:00', '2025-04-07 00:00:00', '2025-04-14 00:00:00',
 '2025-04-21 00:00:00', '2025-04-28 00:00:00', '2025-05-05 00:00:00',
 '2025-05-12 00:00:00', '2025-05-19 00:00:00', '2025-05-26 00:00:00',
 '2025-06-02 00:00:00', '2025-06-09 00:00:00', '2025-06-16 00:00:00',
 '2025-06-23 00:00:00', '2025-06-30 00:00:00', '2025-07-07 00:00:00',
 '2025-07-14 00:00:00', '2025-07-21 00:00:00', '2025-07-28 00:00:00',
 '2025-08-04 00:00:00', '2025-08-11 00:00:00', '2025-08-18 00:00:00',
 '2025-08-25 00:00:00', '2025-09-01 00:00:00', '2025-09-08 00:00:00',
 '2025-09-15 00:00:00', '2025-09-22 00:00:00', '2025-09-29 00:00:00',
 '2025-10-06 00:00:00', '2025-10-13 00:00:00', '2025-10-20 00:00:00',
 '2025-10-27 00:00:00', '2025-11-03 00:00:00', '2025-11-10 00:00:00',
 '2025-11-17 00:00:00', '2025-11-24 00:00:00', '2025-12-01 00:00:00',
 '2025-12-08 00:00:00', '2025-12-15 00:00:00', '2025-12-22 00:00:00',
 '2025-12-29 00:00:00', '2026-01-05 00:00:00', '2026-01-12 00:00:00']
Length: 42, dtype: datetime64[ns]

In [ ]:
cols = ['ServiceID', 'Channel ID', 'w/c', 'PlaceID', 'uv_by_country']
reach_df[cols].to_csv(f"../data/processed/{platformID}/{gam_info['file_timeinfo']}_{platformID}_uniqueViewer_country.csv", 
                     index=None)

In [ ]:
reach_df.ServiceID.unique()

NameError: name 'reach_df' is not defined