## Status 
- twitter business unit and aggregated services is currently calculated by using minnie's dataset (helper/tw_minnie_preBU.csv)
- also minnie's weekly gnl dataset is missing week 51 & 52? 
-

In [32]:
platformID = 'TWI'

In [33]:
from IPython.display import display

import pandas as pd
pd.set_option('display.float_format', '{:.0f}'.format)

In [34]:
import sys
from pathlib import Path

try:
    # Works in Python scripts
    helper_path = Path(__file__).resolve().parent.parent / "helper"
except NameError:
    # Works in Jupyter notebooks
    helper_path = Path().resolve().parent / "helper"

sys.path.insert(0, str(helper_path))

# Now import your modules 
from config_GAM2025 import gam_info
import functions

In [35]:
# Load country mapping
country_map = pd.read_excel(f"../../{gam_info['lookup_file']}", sheet_name='CountryID')[['PlaceID', 'YT-_FBE_codes']]
# Load country mapping
week_map = pd.read_excel(f"../../{gam_info['lookup_file']}", sheet_name='GAM Period')[['w/c', 'WeekNumber_finYear']]

In [36]:
# Utility functions
def load_excel(path):
    return pd.read_excel(path, engine='openpyxl')

def load_csv(path):
    return pd.read_csv(path)

def standardize_country_codes(df, column='Country Code'):
    return df.replace({column: {'WLF': 'WFI', '* Total': 'Total'}})

def run_comparison(original_df, new_df, column_mapping, key_columns, method='integer', threshold=0.0001):
    if method == 'integer':
        return compare_dataframes_integer(original_df, new_df, column_mapping, key_columns)
    elif method == 'percentage':
        return compare_dataframes_percentage(original_df, new_df, column_mapping, key_columns, threshold)
    else:
        raise ValueError("Unknown comparison method")

In [37]:
def compare_dataframes_integer(original_df, new_df, column_mapping, key_columns_new):
    """
    Compare two DataFrames and return rows that are missing or different.

    Parameters:
    - original_df: DataFrame from the original source
    - new_df: DataFrame from the new source
    - column_mapping: dict mapping original_df column names to new_df column names
    - key_columns_new: list of key columns using new_df naming

    Returns:
    - missing_from_new: rows in original_df not found in new_df
    - differing_rows: rows where key matches but mapped columns differ
    """

    # Rename original_df to match new_df column names
    original_df_renamed = original_df.rename(columns=column_mapping)

    # Ensure all required columns exist
    all_columns = list(column_mapping.values())
    original_subset = original_df_renamed[all_columns].copy()
    new_subset = new_df[all_columns].copy()

    # Round numeric columns to nearest integer
    for col in all_columns:
        if pd.api.types.is_numeric_dtype(original_subset[col]) and pd.api.types.is_numeric_dtype(new_subset[col]):
            original_subset[col] = original_subset[col].round(0).astype('Int64')
            new_subset[col] = new_subset[col].round(0).astype('Int64')
        
    # Merge to find differences
    merged = pd.merge(
        original_subset,
        new_subset,
        on=key_columns_new,
        how='outer',
        suffixes=('_orig', '_new'),
        indicator=True
    )

    # Missing rows: present in original but not in new
    missing_from_new = merged[merged['_merge'] == 'left_only']

    # Differing rows: same keys but different values
    comparison_cols = [col for col in all_columns if col not in key_columns_new]
        
    differing_rows = merged[
        (merged['_merge'] == 'both') &
        merged[[f"{col}_orig" for col in comparison_cols]].ne(
            merged[[f"{col}_new" for col in comparison_cols]].values
        ).any(axis=1)
    ]

    return missing_from_new, differing_rows

In [38]:
def compare_dataframes_percentage(original_df, new_df, column_mapping, key_columns_new, threshold=0.0001):
    """
    Compare two DataFrames and return rows that are missing or have percentage differences.

    Parameters:
    - original_df: DataFrame from the original source
    - new_df: DataFrame from the new source
    - column_mapping: dict mapping original_df column names to new_df column names
    - key_columns_new: list of key columns using new_df naming
    - threshold: minimum absolute difference to consider as significant

    Returns:
    - missing_from_new: rows in original_df not found in new_df
    - differing_rows: rows where key matches but mapped columns differ beyond threshold
    """

    # Rename original_df to match new_df column names
    original_df_renamed = original_df.rename(columns=column_mapping)

    # Ensure all required columns exist
    all_columns = list(column_mapping.values())
    original_subset = original_df_renamed[all_columns].copy()
    new_subset = new_df[all_columns].copy()

    # Merge to find differences
    merged = pd.merge(
        original_subset,
        new_subset,
        on=key_columns_new,
        how='outer',
        suffixes=('_orig', '_new'),
        indicator=True
    )

    # Missing rows: present in original but not in new
    missing_from_new = merged[merged['_merge'] == 'left_only']

    # Compute differences
    comparison_cols = [col for col in all_columns if col not in key_columns_new]
    for col in comparison_cols:
        merged[f"{col}_diff"] = merged[f"{col}_new"] - merged[f"{col}_orig"]

    # Filter rows where any difference exceeds threshold
    diff_mask = merged['_merge'] == 'both'
    for col in comparison_cols:
        diff_mask &= merged[f"{col}_diff"].abs() > threshold

    differing_rows = merged[diff_mask]

    return missing_from_new, differing_rows

In [39]:
# Dataset configuration
datasets = [
    
    {
        "name": "Engagements",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/data/final data/TW_GAM2025_REDSHIFT.xlsx",
        "new_path": f"../data/processed/{platformID}/{gam_info['file_timeinfo']}_{platformID}_REDSHIFT.csv",
        "column_mapping": {
            "tw_account_id": "tw_account_id",
            "week_commencing": "w/c",
            "tweet_engagements": "tweet engagements"
        },
        "key_columns": ["tw_account_id", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": False
        },
        "notes": "262 accounts in minnie's dataset - I suspect she got all accounts the BBC has "
    },
    
    {
        "name": "pre Business Unites",
        "original_path": "../helper/tw_minnie_preBU.csv",
        "new_path": f"../data/processed/{platformID}/{gam_info['file_timeinfo']}_uniqueViewer_country.csv",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'TW Account ID': 'Channel ID', 
            'Twitter Engaged Users by Country': 'uv_by_country'
        },
        "key_columns": ["Channel ID", "w/c", 'PlaceID', 'ServiceID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "notes": ""
    },
    {
        "name": "GNL Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY Twitter GNL.xlsx",
        "new_path": "../data/singlePlatform/TWI/weekly/GAM2025_WEEKLY_TWI_GNLbyCountry.xlsx",
        "column_mapping": {
            "Service Code": "ServiceID",
            "Country Code": "PlaceID",
            "Twitter Engaged Users by Country": "Reach",
            "w/c": "w/c"
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        },
        "notes": """the missing are all from the last two weeks. 
        I don't see these values in the alteryx workflow either so not sure where they come from in 
        the output file. 
        differences: looking at the biggest difference I fidn the same value from my calculation in
        alteryx but the excel sheet has a different number... """
    },
]
'''{
        "name": "Country",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2024/Social Media/data/Final Raw/Twitter Engagements inc country.xlsx",
        "new_path": f'../data/raw/{platformID}/stale_Twitter Engagements inc country.xlsx',
        "column_mapping": {
            "TW Account ID": "tw_account_id",
            "TW Service Code": 'ServiceID', 
            "Country": "PlaceID",
            "Week Number": "Week Number",
            "Engagement %": "country_%"
        },
        "key_columns": ["tw_account_id", "w/c", "PlaceID", "ServiceID"],
        "method": "percentage",
        "threshold": 0.0001,
        "preprocess": {
            "standardize_country": False,
            "week_mapping": False
        },
        "notes": "has older data in that isn't of the current GAM year"
    },'''

'{\n        "name": "Country",\n        "original_path": "../../../../Research Projects/GAM/Digital GAM/2024/Social Media/data/Final Raw/Twitter Engagements inc country.xlsx",\n        "new_path": f\'../data/raw/{platformID}/stale_Twitter Engagements inc country.xlsx\',\n        "column_mapping": {\n            "TW Account ID": "tw_account_id",\n            "TW Service Code": \'ServiceID\', \n            "Country": "PlaceID",\n            "Week Number": "Week Number",\n            "Engagement %": "country_%"\n        },\n        "key_columns": ["tw_account_id", "w/c", "PlaceID", "ServiceID"],\n        "method": "percentage",\n        "threshold": 0.0001,\n        "preprocess": {\n            "standardize_country": False,\n            "week_mapping": False\n        },\n        "notes": "has older data in that isn\'t of the current GAM year"\n    },'

In [41]:
datasets = [
    {
        "name": "Twitter ALL Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly Twitter ALL.xlsx",
        "new_path": f"../data/singlePlatform/TWI/weekly/GAM2025_WEEKLY_TWI_ALLbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "Twitter ANW Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly Twitter ANW.xlsx",
        "new_path": f"../data/singlePlatform/TWI/weekly/GAM2025_WEEKLY_TWI_ANWbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "Twitter ANY Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly Twitter ANY.xlsx",
        "new_path": f"../data/singlePlatform/TWI/weekly/GAM2025_WEEKLY_TWI_ANYbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "Twitter AX2 Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly Twitter AX2.xlsx",
        "new_path": f"../data/singlePlatform/TWI/weekly/GAM2025_WEEKLY_TWI_AX2byCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "Twitter AXE Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly Twitter AXE.xlsx",
        "new_path": f"../data/singlePlatform/TWI/weekly/GAM2025_WEEKLY_TWI_AXEbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "Twitter EN2 Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly Twitter EN2 by country.xlsx",
        "new_path": f"../data/singlePlatform/TWI/weekly/GAM2025_WEEKLY_TWI_EN2byCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "Twitter ENG Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly Twitter ENG by country.xlsx",
        "new_path": f"../data/singlePlatform/TWI/weekly/GAM2025_WEEKLY_TWI_ENGbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "Twitter ENW Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly Twitter ENW by country.xlsx",
        "new_path": f"../data/singlePlatform/TWI/weekly/GAM2025_WEEKLY_TWI_ENWbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "Twitter FOA Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly Twitter FOA.xlsx",
        "new_path": f"../data/singlePlatform/TWI/weekly/GAM2025_WEEKLY_TWI_FOAbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "Twitter GNL Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly Twitter GNL.xlsx",
        "new_path": f"../data/singlePlatform/TWI/weekly/GAM2025_WEEKLY_TWI_GNLbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "Twitter MA- Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly Twitter MA.xlsx",
        "new_path": f"../data/singlePlatform/TWI/weekly/GAM2025_WEEKLY_TWI_MA-byCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "Twitter TOT Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly Twitter TOT.xlsx",
        "new_path": f"../data/singlePlatform/TWI/weekly/GAM2025_WEEKLY_TWI_TOTbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "Twitter WOR Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly Twitter WOR.xlsx",
        "new_path": f"../data/singlePlatform/TWI/weekly/GAM2025_WEEKLY_TWI_WORbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "Twitter WSE Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly Twitter WSE.xlsx",
        "new_path": f"../data/singlePlatform/TWI/weekly/GAM2025_WEEKLY_TWI_WSEbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "Twitter WSL Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly Twitter WSL.xlsx",
        "new_path": f"../data/singlePlatform/TWI/weekly/GAM2025_WEEKLY_TWI_WSLbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
]
# Execute comparisons
for ds in datasets:
    print(f"\n--- Processing {ds['name']} ---")

    orig = functions.load_excel(ds["original_path"]) if ds["original_path"].endswith(".xlsx") else functions.load_csv(ds["original_path"])
    new  = functions.load_excel(ds["new_path"]) if ds["new_path"].endswith(".xlsx") else functions.load_csv(ds["new_path"])

    if ds["name"] == "Facebook Factors input":
        new['fb_page_id'] = new['fb_page_id'].astype(str)
        orig = orig.dropna(subset=['page_consumptions', 'page_video_complete_views_30s_autoplayed'],
                           how='any')
        
    # Special preprocessing for Country Percentage dataset
    if ds["name"] == "Country Percentage":
        
        # Rename 'Country' to 'YouTube Codes' in original data and merge with mapping
        orig = orig.rename(columns={'Country': 'YouTube Codes'})
        orig = orig.merge(country_map, on='YouTube Codes', how='left').drop(columns=['YouTube Codes'])

    if "Country Code" in orig.columns:
        orig = functions.standardize_country_codes(orig)
    if "Country Code" in new.columns:
        new = functions.standardize_country_codes(new)

    # Rename columns according to mapping
    orig = orig.rename(columns={k: v for k, v in ds["column_mapping"].items() if k in orig.columns})
    new  = new.rename(columns={k: v for k, v in ds["column_mapping"].items() if k in new.columns})

    # Special preprocessing for Country Percentage dataset
    if ds['preprocess']['week_mapping']:
        # add w/c using Week Number
        orig = orig.merge(week_map, left_on='Week Number', right_on='WeekNumber_finYear',
                                              how='left').drop(columns=['Week Number', 'WeekNumber_finYear'])

    # Ensure 'w/c' columns are datetime in both DataFrames
    if 'w/c' in orig.columns:
        orig['w/c'] = pd.to_datetime(orig['w/c'], errors='coerce')
    if 'w/c' in new.columns:
        new['w/c'] = pd.to_datetime(new['w/c'], errors='coerce')

    missing, different = functions.run_comparison(
        orig, new,
        ds["column_mapping"],
        ds["key_columns"],
        method=ds.get("method", "integer"),
        threshold=ds.get("threshold", 0.0001)
    )

    print("Rows missing from new:")
    display(missing)
    print("Rows with differences:")
    if not different.empty:
        numeric_cols = [col for col in different.columns if col.endswith('_orig') and pd.api.types.is_numeric_dtype(different[col])]
    
        for col in numeric_cols:
            base_col = col.replace('_orig', '')
            new_col = f"{base_col}_new"
            diff_col = f"{base_col}_diff"
            if new_col in different.columns:
                different[diff_col] = different[col] - different[new_col]
        
            display(different.sort_values(by=[col for col in different.columns if col.endswith('_diff')][0], ascending=False))
        else:
            display(different)

--- Processing Twitter ALL Platform ---
Rows missing from new:

            w/c PlaceID ServiceID PlatformID  Reach_orig  Reach_new     _merge
8    2024-04-01     BHZ       ALL        TWI         327       <NA>  left_only
19   2024-04-01     CRO       ALL        TWI         218       <NA>  left_only
56   2024-04-01     MLD       ALL        TWI          35       <NA>  left_only
58   2024-04-01     MTG       ALL        TWI         327       <NA>  left_only
59   2024-04-01     NAM       ALL        TWI           0       <NA>  left_only
...         ...     ...       ...        ...         ...        ...        ...
5336 2025-03-24     BHZ       ALL        TWI         101       <NA>  left_only
5347 2025-03-24     CRO       ALL        TWI          67       <NA>  left_only
5384 2025-03-24     MLD       ALL        TWI          16       <NA>  left_only
5386 2025-03-24     MTG       ALL        TWI         101       <NA>  left_only
5404 2025-03-24     SER       ALL        TWI        2288       <NA>  left_only

[322 rows x 7 columns]

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
1280,2024-06-17,USA,ALL,TWI,5800975,80468,both,5720507
1386,2024-06-24,USA,ALL,TWI,4727797,45604,both,4682193
1279,2024-06-17,USA,ALL,TWI,5800975,1395513,both,4405462
1810,2024-07-22,USA,ALL,TWI,4209366,50944,both,4158422
1385,2024-06-24,USA,ALL,TWI,4727797,761850,both,3965947
...,...,...,...,...,...,...,...,...
2228,2024-08-19,UK,ALL,TWI,263516,1970504,both,-1706988
525,2024-04-29,UK,ALL,TWI,214514,2000412,both,-1785898
1169,2024-06-10,UK,ALL,TWI,139578,2246654,both,-2107076
2850,2024-09-30,USA,ALL,TWI,804967,3207133,both,-2402166
3571,2024-11-18,USA,ALL,TWI,583260,4187681,both,-3604421

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
0,2024-04-01,AFG,ALL,TWI,14796,16755,both,-1959
1,2024-04-01,ARG,ALL,TWI,3112,11513,both,-8401
2,2024-04-01,AUS,ALL,TWI,389161,152934,both,236227
3,2024-04-01,AUS,ALL,TWI,389161,336782,both,52379
4,2024-04-01,AZE,ALL,TWI,15,48,both,-33
...,...,...,...,...,...,...,...,...
5426,2025-03-24,USA,ALL,TWI,464997,45577,both,419420
5427,2025-03-24,UZB,ALL,TWI,30,0,both,30
5428,2025-03-24,VEN,ALL,TWI,5076,0,both,5076
5429,2025-03-24,YEM,ALL,TWI,253,0,both,253
5430,2025-03-24,ZAI,ALL,TWI,286,0,both,286

--- Processing Twitter ANW Platform ---
Rows missing from new:

            w/c PlaceID ServiceID PlatformID  Reach_orig  Reach_new     _merge
9    2024-04-01     BHZ       ANW        TWI         327       <NA>  left_only
20   2024-04-01     CRO       ANW        TWI         218       <NA>  left_only
57   2024-04-01     MLD       ANW        TWI          35       <NA>  left_only
59   2024-04-01     MTG       ANW        TWI         327       <NA>  left_only
70   2024-04-01     PAR       ANW        TWI           0       <NA>  left_only
...         ...     ...       ...        ...         ...        ...        ...
5531 2025-03-24     BHZ       ANW        TWI         101       <NA>  left_only
5541 2025-03-24     CRO       ANW        TWI          67       <NA>  left_only
5574 2025-03-24     MLD       ANW        TWI          16       <NA>  left_only
5576 2025-03-24     MTG       ANW        TWI         101       <NA>  left_only
5594 2025-03-24     SER       ANW        TWI        2288       <NA>  left_only

[264 rows x 7 columns]

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
5606,2025-03-24,TUR,ANW,TWI,1126247,0,both,1126247
5607,2025-03-24,TUR,ANW,TWI,1126247,208,both,1126039
5078,2025-02-17,INO,ANW,TWI,840500,136,both,840364
5077,2025-02-17,INO,ANW,TWI,840500,36665,both,803835
98,2024-04-01,TUR,ANW,TWI,668736,636,both,668100
...,...,...,...,...,...,...,...,...
3542,2024-11-11,BRA,ANW,TWI,39674,668470,both,-628796
986,2024-05-27,USA,ANW,TWI,123476,860373,both,-736897
2247,2024-08-19,IND,ANW,TWI,193124,1212096,both,-1018972
4667,2025-01-20,IND,ANW,TWI,208687,1305211,both,-1096524
1693,2024-07-15,IND,ANW,TWI,186495,1516370,both,-1329875

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
0,2024-04-01,AFG,ANW,TWI,14796,16755,both,-1959
1,2024-04-01,ARG,ANW,TWI,3112,11093,both,-7981
2,2024-04-01,ARG,ANW,TWI,3112,420,both,2692
3,2024-04-01,AUS,ANW,TWI,29557,38775,both,-9218
4,2024-04-01,AUS,ANW,TWI,29557,478,both,29079
...,...,...,...,...,...,...,...,...
5614,2025-03-24,USA,ANW,TWI,110519,1135,both,109384
5615,2025-03-24,UZB,ANW,TWI,30,0,both,30
5616,2025-03-24,VEN,ANW,TWI,5076,0,both,5076
5617,2025-03-24,YEM,ANW,TWI,253,0,both,253
5618,2025-03-24,ZAI,ANW,TWI,286,0,both,286

--- Processing Twitter ANY Platform ---
Rows missing from new:

            w/c PlaceID ServiceID PlatformID  Reach_orig  Reach_new     _merge
8    2024-04-01     BHZ       ANY        TWI         327       <NA>  left_only
19   2024-04-01     CRO       ANY        TWI         218       <NA>  left_only
55   2024-04-01     MLD       ANY        TWI          35       <NA>  left_only
57   2024-04-01     MTG       ANY        TWI         327       <NA>  left_only
67   2024-04-01     PAR       ANY        TWI           0       <NA>  left_only
...         ...     ...       ...        ...         ...        ...        ...
5149 2025-03-24     BHZ       ANY        TWI         101       <NA>  left_only
5159 2025-03-24     CRO       ANY        TWI          67       <NA>  left_only
5192 2025-03-24     MLD       ANY        TWI          16       <NA>  left_only
5194 2025-03-24     MTG       ANY        TWI         101       <NA>  left_only
5214 2025-03-24     SER       ANY        TWI        2288       <NA>  left_only

[264 rows x 7 columns]

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
1236,2024-06-17,USA,ANY,TWI,5778287,225037,both,5553250
1237,2024-06-17,USA,ANY,TWI,5778287,1170458,both,4607829
1339,2024-06-24,USA,ANY,TWI,4698064,177624,both,4520440
1340,2024-06-24,USA,ANY,TWI,4698064,584214,both,4113850
1752,2024-07-22,USA,ANY,TWI,4177308,397327,both,3779981
...,...,...,...,...,...,...,...,...
2159,2024-08-19,UK,ANY,TWI,263493,1874986,both,-1611493
513,2024-04-29,UK,ANY,TWI,214429,1937542,both,-1723113
1131,2024-06-10,UK,ANY,TWI,139561,2144735,both,-2005174
2760,2024-09-30,USA,ANY,TWI,768277,3007585,both,-2239308
3453,2024-11-18,USA,ANY,TWI,572543,4029521,both,-3456978

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
0,2024-04-01,AFG,ANY,TWI,14796,16755,both,-1959
1,2024-04-01,ARG,ANY,TWI,3112,11513,both,-8401
2,2024-04-01,AUS,ANY,TWI,77867,39253,both,38614
3,2024-04-01,AUS,ANY,TWI,77867,113681,both,-35814
4,2024-04-01,AZE,ANY,TWI,15,48,both,-33
...,...,...,...,...,...,...,...,...
5235,2025-03-24,USA,ANY,TWI,454133,0,both,454133
5236,2025-03-24,UZB,ANY,TWI,30,0,both,30
5237,2025-03-24,VEN,ANY,TWI,5076,0,both,5076
5238,2025-03-24,YEM,ANY,TWI,253,0,both,253
5239,2025-03-24,ZAI,ANY,TWI,286,0,both,286

--- Processing Twitter AX2 Platform ---
Rows missing from new:

            w/c PlaceID ServiceID PlatformID  Reach_orig  Reach_new     _merge
7    2024-04-01     BHZ       AX2        TWI         327       <NA>  left_only
16   2024-04-01     CRO       AX2        TWI         218       <NA>  left_only
42   2024-04-01     MLD       AX2        TWI          35       <NA>  left_only
44   2024-04-01     MTG       AX2        TWI         327       <NA>  left_only
51   2024-04-01     PAR       AX2        TWI           0       <NA>  left_only
...         ...     ...       ...        ...         ...        ...        ...
4098 2025-03-24     BHZ       AX2        TWI         101       <NA>  left_only
4107 2025-03-24     CRO       AX2        TWI          67       <NA>  left_only
4133 2025-03-24     MLD       AX2        TWI          16       <NA>  left_only
4135 2025-03-24     MTG       AX2        TWI         101       <NA>  left_only
4151 2025-03-24     SER       AX2        TWI        2288       <NA>  left_only

[264 rows x 7 columns]

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
4161,2025-03-24,TUR,AX2,TWI,1125975,0,both,1125975
3720,2025-02-17,INO,AX2,TWI,839539,36665,both,802874
750,2024-06-03,IND,AX2,TWI,649418,249754,both,399664
4039,2025-03-17,IND,AX2,TWI,366930,0,both,366930
4040,2025-03-17,INO,AX2,TWI,314255,0,both,314255
...,...,...,...,...,...,...,...,...
2580,2024-11-11,BRA,AX2,TWI,39674,668470,both,-628796
717,2024-05-27,USA,AX2,TWI,121651,860373,both,-738722
1639,2024-08-19,IND,AX2,TWI,192765,1212096,both,-1019331
3399,2025-01-20,IND,AX2,TWI,208594,1305211,both,-1096617
1235,2024-07-15,IND,AX2,TWI,185847,1516370,both,-1330523

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
0,2024-04-01,AFG,AX2,TWI,14796,16755,both,-1959
1,2024-04-01,ARG,AX2,TWI,3062,11093,both,-8031
2,2024-04-01,AUS,AX2,TWI,29296,38775,both,-9479
3,2024-04-01,AZE,AX2,TWI,15,48,both,-33
4,2024-04-01,BAH,AX2,TWI,820,1694,both,-874
...,...,...,...,...,...,...,...,...
4166,2025-03-24,USA,AX2,TWI,109123,0,both,109123
4167,2025-03-24,UZB,AX2,TWI,30,0,both,30
4168,2025-03-24,VEN,AX2,TWI,5076,0,both,5076
4169,2025-03-24,YEM,AX2,TWI,253,0,both,253
4170,2025-03-24,ZAI,AX2,TWI,286,0,both,286

--- Processing Twitter AXE Platform ---
Rows missing from new:

            w/c PlaceID ServiceID PlatformID  Reach_orig  Reach_new     _merge
7    2024-04-01     BHZ       AXE        TWI         327       <NA>  left_only
16   2024-04-01     CRO       AXE        TWI         218       <NA>  left_only
42   2024-04-01     MLD       AXE        TWI          35       <NA>  left_only
44   2024-04-01     MTG       AXE        TWI         327       <NA>  left_only
51   2024-04-01     PAR       AXE        TWI           0       <NA>  left_only
...         ...     ...       ...        ...         ...        ...        ...
4098 2025-03-24     BHZ       AXE        TWI         101       <NA>  left_only
4107 2025-03-24     CRO       AXE        TWI          67       <NA>  left_only
4133 2025-03-24     MLD       AXE        TWI          16       <NA>  left_only
4135 2025-03-24     MTG       AXE        TWI         101       <NA>  left_only
4151 2025-03-24     SER       AXE        TWI        2288       <NA>  left_only

[264 rows x 7 columns]

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
4161,2025-03-24,TUR,AXE,TWI,1125975,0,both,1125975
3720,2025-02-17,INO,AXE,TWI,837410,34013,both,803397
750,2024-06-03,IND,AXE,TWI,649418,249754,both,399664
4039,2025-03-17,IND,AXE,TWI,366930,0,both,366930
4040,2025-03-17,INO,AXE,TWI,300036,0,both,300036
...,...,...,...,...,...,...,...,...
2580,2024-11-11,BRA,AXE,TWI,39674,668470,both,-628796
717,2024-05-27,USA,AXE,TWI,90939,851191,both,-760252
1639,2024-08-19,IND,AXE,TWI,192765,1212096,both,-1019331
3399,2025-01-20,IND,AXE,TWI,208594,1305211,both,-1096617
1235,2024-07-15,IND,AXE,TWI,185847,1516370,both,-1330523

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
0,2024-04-01,AFG,AXE,TWI,14796,16755,both,-1959
1,2024-04-01,ARG,AXE,TWI,3062,11093,both,-8031
2,2024-04-01,AUS,AXE,TWI,29296,38775,both,-9479
3,2024-04-01,AZE,AXE,TWI,15,48,both,-33
4,2024-04-01,BAH,AXE,TWI,820,1694,both,-874
...,...,...,...,...,...,...,...,...
4166,2025-03-24,USA,AXE,TWI,93133,0,both,93133
4167,2025-03-24,UZB,AXE,TWI,30,0,both,30
4168,2025-03-24,VEN,AXE,TWI,5076,0,both,5076
4169,2025-03-24,YEM,AXE,TWI,253,0,both,253
4170,2025-03-24,ZAI,AXE,TWI,286,0,both,286

--- Processing Twitter EN2 Platform ---
Rows missing from new:

            w/c PlaceID ServiceID PlatformID  Reach_orig  Reach_new     _merge
1484 2025-01-27     ARG       EN2        TWI           9       <NA>  left_only
1488 2025-01-27     CHI       EN2        TWI           1       <NA>  left_only
1489 2025-01-27     EGY       EN2        TWI           1       <NA>  left_only
1492 2025-01-27     GHA       EN2        TWI           2       <NA>  left_only
1502 2025-01-27     NET       EN2        TWI           1       <NA>  left_only
1506 2025-01-27     RWA       EN2        TWI           0       <NA>  left_only
1507 2025-01-27     SAF       EN2        TWI           0       <NA>  left_only
1511 2025-01-27     SWE       EN2        TWI           1       <NA>  left_only

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
419,2024-06-17,USA,EN2,TWI,5668888,1247101,both,4421787
454,2024-06-24,USA,EN2,TWI,4646729,627282,both,4019447
594,2024-07-22,USA,EN2,TWI,4045472,445896,both,3599576
524,2024-07-08,USA,EN2,TWI,2527390,1009161,both,1518229
405,2024-06-17,NIG,EN2,TWI,1368746,86857,both,1281889
...,...,...,...,...,...,...,...,...
173,2024-04-29,UK,EN2,TWI,165758,1958338,both,-1792580
1145,2024-11-18,AUS,EN2,TWI,121220,1977562,both,-1856342
383,2024-06-10,UK,EN2,TWI,101608,2181330,both,-2079722
939,2024-09-30,USA,EN2,TWI,649671,3043164,both,-2393493
1177,2024-11-18,USA,EN2,TWI,435127,4217096,both,-3781969

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
0,2024-04-01,ARG,EN2,TWI,54,420,both,-366
1,2024-04-01,AUS,EN2,TWI,364289,445505,both,-81216
2,2024-04-01,BRA,EN2,TWI,1250,3017,both,-1767
3,2024-04-01,CAN,EN2,TWI,73583,220294,both,-146711
4,2024-04-01,CHI,EN2,TWI,8,65,both,-57
...,...,...,...,...,...,...,...,...
1729,2025-03-24,THA,EN2,TWI,3149,1913,both,1236
1730,2025-03-24,TUR,EN2,TWI,25835,1866,both,23969
1731,2025-03-24,UAE,EN2,TWI,16,0,both,16
1732,2025-03-24,UK,EN2,TWI,172898,27616,both,145282
1733,2025-03-24,USA,EN2,TWI,371231,46658,both,324573

--- Processing Twitter ENG Platform ---
Rows missing from new:

            w/c PlaceID ServiceID PlatformID  Reach_orig  Reach_new     _merge
1355 2025-01-27     ARG       ENG        TWI           9       <NA>  left_only
1358 2025-01-27     CHI       ENG        TWI           1       <NA>  left_only
1359 2025-01-27     EGY       ENG        TWI           1       <NA>  left_only
1362 2025-01-27     GHA       ENG        TWI           2       <NA>  left_only
1366 2025-01-27     ITA       ENG        TWI           0       <NA>  left_only
1371 2025-01-27     NET       ENG        TWI           1       <NA>  left_only
1375 2025-01-27     RWA       ENG        TWI           0       <NA>  left_only
1376 2025-01-27     SAF       ENG        TWI           0       <NA>  left_only
1380 2025-01-27     SWE       ENG        TWI           1       <NA>  left_only

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
383,2024-06-17,USA,ENG,TWI,5639017,1175236,both,4463781
415,2024-06-24,USA,ENG,TWI,4607590,586560,both,4021030
543,2024-07-22,USA,ENG,TWI,4003274,400406,both,3602868
479,2024-07-08,USA,ENG,TWI,2471536,953168,both,1518368
370,2024-06-17,NIG,ENG,TWI,1368746,86857,both,1281889
...,...,...,...,...,...,...,...,...
670,2024-08-19,UK,ENG,TWI,217789,1882452,both,-1664663
158,2024-04-29,UK,ENG,TWI,165747,1944912,both,-1779165
350,2024-06-10,UK,ENG,TWI,101599,2169626,both,-2068027
858,2024-09-30,USA,ENG,TWI,601442,3010384,both,-2408942
1075,2024-11-18,USA,ENG,TWI,421056,4047489,both,-3626433

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
0,2024-04-01,ARG,ENG,TWI,54,420,both,-366
1,2024-04-01,AUS,ENG,TWI,51752,114157,both,-62405
2,2024-04-01,CAN,ENG,TWI,66947,209173,both,-142226
3,2024-04-01,CHI,ENG,TWI,8,65,both,-57
4,2024-04-01,COL,ENG,TWI,21,4,both,17
...,...,...,...,...,...,...,...,...
1566,2025-03-24,THA,ENG,TWI,366,258,both,108
1567,2025-03-24,TUR,ENG,TWI,23335,208,both,23127
1568,2025-03-24,UAE,ENG,TWI,16,0,both,16
1569,2025-03-24,UK,ENG,TWI,172887,3709,both,169178
1570,2025-03-24,USA,ENG,TWI,356934,1135,both,355799

--- Processing Twitter ENW Platform ---
Rows missing from new:

            w/c PlaceID ServiceID PlatformID  Reach_orig  Reach_new     _merge
1290 2025-01-27     ARG       ENW        TWI           9       <NA>  left_only
1293 2025-01-27     CHI       ENW        TWI           1       <NA>  left_only
1294 2025-01-27     EGY       ENW        TWI           1       <NA>  left_only
1297 2025-01-27     GHA       ENW        TWI           2       <NA>  left_only
1301 2025-01-27     ITA       ENW        TWI           0       <NA>  left_only
1305 2025-01-27     NET       ENW        TWI           1       <NA>  left_only
1308 2025-01-27     PAK       ENW        TWI           0       <NA>  left_only
1309 2025-01-27     RWA       ENW        TWI           0       <NA>  left_only
1312 2025-01-27     SIN       ENW        TWI           1       <NA>  left_only
1314 2025-01-27     SWE       ENW        TWI           1       <NA>  left_only
1317 2025-01-27     UAE       ENW        TWI           1       <NA>  left_only

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
658,2024-08-26,UK,ENW,TWI,121647,64326,both,57321
659,2024-08-26,USA,ENW,TWI,113284,58924,both,54360
508,2024-07-22,UK,ENW,TWI,64990,16401,both,48589
509,2024-07-22,USA,ENW,TWI,60137,12847,both,47290
1169,2024-12-23,USA,ENW,TWI,73899,31720,both,42179
...,...,...,...,...,...,...,...,...
1198,2024-12-30,UK,ENW,TWI,16224,74900,both,-58676
749,2024-09-16,USA,ENW,TWI,30027,131156,both,-101129
748,2024-09-16,UK,ENW,TWI,31385,134829,both,-103444
89,2024-04-15,USA,ENW,TWI,12532,129578,both,-117046
88,2024-04-15,UK,ENW,TWI,14981,147802,both,-132821

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
0,2024-04-01,ARG,ENW,TWI,54,420,both,-366
1,2024-04-01,AUS,ENW,TWI,281,478,both,-197
2,2024-04-01,CAN,ENW,TWI,1161,1353,both,-192
3,2024-04-01,CHI,ENW,TWI,8,65,both,-57
4,2024-04-01,EGY,ENW,TWI,4,32,both,-28
...,...,...,...,...,...,...,...,...
1478,2025-03-24,SPA,ENW,TWI,104,87,both,17
1479,2025-03-24,THA,ENW,TWI,366,258,both,108
1480,2025-03-24,TUR,ENW,TWI,293,208,both,85
1481,2025-03-24,UK,ENW,TWI,20163,3709,both,16454
1482,2025-03-24,USA,ENW,TWI,17494,1135,both,16359

--- Processing Twitter FOA Platform ---
Rows missing from new:

Empty DataFrame
Columns: [w/c, PlaceID, ServiceID, PlatformID, Reach_orig, Reach_new, _merge]
Index: []

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
389,2024-12-23,USA,FOA,TWI,71739,9388,both,62351
388,2024-12-23,UK,FOA,TWI,71739,9388,both,62351
218,2024-08-26,UK,FOA,TWI,104158,52322,both,51836
219,2024-08-26,USA,FOA,TWI,104158,52322,both,51836
169,2024-07-22,USA,FOA,TWI,57674,9763,both,47911
...,...,...,...,...,...,...,...,...
399,2024-12-30,USA,FOA,TWI,8744,57813,both,-49069
28,2024-04-15,UK,FOA,TWI,10437,104008,both,-93571
29,2024-04-15,USA,FOA,TWI,10437,104008,both,-93571
248,2024-09-16,UK,FOA,TWI,28370,127477,both,-99107
249,2024-09-16,USA,FOA,TWI,28370,127477,both,-99107

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
0,2024-04-01,CAN,FOA,TWI,767,814,both,-47
1,2024-04-01,FRA,FOA,TWI,767,814,both,-47
2,2024-04-01,INO,FOA,TWI,2302,2442,both,-140
3,2024-04-01,KEN,FOA,TWI,3070,3256,both,-186
4,2024-04-01,MAL,FOA,TWI,1535,1628,both,-93
...,...,...,...,...,...,...,...,...
515,2025-03-24,NIG,FOA,TWI,4703,0,both,4703
516,2025-03-24,SAF,FOA,TWI,5644,0,both,5644
517,2025-03-24,SAU,FOA,TWI,1881,0,both,1881
518,2025-03-24,UK,FOA,TWI,15990,0,both,15990
519,2025-03-24,USA,FOA,TWI,15990,0,both,15990

--- Processing Twitter GNL Platform ---
Rows missing from new:

Empty DataFrame
Columns: [w/c, PlaceID, ServiceID, PlatformID, Reach_orig, Reach_new, _merge]
Index: []

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
253,2024-06-17,USA,GNL,TWI,5637425,1170458,both,4466967
273,2024-06-24,USA,GNL,TWI,4606168,584214,both,4021954
353,2024-07-22,USA,GNL,TWI,4000843,397327,both,3603516
313,2024-07-08,USA,GNL,TWI,2470322,950187,both,1520135
245,2024-06-17,NIG,GNL,TWI,1368732,86853,both,1281879
...,...,...,...,...,...,...,...,...
432,2024-08-19,UK,GNL,TWI,214645,1874986,both,-1660341
108,2024-04-29,UK,GNL,TWI,161189,1937542,both,-1776353
232,2024-06-10,UK,GNL,TWI,95804,2144735,both,-2048931
539,2024-09-30,USA,GNL,TWI,598485,3007585,both,-2409100
658,2024-11-18,USA,GNL,TWI,420034,4029521,both,-3609487

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
0,2024-04-01,AUS,GNL,TWI,51471,113681,both,-62210
1,2024-04-01,CAN,GNL,TWI,66555,208636,both,-142081
2,2024-04-01,COL,GNL,TWI,21,4,both,17
3,2024-04-01,FRA,GNL,TWI,1,0,both,1
4,2024-04-01,GER,GNL,TWI,31,8,both,23
...,...,...,...,...,...,...,...,...
960,2025-03-24,SPA,GNL,TWI,51998,0,both,51998
961,2025-03-24,TUR,GNL,TWI,23042,0,both,23042
962,2025-03-24,UAE,GNL,TWI,16,0,both,16
963,2025-03-24,UK,GNL,TWI,168724,0,both,168724
964,2025-03-24,USA,GNL,TWI,355432,0,both,355432

--- Processing Twitter MA- Platform ---
Rows missing from new:

           w/c PlaceID ServiceID PlatformID  Reach_orig  Reach_new     _merge
4   2024-04-01     INO       MA-        TWI           0       <NA>  left_only
6   2024-04-01     NAM       MA-        TWI           0       <NA>  left_only
7   2024-04-01     NEP       MA-        TWI           0       <NA>  left_only
8   2024-04-01     NIG       MA-        TWI           0       <NA>  left_only
9   2024-04-01     PAK       MA-        TWI           0       <NA>  left_only
..         ...     ...       ...        ...         ...        ...        ...
711 2025-02-03     PAK       MA-        TWI           0       <NA>  left_only
714 2025-02-03     SWE       MA-        TWI           0       <NA>  left_only
736 2025-02-17     NEP       MA-        TWI           0       <NA>  left_only
737 2025-02-17     PAK       MA-        TWI           0       <NA>  left_only
740 2025-02-17     SWE       MA-        TWI           0       <NA>  left_only

[190 rows x 7 columns]

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
513,2024-10-21,IND,MA-,TWI,1023,21,both,1002
539,2024-11-04,IND,MA-,TWI,877,79,both,798
716,2025-02-03,UK,MA-,TWI,680,21,both,659
487,2024-10-07,IND,MA-,TWI,743,154,both,589
461,2024-09-23,IND,MA-,TWI,589,8,both,581
...,...,...,...,...,...,...,...,...
456,2024-09-16,UK,MA-,TWI,4,157,both,-153
84,2024-04-22,UK,MA-,TWI,32,187,both,-155
106,2024-04-29,UK,MA-,TWI,85,247,both,-162
392,2024-08-12,UK,MA-,TWI,31,212,both,-181
341,2024-07-22,UK,MA-,TWI,47,237,both,-190

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
0,2024-04-01,CAN,MA-,TWI,4,11,both,-7
1,2024-04-01,FRA,MA-,TWI,2,5,both,-3
2,2024-04-01,GER,MA-,TWI,2,5,both,-3
3,2024-04-01,IND,MA-,TWI,3,8,both,-5
5,2024-04-01,KEN,MA-,TWI,2,5,both,-3
...,...,...,...,...,...,...,...,...
773,2025-03-10,IND,MA-,TWI,0,1,both,-1
774,2025-03-10,KEN,MA-,TWI,0,1,both,-1
778,2025-03-10,SPA,MA-,TWI,0,1,both,-1
781,2025-03-10,UK,MA-,TWI,2,14,both,-12
782,2025-03-10,USA,MA-,TWI,1,4,both,-3

--- Processing Twitter TOT Platform ---
Rows missing from new:

            w/c PlaceID ServiceID PlatformID  Reach_orig  Reach_new     _merge
7    2024-04-01     BHZ       TOT        TWI         327       <NA>  left_only
17   2024-04-01     CRO       TOT        TWI         218       <NA>  left_only
48   2024-04-01     MLD       TOT        TWI          35       <NA>  left_only
50   2024-04-01     MTG       TOT        TWI         327       <NA>  left_only
51   2024-04-01     NAM       TOT        TWI           0       <NA>  left_only
...         ...     ...       ...        ...         ...        ...        ...
4864 2025-03-24     BHZ       TOT        TWI         101       <NA>  left_only
4874 2025-03-24     CRO       TOT        TWI          67       <NA>  left_only
4905 2025-03-24     MLD       TOT        TWI          16       <NA>  left_only
4907 2025-03-24     MTG       TOT        TWI         101       <NA>  left_only
4927 2025-03-24     SER       TOT        TWI        2288       <NA>  left_only

[322 rows x 7 columns]

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
1148,2024-06-17,USA,TOT,TWI,5778297,18,both,5778279
1243,2024-06-24,USA,TOT,TWI,4698068,12,both,4698056
1147,2024-06-17,USA,TOT,TWI,5778297,1395495,both,4382802
1623,2024-07-22,USA,TOT,TWI,4177321,63,both,4177258
1242,2024-06-24,USA,TOT,TWI,4698068,761838,both,3936230
...,...,...,...,...,...,...,...,...
2012,2024-08-19,UK,TOT,TWI,263516,1970446,both,-1706930
470,2024-04-29,UK,TOT,TWI,214514,2000165,both,-1785651
1048,2024-06-10,UK,TOT,TWI,139578,2246587,both,-2107009
2580,2024-09-30,USA,TOT,TWI,768317,3207103,both,-2438786
3245,2024-11-18,USA,TOT,TWI,572568,4187673,both,-3615105

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
0,2024-04-01,AFG,TOT,TWI,14796,16755,both,-1959
1,2024-04-01,ARG,TOT,TWI,3112,11513,both,-8401
2,2024-04-01,AUS,TOT,TWI,77867,152934,both,-75067
3,2024-04-01,AZE,TOT,TWI,15,48,both,-33
4,2024-04-01,BAH,TOT,TWI,820,1694,both,-874
...,...,...,...,...,...,...,...,...
4947,2025-03-24,USA,TOT,TWI,454133,0,both,454133
4948,2025-03-24,UZB,TOT,TWI,30,0,both,30
4949,2025-03-24,VEN,TOT,TWI,5076,0,both,5076
4950,2025-03-24,YEM,TOT,TWI,253,0,both,253
4951,2025-03-24,ZAI,TOT,TWI,286,0,both,286

--- Processing Twitter WOR Platform ---
Rows missing from new:

Empty DataFrame
Columns: [w/c, PlaceID, ServiceID, PlatformID, Reach_orig, Reach_new, _merge]
Index: []

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
21,2024-04-08,AUS,WOR,TWI,945545,248131,both,697414
210,2024-06-10,AUS,WOR,TWI,683960,210161,both,473799
42,2024-04-15,AUS,WOR,TWI,679894,262763,both,417131
63,2024-04-22,AUS,WOR,TWI,603550,207916,both,395634
567,2024-10-07,AUS,WOR,TWI,367426,100553,both,266873
...,...,...,...,...,...,...,...,...
125,2024-05-06,USA,WOR,TWI,74687,378098,both,-303411
1071,2025-03-24,AUS,WOR,TWI,22259,333628,both,-311369
504,2024-09-16,AUS,WOR,TWI,87368,448383,both,-361015
672,2024-11-11,AUS,WOR,TWI,155765,648097,both,-492332
693,2024-11-18,AUS,WOR,TWI,79775,1504647,both,-1424872

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
0,2024-04-01,AUS,WOR,TWI,315001,336782,both,-21781
1,2024-04-01,BRA,WOR,TWI,1250,3017,both,-1767
2,2024-04-01,CAN,WOR,TWI,7431,12452,both,-5021
3,2024-04-01,FRA,WOR,TWI,2699,6361,both,-3662
4,2024-04-01,GER,WOR,TWI,3322,7868,both,-4546
...,...,...,...,...,...,...,...,...
1086,2025-03-24,SPA,WOR,TWI,1960,1167,both,793
1087,2025-03-24,SWI,WOR,TWI,1416,4848,both,-3432
1088,2025-03-24,THA,WOR,TWI,2800,1668,both,1132
1089,2025-03-24,TUR,WOR,TWI,2800,1668,both,1132
1091,2025-03-24,USA,WOR,TWI,16011,45577,both,-29566

--- Processing Twitter WSE Platform ---
Rows missing from new:

            w/c PlaceID ServiceID PlatformID  Reach_orig  Reach_new     _merge
1290 2025-01-27     ARG       WSE        TWI           9       <NA>  left_only
1293 2025-01-27     CHI       WSE        TWI           1       <NA>  left_only
1294 2025-01-27     EGY       WSE        TWI           1       <NA>  left_only
1297 2025-01-27     GHA       WSE        TWI           2       <NA>  left_only
1301 2025-01-27     ITA       WSE        TWI           0       <NA>  left_only
1304 2025-01-27     MAL       WSE        TWI           1       <NA>  left_only
1305 2025-01-27     NET       WSE        TWI           1       <NA>  left_only
1306 2025-01-27     NIG       WSE        TWI           2       <NA>  left_only
1308 2025-01-27     PAK       WSE        TWI           0       <NA>  left_only
1309 2025-01-27     RWA       WSE        TWI           0       <NA>  left_only
1310 2025-01-27     SAF       WSE        TWI           0       <NA>  left_only
1312 2025-01-27     SIN       WSE        TWI           1       <NA>  left_only
1314 2025-01-27     SWE       WSE        TWI           1       <NA>  left_only
1317 2025-01-27     UAE       WSE        TWI           1       <NA>  left_only

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
568,2024-08-05,UK,WSE,TWI,38899,9894,both,29005
598,2024-08-12,UK,WSE,TWI,23260,9722,both,13538
1380,2025-02-17,UK,WSE,TWI,15639,2381,both,13258
538,2024-07-29,UK,WSE,TWI,16468,5444,both,11024
569,2024-08-05,USA,WSE,TWI,14719,5112,both,9607
...,...,...,...,...,...,...,...,...
89,2024-04-15,USA,WSE,TWI,2095,25579,both,-23484
1018,2024-11-18,UK,WSE,TWI,2238,31796,both,-29558
1168,2024-12-23,UK,WSE,TWI,3673,39493,both,-35820
838,2024-10-07,UK,WSE,TWI,2868,39097,both,-36229
88,2024-04-15,UK,WSE,TWI,4545,43864,both,-39319

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
0,2024-04-01,ARG,WSE,TWI,54,420,both,-366
1,2024-04-01,AUS,WSE,TWI,281,478,both,-197
2,2024-04-01,CAN,WSE,TWI,394,540,both,-146
3,2024-04-01,CHI,WSE,TWI,8,65,both,-57
4,2024-04-01,EGY,WSE,TWI,4,32,both,-28
...,...,...,...,...,...,...,...,...
1457,2025-03-24,SPA,WSE,TWI,104,87,both,17
1458,2025-03-24,THA,WSE,TWI,366,258,both,108
1459,2025-03-24,TUR,WSE,TWI,293,208,both,85
1460,2025-03-24,UK,WSE,TWI,4173,3709,both,464
1461,2025-03-24,USA,WSE,TWI,1503,1135,both,368

--- Processing Twitter WSL Platform ---
Rows missing from new:

            w/c PlaceID ServiceID PlatformID  Reach_orig  Reach_new     _merge
153  2024-04-01     PAR       SPA        TWI           0       <NA>  left_only
5137 2024-07-22     PAR       SPA        TWI           0       <NA>  left_only
5449 2024-07-29     PAR       SPA        TWI           0       <NA>  left_only
5761 2024-08-05     PAR       SPA        TWI           0       <NA>  left_only

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
16096,2025-03-24,TUR,TUR,TWI,1122939,0,both,1122939
14414,2025-02-17,INO,INO,TWI,837329,33863,both,803466
15658,2025-03-17,INO,INO,TWI,299951,0,both,299951
15970,2025-03-24,INO,INO,TWI,274979,0,both,274979
2890,2024-06-03,IND,HIN,TWI,480775,211714,both,269061
...,...,...,...,...,...,...,...,...
9990,2024-11-11,BRA,POR,TWI,39674,668470,both,-628796
2777,2024-05-27,USA,MAN,TWI,45066,733354,both,-688288
13162,2025-01-20,IND,HIN,TWI,154953,1183397,both,-1028444
6320,2024-08-19,IND,HIN,TWI,103178,1161768,both,-1058590
4761,2024-07-15,IND,HIN,TWI,76801,1344864,both,-1268063

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,Reach_diff
0,2024-04-01,AFG,DAR,TWI,590,282,both,308
1,2024-04-01,AFG,PAS,TWI,4811,3025,both,1786
2,2024-04-01,AFG,PER,TWI,9396,13447,both,-4051
3,2024-04-01,ARG,POR,TWI,585,1384,both,-799
4,2024-04-01,ARG,SPA,TWI,2477,9709,both,-7232
...,...,...,...,...,...,...,...,...
16179,2025-03-24,USA,UZB,TWI,2,0,both,2
16180,2025-03-24,UZB,UZB,TWI,30,0,both,30
16181,2025-03-24,VEN,SPA,TWI,5076,0,both,5076
16182,2025-03-24,YEM,ARA,TWI,253,0,both,253
16183,2025-03-24,ZAI,FRE,TWI,286,0,both,286