In [39]:
from IPython.display import display

import pandas as pd

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [40]:
import sys
from pathlib import Path

try:
    # Works in Python scripts
    helper_path = Path(__file__).resolve().parent.parent / "helper"
except NameError:
    # Works in Jupyter notebooks
    helper_path = Path().resolve().parent / "helper"

sys.path.insert(0, str(helper_path))

# Now import your modules
from config_GAM2025 import gam_info
import functions

In [41]:
# Load country mapping
country_map = pd.read_excel(f"../../{gam_info['lookup_file']}", sheet_name='CountryID')[['PlaceID', 'YT-_FBE_codes']]
# Load country mapping
week_map = pd.read_excel(f"../../{gam_info['lookup_file']}", sheet_name='GAM Period')[['w/c', 'WeekNumber_finYear']]

In [42]:
# Utility functions
def load_excel(path):
    return pd.read_excel(path, engine='openpyxl')

def load_csv(path):
    return pd.read_csv(path)

def standardize_country_codes(df, column='Country Code'):
    return df.replace({column: {'WLF': 'WFI', '* Total': 'Total'}})

def run_comparison(original_df, new_df, column_mapping, key_columns, method='integer', threshold=0.0001):
    if method == 'integer':
        return compare_dataframes_integer(original_df, new_df, column_mapping, key_columns)
    elif method == 'percentage':
        return compare_dataframes_percentage(original_df, new_df, column_mapping, key_columns, threshold)
    else:
        raise ValueError("Unknown comparison method")

In [43]:
def compare_dataframes_integer(original_df, new_df, column_mapping, key_columns_new):
    """
    Compare two DataFrames and return rows that are missing or different.

    Parameters:
    - original_df: DataFrame from the original source
    - new_df: DataFrame from the new source
    - column_mapping: dict mapping original_df column names to new_df column names
    - key_columns_new: list of key columns using new_df naming

    Returns:
    - missing_from_new: rows in original_df not found in new_df
    - differing_rows: rows where key matches but mapped columns differ
    """

    # Rename original_df to match new_df column names
    original_df_renamed = original_df.rename(columns=column_mapping)

    # Ensure all required columns exist
    all_columns = list(column_mapping.values())
    original_subset = original_df_renamed[all_columns].copy()
    new_subset = new_df[all_columns].copy()

    # Round numeric columns to nearest integer
    for col in all_columns:
        if pd.api.types.is_numeric_dtype(original_subset[col]) and pd.api.types.is_numeric_dtype(new_subset[col]):
            original_subset[col] = original_subset[col].round(0).astype('Int64')
            new_subset[col] = new_subset[col].round(0).astype('Int64')
        
    # Merge to find differences
    merged = pd.merge(
        original_subset,
        new_subset,
        on=key_columns_new,
        how='outer',
        suffixes=('_orig', '_new'),
        indicator=True
    )

    # Missing rows: present in original but not in new
    missing_from_new = merged[merged['_merge'] == 'left_only']

    # Differing rows: same keys but different values
    comparison_cols = [col for col in all_columns if col not in key_columns_new]
        
    differing_rows = merged[
        (merged['_merge'] == 'both') &
        merged[[f"{col}_orig" for col in comparison_cols]].ne(
            merged[[f"{col}_new" for col in comparison_cols]].values
        ).any(axis=1)
    ]

    return missing_from_new, differing_rows

In [44]:
def compare_dataframes_percentage(original_df, new_df, column_mapping, key_columns_new, threshold=0.0001):
    """
    Compare two DataFrames and return rows that are missing or have percentage differences.

    Parameters:
    - original_df: DataFrame from the original source
    - new_df: DataFrame from the new source
    - column_mapping: dict mapping original_df column names to new_df column names
    - key_columns_new: list of key columns using new_df naming
    - threshold: minimum absolute difference to consider as significant

    Returns:
    - missing_from_new: rows in original_df not found in new_df
    - differing_rows: rows where key matches but mapped columns differ beyond threshold
    """

    # Rename original_df to match new_df column names
    original_df_renamed = original_df.rename(columns=column_mapping)

    # Ensure all required columns exist
    all_columns = list(column_mapping.values())
    original_subset = original_df_renamed[all_columns].copy()
    new_subset = new_df[all_columns].copy()

    # Merge to find differences
    merged = pd.merge(
        original_subset,
        new_subset,
        on=key_columns_new,
        how='outer',
        suffixes=('_orig', '_new'),
        indicator=True
    )

    # Missing rows: present in original but not in new
    missing_from_new = merged[merged['_merge'] == 'left_only']

    # Compute differences
    comparison_cols = [col for col in all_columns if col not in key_columns_new]
    for col in comparison_cols:
        merged[f"{col}_diff"] = merged[f"{col}_new"] - merged[f"{col}_orig"]

    # Filter rows where any difference exceeds threshold
    diff_mask = merged['_merge'] == 'both'
    for col in comparison_cols:
        diff_mask &= merged[f"{col}_diff"].abs() > threshold

    differing_rows = merged[diff_mask]

    return missing_from_new, differing_rows

In [45]:
datasets = [
    {
        "name": "Unique Viewers",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/data/Final Raw/YouTube Unique Viewers.xlsx",
        "new_path": f"../data/processed/YT-/_{gam_info['file_timeinfo']}_uniqueViewer_withAds.csv",
        "column_mapping": {
            "Channel": "Channel ID",
            "YT Service Code": "ServiceID",
            "w/c": "w/c",
            "Unique viewers": "Unique viewers"
        },
        "key_columns": ["Channel ID", "ServiceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": False
        }
    },
    {
        "name": "Country Percentage",
        "original_path": "../data/interim/minnie_country_YT_data_2025.csv",
        "new_path": f"../data/processed/YT-/{gam_info['file_timeinfo']}_country_new.csv",
        "column_mapping": {
            "Channel": "Channel ID",
            "Country": "PlaceID",
            "Date": "w/c",
            "Country %": "country_%"
        },
        "key_columns": ["Channel ID", "w/c", "PlaceID"],
        "method": "percentage",
        "threshold": 0.0001,
        "preprocess": {
            "standardize_country": False,
            "week_mapping": False
        }
    },
    {
        "name": "GNL Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - GNL by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_GNLbyCountry.xlsx",
        "column_mapping": {
            "Service Code": "ServiceID",
            "Country Code": "PlaceID",
            "YouTube Engaged Reach": "Reach",
            "w/c": "w/c"
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "WSL Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - WSL by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_WSLbyCountry.xlsx",
        "column_mapping": {
            "Service Code": "ServiceID",
            "Country Code": "PlaceID",
            "YouTube Engaged Reach": "Reach",
            "w/c": "w/c"
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "WOR Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - WOR by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_WORbyCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "WSE Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - WSE by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_WSEbyCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "MA- Weekly",
        "original_path": "../test/alteryx_datasets/mk_weekly_MA_YT.csv",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_MA-byCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "FOA Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - FOA by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_FOAbyCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "AXE Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - AXE by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_AXEbyCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "AX2 Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - AX2 by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_AX2byCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "ANW Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - ANW by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_ANWbyCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "ANY Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - ANY by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_ANYbyCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "TOT Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - TOT by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_TOTbyCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "ALL Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - ALL by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_ALLbyCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "ENG Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - ENG by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_ENGbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c',
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
        },
        "key_columns": ["w/c", "ServiceID", "PlaceID"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "ENW Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - ENW by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_ENWbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c',
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
        },
        "key_columns": ["w/c", "ServiceID", "PlaceID"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "EN2 Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - EN2 by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_EN2byCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c',
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
        },
        "key_columns": ["w/c", "ServiceID", "PlaceID"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
]

In [46]:

# Execute comparisons
for ds in datasets:
    # TODO - test currently doesn't catch additional things in my dataset that are not in minnie's 
    # e.g. I included Studios for UK / Youtube and Minnie did not - that did not show up here
    print(f"\n--- Processing {ds['name']} ---")

    orig = load_excel(ds["original_path"]) if ds["original_path"].endswith(".xlsx") else load_csv(ds["original_path"])
    new  = load_excel(ds["new_path"]) if ds["new_path"].endswith(".xlsx") else load_csv(ds["new_path"])

    # Special preprocessing for Country Percentage dataset
    if ds["name"] == "Country Percentage":
        
        # Rename 'Country' to 'YouTube Codes' in original data and merge with mapping
        orig = orig.rename(columns={'Country': 'YT-_FBE_codes'})
        orig = orig.merge(country_map, on='YT-_FBE_codes', how='left').drop(columns=['YT-_FBE_codes'])

    if "Country Code" in orig.columns:
        orig = standardize_country_codes(orig)
    if "Country Code" in new.columns:
        new = standardize_country_codes(new)

    # Rename columns according to mapping
    orig = orig.rename(columns={k: v for k, v in ds["column_mapping"].items() if k in orig.columns})
    new  = new.rename(columns={k: v for k, v in ds["column_mapping"].items() if k in new.columns})

    # Special preprocessing for Country Percentage dataset
    if ds['preprocess']['week_mapping']:
        # add w/c using Week Number
        orig = orig.merge(week_map, left_on='Week Number', right_on='WeekNumber_finYear',
                                              how='left').drop(columns=['Week Number', 'WeekNumber_finYear'])

    # Ensure 'w/c' columns are datetime in both DataFrames
    if 'w/c' in orig.columns:
        orig['w/c'] = pd.to_datetime(orig['w/c'], errors='coerce')
    if 'w/c' in new.columns:
        new['w/c'] = pd.to_datetime(new['w/c'], errors='coerce')

    missing, different = run_comparison(
        orig, new,
        ds["column_mapping"],
        ds["key_columns"],
        method=ds.get("method", "integer"),
        threshold=ds.get("threshold", 0.0001)
    )

    print("Rows missing from new:")
    display(missing)
    print("Rows with differences:")
    if len(different) > 0:
        different['diff'] = different['Reach_orig'] - different['Reach_new']
        display(different.sort_values('diff', ascending=False))
    else:
        display(different)

--- Processing Unique Viewers ---
Rows missing from new:

Empty DataFrame
Columns: [Channel ID, ServiceID, w/c, Unique viewers_orig, Unique viewers_new, _merge]
Index: []

Rows with differences:

Empty DataFrame
Columns: [Channel ID, ServiceID, w/c, Unique viewers_orig, Unique viewers_new, _merge]
Index: []

--- Processing Country Percentage ---
Rows missing from new:

,Channel ID,PlaceID,w/c,country_%_orig,country_%_new,_merge
3815,UC0JypFmHP-9wh5A3JjJLpcA,NAM,2024-04-01,0.000010,NaN,left_only
3947,UC0JypFmHP-9wh5A3JjJLpcA,NAM,2024-04-08,0.000005,NaN,left_only
4080,UC0JypFmHP-9wh5A3JjJLpcA,NAM,2024-04-15,0.000005,NaN,left_only
4212,UC0JypFmHP-9wh5A3JjJLpcA,NAM,2024-04-22,0.000004,NaN,left_only
4356,UC0JypFmHP-9wh5A3JjJLpcA,NAM,2024-04-29,0.000006,NaN,left_only
...,...,...,...,...,...,...
941801,UCynLtJ9E2c34bui4ON0ovGw,NAM,2025-03-24,0.000094,NaN,left_only
942318,UCyxdPjbYBT7UMmGT-jaPMCg,NAM,2024-08-12,0.020408,NaN,left_only
942863,UCyxdPjbYBT7UMmGT-jaPMCg,NAM,2025-01-27,0.064516,NaN,left_only
942898,UCyxdPjbYBT7UMmGT-jaPMCg,NAM,2025-02-10,0.027027,NaN,left_only
947056,UCznzKevbLg9SjtfAbjXiNFw,NAM,2025-01-20,0.003610,NaN,left_only

Rows with differences:

Empty DataFrame
Columns: [Channel ID, PlaceID, w/c, country_%_orig, country_%_new, _merge, country_%_diff]
Index: []

--- Processing GNL Weekly ---
Rows missing from new:

     ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
7729       GNL     NAM        9969 2024-04-01       <NA>  left_only
7730       GNL     NAM       12031 2024-04-08       <NA>  left_only
7731       GNL     NAM       11668 2024-04-15       <NA>  left_only
7732       GNL     NAM        7274 2024-04-22       <NA>  left_only
7733       GNL     NAM        6692 2024-04-29       <NA>  left_only
7734       GNL     NAM        8746 2024-05-06       <NA>  left_only
7735       GNL     NAM       16953 2024-05-13       <NA>  left_only
7736       GNL     NAM       13055 2024-05-20       <NA>  left_only
7737       GNL     NAM       12789 2024-05-27       <NA>  left_only
7738       GNL     NAM        6498 2024-06-03       <NA>  left_only
7739       GNL     NAM        8869 2024-06-10       <NA>  left_only
7740       GNL     NAM        6823 2024-06-17       <NA>  left_only
7741       GNL     NAM        8090 2024-06-24       <NA>  left_only
7742       GNL     NAM        7417 2024-07-01       <NA>  left_only
7743       GNL     NAM       15739 2024-07-08       <NA>  left_only
7744       GNL     NAM       15156 2024-07-15       <NA>  left_only
7745       GNL     NAM        9867 2024-07-22       <NA>  left_only
7746       GNL     NAM        8619 2024-07-29       <NA>  left_only
7747       GNL     NAM        9112 2024-08-05       <NA>  left_only
7748       GNL     NAM       13595 2024-08-12       <NA>  left_only
7749       GNL     NAM       10663 2024-08-19       <NA>  left_only
7750       GNL     NAM        6972 2024-08-26       <NA>  left_only
7751       GNL     NAM        8880 2024-09-02       <NA>  left_only
7752       GNL     NAM       10890 2024-09-09       <NA>  left_only
7753       GNL     NAM       12014 2024-09-16       <NA>  left_only
7754       GNL     NAM        8827 2024-09-23       <NA>  left_only
7755       GNL     NAM       10954 2024-09-30       <NA>  left_only
7756       GNL     NAM        8471 2024-10-07       <NA>  left_only
7757       GNL     NAM        9323 2024-10-14       <NA>  left_only
7758       GNL     NAM        7640 2024-10-21       <NA>  left_only
7759       GNL     NAM        8082 2024-10-28       <NA>  left_only
7760       GNL     NAM       14855 2024-11-04       <NA>  left_only
7761       GNL     NAM        7950 2024-11-11       <NA>  left_only
7762       GNL     NAM       14886 2024-11-18       <NA>  left_only
7763       GNL     NAM        9960 2024-11-25       <NA>  left_only
7764       GNL     NAM        8833 2024-12-02       <NA>  left_only
7765       GNL     NAM        9158 2024-12-09       <NA>  left_only
7766       GNL     NAM        8818 2024-12-16       <NA>  left_only
7767       GNL     NAM        8565 2024-12-23       <NA>  left_only
7768       GNL     NAM        7886 2024-12-30       <NA>  left_only
7769       GNL     NAM       11050 2025-01-06       <NA>  left_only
7770       GNL     NAM       13013 2025-01-13       <NA>  left_only
7771       GNL     NAM        8721 2025-01-20       <NA>  left_only
7772       GNL     NAM       10551 2025-01-27       <NA>  left_only
7773       GNL     NAM       16864 2025-02-03       <NA>  left_only
7774       GNL     NAM       21547 2025-02-10       <NA>  left_only
7775       GNL     NAM       19324 2025-02-17       <NA>  left_only
7776       GNL     NAM       22881 2025-02-24       <NA>  left_only
7777       GNL     NAM       23024 2025-03-03       <NA>  left_only
7778       GNL     NAM       12431 2025-03-10       <NA>  left_only
7779       GNL     NAM        9012 2025-03-17       <NA>  left_only
7780       GNL     NAM       10933 2025-03-24       <NA>  left_only

Rows with differences:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

--- Processing WSL Weekly ---
Rows missing from new:

       ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
7379         ARA     NAM          49 2024-04-01       <NA>  left_only
7380         ARA     NAM          70 2024-04-08       <NA>  left_only
7381         ARA     NAM         316 2024-04-15       <NA>  left_only
7382         ARA     NAM         700 2024-04-22       <NA>  left_only
7383         ARA     NAM         172 2024-04-29       <NA>  left_only
...          ...     ...         ...        ...        ...        ...
299983       VIE     NAM           4 2025-01-27       <NA>  left_only
299984       VIE     NAM           1 2025-02-03       <NA>  left_only
299985       VIE     NAM           1 2025-02-10       <NA>  left_only
299986       VIE     NAM           1 2025-02-17       <NA>  left_only
299987       VIE     NAM           2 2025-03-24       <NA>  left_only

[5564 rows x 6 columns]

Rows with differences:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

--- Processing WOR Weekly ---
Rows missing from new:

      ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
7748        WOR     NAM       16199 2024-04-01       <NA>  left_only
7749        WOR     NAM       16397 2024-04-08       <NA>  left_only
7750        WOR     NAM       19189 2024-04-15       <NA>  left_only
7751        WOR     NAM       18720 2024-04-22       <NA>  left_only
7752        WOR     NAM       19691 2024-04-29       <NA>  left_only
...         ...     ...         ...        ...        ...        ...
12597       WOR     NaN        <NA> 2025-02-24       <NA>  left_only
12598       WOR     NaN        <NA> 2025-03-03       <NA>  left_only
12599       WOR     NaN        <NA> 2025-03-10       <NA>  left_only
12600       WOR     NaN        <NA> 2025-03-17       <NA>  left_only
12601       WOR     NaN        <NA> 2025-03-24       <NA>  left_only

[104 rows x 6 columns]

Rows with differences:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

--- Processing WSE Weekly ---
Rows missing from new:

     ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
7626       WSE     NAM        1232 2024-04-01       <NA>  left_only
7627       WSE     NAM        1956 2024-04-08       <NA>  left_only
7628       WSE     NAM        1809 2024-04-15       <NA>  left_only
7629       WSE     NAM         602 2024-04-22       <NA>  left_only
7630       WSE     NAM         735 2024-04-29       <NA>  left_only
7631       WSE     NAM         545 2024-05-06       <NA>  left_only
7632       WSE     NAM         999 2024-05-13       <NA>  left_only
7633       WSE     NAM        1029 2024-05-20       <NA>  left_only
7634       WSE     NAM         828 2024-05-27       <NA>  left_only
7635       WSE     NAM        2087 2024-06-03       <NA>  left_only
7636       WSE     NAM         968 2024-06-10       <NA>  left_only
7637       WSE     NAM         801 2024-06-17       <NA>  left_only
7638       WSE     NAM         820 2024-06-24       <NA>  left_only
7639       WSE     NAM         873 2024-07-01       <NA>  left_only
7640       WSE     NAM         823 2024-07-08       <NA>  left_only
7641       WSE     NAM        2880 2024-07-15       <NA>  left_only
7642       WSE     NAM        1642 2024-07-22       <NA>  left_only
7643       WSE     NAM         987 2024-07-29       <NA>  left_only
7644       WSE     NAM        1149 2024-08-05       <NA>  left_only
7645       WSE     NAM        1381 2024-08-12       <NA>  left_only
7646       WSE     NAM        1171 2024-08-19       <NA>  left_only
7647       WSE     NAM         953 2024-08-26       <NA>  left_only
7648       WSE     NAM         883 2024-09-02       <NA>  left_only
7649       WSE     NAM         773 2024-09-09       <NA>  left_only
7650       WSE     NAM         760 2024-09-16       <NA>  left_only
7651       WSE     NAM         608 2024-09-23       <NA>  left_only
7652       WSE     NAM         867 2024-09-30       <NA>  left_only
7653       WSE     NAM         902 2024-10-07       <NA>  left_only
7654       WSE     NAM         772 2024-10-14       <NA>  left_only
7655       WSE     NAM         659 2024-10-21       <NA>  left_only
7656       WSE     NAM         533 2024-10-28       <NA>  left_only
7657       WSE     NAM         775 2024-11-04       <NA>  left_only
7658       WSE     NAM         721 2024-11-11       <NA>  left_only
7659       WSE     NAM         778 2024-11-18       <NA>  left_only
7660       WSE     NAM         696 2024-11-25       <NA>  left_only
7661       WSE     NAM         545 2024-12-02       <NA>  left_only
7662       WSE     NAM         718 2024-12-09       <NA>  left_only
7663       WSE     NAM        1226 2024-12-16       <NA>  left_only
7664       WSE     NAM        3716 2024-12-23       <NA>  left_only
7665       WSE     NAM        2449 2024-12-30       <NA>  left_only
7666       WSE     NAM        1288 2025-01-06       <NA>  left_only
7667       WSE     NAM        1394 2025-01-13       <NA>  left_only
7668       WSE     NAM        1123 2025-01-20       <NA>  left_only
7669       WSE     NAM        1098 2025-01-27       <NA>  left_only
7670       WSE     NAM        1659 2025-02-03       <NA>  left_only
7671       WSE     NAM        1483 2025-02-10       <NA>  left_only
7672       WSE     NAM        1474 2025-02-17       <NA>  left_only
7673       WSE     NAM        1031 2025-02-24       <NA>  left_only
7674       WSE     NAM        1153 2025-03-03       <NA>  left_only
7675       WSE     NAM        1502 2025-03-10       <NA>  left_only
7676       WSE     NAM        1032 2025-03-17       <NA>  left_only
7677       WSE     NAM         612 2025-03-24       <NA>  left_only

Rows with differences:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

--- Processing MA- Weekly ---
Rows missing from new:

     ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
3068       MA-   Total       66566 2024-04-01       <NA>  left_only
3069       MA-   Total       53222 2024-04-08       <NA>  left_only
3070       MA-   Total       70504 2024-04-15       <NA>  left_only
3071       MA-   Total       69262 2024-04-22       <NA>  left_only
3072       MA-   Total       92958 2024-04-29       <NA>  left_only
3073       MA-   Total       72930 2024-05-06       <NA>  left_only
3074       MA-   Total       83665 2024-05-13       <NA>  left_only
3075       MA-   Total       84758 2024-05-20       <NA>  left_only
3076       MA-   Total       76328 2024-05-27       <NA>  left_only
3077       MA-   Total      187175 2024-06-03       <NA>  left_only
3078       MA-   Total      180652 2024-06-10       <NA>  left_only
3079       MA-   Total      273216 2024-06-17       <NA>  left_only
3080       MA-   Total      282322 2024-06-24       <NA>  left_only
3081       MA-   Total      348451 2024-07-01       <NA>  left_only
3082       MA-   Total      225474 2024-07-08       <NA>  left_only
3083       MA-   Total      152333 2024-07-15       <NA>  left_only
3084       MA-   Total      125535 2024-07-22       <NA>  left_only
3085       MA-   Total      150006 2024-07-29       <NA>  left_only
3086       MA-   Total      215169 2024-08-05       <NA>  left_only
3087       MA-   Total      235531 2024-08-12       <NA>  left_only
3088       MA-   Total      312654 2024-08-19       <NA>  left_only
3089       MA-   Total      322060 2024-08-26       <NA>  left_only
3090       MA-   Total      222038 2024-09-02       <NA>  left_only
3091       MA-   Total      304854 2024-09-09       <NA>  left_only
3092       MA-   Total      175660 2024-09-16       <NA>  left_only
3093       MA-   Total      140433 2024-09-23       <NA>  left_only
3094       MA-   Total       92867 2024-09-30       <NA>  left_only
3095       MA-   Total       87657 2024-10-07       <NA>  left_only
3096       MA-   Total      118730 2024-10-14       <NA>  left_only
3097       MA-   Total       98895 2024-10-21       <NA>  left_only
3098       MA-   Total      102150 2024-10-28       <NA>  left_only
3099       MA-   Total      201840 2024-11-04       <NA>  left_only
3100       MA-   Total      173838 2024-11-11       <NA>  left_only
3101       MA-   Total       90136 2024-11-18       <NA>  left_only
3102       MA-   Total       98585 2024-11-25       <NA>  left_only
3103       MA-   Total      129224 2024-12-02       <NA>  left_only
3104       MA-   Total      115904 2024-12-09       <NA>  left_only
3105       MA-   Total      132798 2024-12-16       <NA>  left_only
3106       MA-   Total      171255 2024-12-23       <NA>  left_only
3107       MA-   Total      102160 2024-12-30       <NA>  left_only
3108       MA-   Total      125138 2025-01-06       <NA>  left_only
3109       MA-   Total      101489 2025-01-13       <NA>  left_only
3110       MA-   Total       94647 2025-01-20       <NA>  left_only
3111       MA-   Total      111228 2025-01-27       <NA>  left_only
3112       MA-   Total      104668 2025-02-03       <NA>  left_only
3113       MA-   Total       69881 2025-02-10       <NA>  left_only
3114       MA-   Total       63820 2025-02-17       <NA>  left_only
3115       MA-   Total       66925 2025-02-24       <NA>  left_only
3116       MA-   Total       97235 2025-03-03       <NA>  left_only
3117       MA-   Total       98904 2025-03-10       <NA>  left_only
3118       MA-   Total       83865 2025-03-17       <NA>  left_only
3119       MA-   Total       78646 2025-03-24       <NA>  left_only

Rows with differences:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

--- Processing FOA Weekly ---
Rows missing from new:

     ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
7552       FOA     NAM        3548 2024-04-01       <NA>  left_only
7553       FOA     NAM        4275 2024-04-08       <NA>  left_only
7554       FOA     NAM        3708 2024-04-15       <NA>  left_only
7555       FOA     NAM        3243 2024-04-22       <NA>  left_only
7556       FOA     NAM        3792 2024-04-29       <NA>  left_only
7557       FOA     NAM        3098 2024-05-06       <NA>  left_only
7558       FOA     NAM        7104 2024-05-13       <NA>  left_only
7559       FOA     NAM        5963 2024-05-20       <NA>  left_only
7560       FOA     NAM        6212 2024-05-27       <NA>  left_only
7561       FOA     NAM        4409 2024-06-03       <NA>  left_only
7562       FOA     NAM        5246 2024-06-10       <NA>  left_only
7563       FOA     NAM        4518 2024-06-17       <NA>  left_only
7564       FOA     NAM        5020 2024-06-24       <NA>  left_only
7565       FOA     NAM        3827 2024-07-01       <NA>  left_only
7566       FOA     NAM        5680 2024-07-08       <NA>  left_only
7567       FOA     NAM        4432 2024-07-15       <NA>  left_only
7568       FOA     NAM        9627 2024-07-22       <NA>  left_only
7569       FOA     NAM        4489 2024-07-29       <NA>  left_only
7570       FOA     NAM        5378 2024-08-05       <NA>  left_only
7571       FOA     NAM        4413 2024-08-12       <NA>  left_only
7572       FOA     NAM        3684 2024-08-19       <NA>  left_only
7573       FOA     NAM        3790 2024-08-26       <NA>  left_only
7574       FOA     NAM        4610 2024-09-02       <NA>  left_only
7575       FOA     NAM        3481 2024-09-09       <NA>  left_only
7576       FOA     NAM        5577 2024-09-16       <NA>  left_only
7577       FOA     NAM        3854 2024-09-23       <NA>  left_only
7578       FOA     NAM        4022 2024-09-30       <NA>  left_only
7579       FOA     NAM        3180 2024-10-07       <NA>  left_only
7580       FOA     NAM        4428 2024-10-14       <NA>  left_only
7581       FOA     NAM        3643 2024-10-21       <NA>  left_only
7582       FOA     NAM        3315 2024-10-28       <NA>  left_only
7583       FOA     NAM        5094 2024-11-04       <NA>  left_only
7584       FOA     NAM        6085 2024-11-11       <NA>  left_only
7585       FOA     NAM        4604 2024-11-18       <NA>  left_only
7586       FOA     NAM        5963 2024-11-25       <NA>  left_only
7587       FOA     NAM        3650 2024-12-02       <NA>  left_only
7588       FOA     NAM        3682 2024-12-09       <NA>  left_only
7589       FOA     NAM        6991 2024-12-16       <NA>  left_only
7590       FOA     NAM        5495 2024-12-23       <NA>  left_only
7591       FOA     NAM        4294 2024-12-30       <NA>  left_only
7592       FOA     NAM        4475 2025-01-06       <NA>  left_only
7593       FOA     NAM        3652 2025-01-13       <NA>  left_only
7594       FOA     NAM        5045 2025-01-20       <NA>  left_only
7595       FOA     NAM        8172 2025-01-27       <NA>  left_only
7596       FOA     NAM        6152 2025-02-03       <NA>  left_only
7597       FOA     NAM        3376 2025-02-10       <NA>  left_only
7598       FOA     NAM        3500 2025-02-17       <NA>  left_only
7599       FOA     NAM        4297 2025-02-24       <NA>  left_only
7600       FOA     NAM        5449 2025-03-03       <NA>  left_only
7601       FOA     NAM        3440 2025-03-10       <NA>  left_only
7602       FOA     NAM        6971 2025-03-17       <NA>  left_only
7603       FOA     NAM        6992 2025-03-24       <NA>  left_only

Rows with differences:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

--- Processing AXE Weekly ---
Rows missing from new:

      ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
7713        AXE     NAM         519 2024-04-01       <NA>  left_only
7714        AXE     NAM         604 2024-04-08       <NA>  left_only
7715        AXE     NAM         828 2024-04-15       <NA>  left_only
7716        AXE     NAM        1229 2024-04-22       <NA>  left_only
7717        AXE     NAM         655 2024-04-29       <NA>  left_only
...         ...     ...         ...        ...        ...        ...
12488       AXE     NaN       48441 2025-02-17       <NA>  left_only
12489       AXE     NaN       30355 2025-02-24       <NA>  left_only
12490       AXE     NaN       50526 2025-03-03       <NA>  left_only
12491       AXE     NaN      139235 2025-03-10       <NA>  left_only
12492       AXE     NaN      248064 2025-03-17       <NA>  left_only

[103 rows x 6 columns]

Rows with differences:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

--- Processing AX2 Weekly ---
Rows missing from new:

      ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
7717        AX2     NAM        4049 2024-04-01       <NA>  left_only
7718        AX2     NAM        4857 2024-04-08       <NA>  left_only
7719        AX2     NAM        4507 2024-04-15       <NA>  left_only
7720        AX2     NAM        4428 2024-04-22       <NA>  left_only
7721        AX2     NAM        4423 2024-04-29       <NA>  left_only
...         ...     ...         ...        ...        ...        ...
12556       AX2     NaN       48441 2025-02-17       <NA>  left_only
12557       AX2     NaN       30355 2025-02-24       <NA>  left_only
12558       AX2     NaN       50526 2025-03-03       <NA>  left_only
12559       AX2     NaN      139235 2025-03-10       <NA>  left_only
12560       AX2     NaN      248064 2025-03-17       <NA>  left_only

[103 rows x 6 columns]

Rows with differences:

     ServiceID PlaceID  Reach_orig        w/c  Reach_new _merge  diff
3262       AX2     EGY      429879 2024-07-29     429878   both     1
5072       AX2     IND    18110495 2024-05-20   18110494   both     1

--- Processing ANW Weekly ---
Rows missing from new:

      ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
7723        ANW     NAM        5192 2024-04-01       <NA>  left_only
7724        ANW     NAM        6673 2024-04-08       <NA>  left_only
7725        ANW     NAM        6186 2024-04-15       <NA>  left_only
7726        ANW     NAM        4987 2024-04-22       <NA>  left_only
7727        ANW     NAM        5106 2024-04-29       <NA>  left_only
...         ...     ...         ...        ...        ...        ...
12630       ANW     NaN       48441 2025-02-17       <NA>  left_only
12631       ANW     NaN       30355 2025-02-24       <NA>  left_only
12632       ANW     NaN       50526 2025-03-03       <NA>  left_only
12633       ANW     NaN      139235 2025-03-10       <NA>  left_only
12634       ANW     NaN      248064 2025-03-17       <NA>  left_only

[103 rows x 6 columns]

Rows with differences:

      ServiceID PlaceID  Reach_orig        w/c  Reach_new _merge  diff
715         ANW     AUS      293555 2024-12-30     293554   both     1
870         ANW     BAN     1792265 2024-12-23    1792264   both     1
2045        ANW     CAN      487222 2024-07-29     487221   both     1
2072        ANW     CAN      636626 2025-02-03     636625   both     1
2073        ANW     CAN      621037 2025-02-10     621036   both     1
4306        ANW     GRE       31888 2024-07-15      31887   both     1
5102        ANW     IND    13637958 2024-11-04   13637957   both     1
5114        ANW     IND    19342822 2025-01-27   19342821   both     1
5116        ANW     IND    20236022 2025-02-10   20236021   both     1
5117        ANW     IND    15622104 2025-02-17   15622103   both     1
5118        ANW     IND    17849387 2025-02-24   17849386   both     1
5119        ANW     IND    17500248 2025-03-03   17500247   both     1
5120        ANW     IND    19390152 2025-03-10   19390151   both     1
5124        ANW     INO      796041 2024-04-08     796040   both     1
5125        ANW     INO     1128956 2024-04-15    1128955   both     1
5130        ANW     INO     1341818 2024-05-20    1341817   both     1
5153        ANW     INO      936438 2024-10-28     936437   both     1
5167        ANW     INO     1045958 2025-02-03    1045957   both     1
5168        ANW     INO     2022599 2025-02-10    2022598   both     1
5542        ANW     JAP      211874 2024-04-22     211873   both     1
5558        ANW     JAP      186740 2024-08-12     186739   both     1
5704        ANW     KAZ      130686 2024-06-03     130685   both     1
5918        ANW     KOS      738346 2024-07-15     738345   both     1
5935        ANW     KOS      438788 2024-11-11     438787   both     1
5950        ANW     KOS      934195 2025-02-24     934194   both     1
6666        ANW     MAL      203385 2024-12-02     203384   both     1
7235        ANW     MLT        3822 2024-11-11       3821   both     1
7975        ANW     NET      207090 2025-02-03     207089   both     1
8365        ANW      NZ       36110 2024-09-02      36109   both     1
8496        ANW     OST       50245 2025-03-10      50244   both     1
8515        ANW     PAK      826439 2024-07-22     826438   both     1
8840        ANW     PHI      423214 2024-04-29     423213   both     1
8896        ANW     POL       60235 2024-05-27      60234   both     1
8922        ANW     POL       62643 2024-11-25      62642   both     1
8943        ANW     POR       56613 2024-04-22      56612   both     1
9395        ANW     SAF      125341 2024-12-30     125340   both     1
10723       ANW     SWE       82037 2024-06-17      82036   both     1
11089       ANW     THA     1080815 2024-07-01    1080814   both     1
11716       ANW      UK      490839 2024-05-06     490838   both     1
11727       ANW      UK      750897 2024-07-22     750896   both     1
11751       ANW      UK      749512 2025-01-06     749511   both     1
11752       ANW      UK      719892 2025-01-13     719891   both     1
11758       ANW      UK      740897 2025-02-24     740896   both     1
11794       ANW     UKR      882684 2024-11-04     882683   both     1
11958       ANW     USA     1809085 2024-04-15    1809084   both     1
11982       ANW     USA     1451825 2024-09-30    1451824   both     1
11987       ANW     USA     2345571 2024-11-04    2345570   both     1
11995       ANW     USA     1912763 2024-12-30    1912762   both     1
12000       ANW     USA     2060301 2025-02-03    2060300   both     1
12003       ANW     USA     2058314 2025-02-24    2058313   both     1
12004       ANW     USA     1882907 2025-03-03    1882906   both     1
12251       ANW     VIE     1906002 2024-10-14    1906001   both     1

--- Processing ANY Weekly ---
Rows missing from new:

      ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
7750        ANY     NAM       14605 2024-04-01       <NA>  left_only
7751        ANY     NAM       17990 2024-04-08       <NA>  left_only
7752        ANY     NAM       17192 2024-04-15       <NA>  left_only
7753        ANY     NAM       11728 2024-04-22       <NA>  left_only
7754        ANY     NAM       11252 2024-04-29       <NA>  left_only
...         ...     ...         ...        ...        ...        ...
12715       ANY     NaN       48441 2025-02-17       <NA>  left_only
12716       ANY     NaN       30355 2025-02-24       <NA>  left_only
12717       ANY     NaN       50526 2025-03-03       <NA>  left_only
12718       ANY     NaN      139235 2025-03-10       <NA>  left_only
12719       ANY     NaN      248064 2025-03-17       <NA>  left_only

[103 rows x 6 columns]

Rows with differences:

      ServiceID PlaceID  Reach_orig        w/c  Reach_new _merge  diff
707         ANY     AUS      751045 2024-11-04     751044   both     1
1619        ANY     BRA     1368522 2024-05-20    1368521   both     1
2036        ANY     CAN      739510 2024-05-27     739509   both     1
2040        ANY     CAN      698034 2024-06-24     698033   both     1
2054        ANY     CAN      939441 2024-09-30     939440   both     1
3868        ANY     FIN       59331 2024-08-05      59330   both     1
4199        ANY     GER     1242763 2024-12-16    1242762   both     1
4904        ANY      HK      567607 2024-07-08     567606   both     1
5117        ANY     IND    17020550 2024-08-12   17020549   both     1
5120        ANY     IND    15618738 2024-09-02   15618737   both     1
5139        ANY     IND    19182268 2025-01-13   19182267   both     1
5143        ANY     IND    21410303 2025-02-10   21410302   both     1
5145        ANY     IND    18906088 2025-02-24   18906087   both     1
5146        ANY     IND    18589049 2025-03-03   18589048   both     1
5147        ANY     IND    20231940 2025-03-10   20231939   both     1
5148        ANY     IND    26350087 2025-03-17   26350086   both     1
5151        ANY     INO      892512 2024-04-08     892511   both     1
5154        ANY     INO     1334176 2024-04-29    1334175   both     1
5157        ANY     INO     1468737 2024-05-20    1468736   both     1
5195        ANY     INO     2089206 2025-02-10    2089205   both     1
5245        ANY     IRE      144263 2025-01-27     144262   both     1
5349        ANY     IRQ      400118 2025-01-27     400117   both     1
5405        ANY     ISR       85375 2025-02-24      85374   both     1
5459        ANY     ITA      231453 2025-03-10     231452   both     1
5570        ANY     JAP      771496 2024-04-29     771495   both     1
5758        ANY     KAZ      259720 2024-12-09     259719   both     1
5956        ANY     KOS      368352 2024-09-30     368351   both     1
5960        ANY     KOS      335634 2024-10-28     335633   both     1
5976        ANY     KOS     1114201 2025-02-17    1114200   both     1
6483        ANY     LTV       29662 2024-11-18      29661   both     1
7541        ANY     MON       10606 2025-03-24      10605   both     1
7553        ANY     MOR      474310 2024-06-17     474309   both     1
8301        ANY     NOR       82667 2024-11-04      82666   both     1
8531        ANY     PAK     1880514 2024-04-08    1880513   both     1
8875        ANY     PHI      315682 2024-05-27     315681   both     1
8901        ANY     PHI      324568 2024-11-25     324567   both     1
9396        ANY     SAF      243130 2024-06-03     243129   both     1
9900        ANY     SIN      223649 2024-12-23     223648   both     1
10849       ANY     SWI       99816 2025-03-24      99815   both     1
11117       ANY     THA     1592899 2024-05-20    1592898   both     1
11783       ANY      UK      490839 2024-05-06     490838   both     1
11794       ANY      UK      750897 2024-07-22     750896   both     1
11818       ANY      UK      749512 2025-01-06     749511   both     1
11819       ANY      UK      719892 2025-01-13     719891   both     1
11825       ANY      UK      740897 2025-02-24     740896   both     1
12027       ANY     USA     4315851 2024-04-08    4315850   both     1
12033       ANY     USA     4042032 2024-05-20    4042031   both     1
12043       ANY     USA     3609914 2024-07-29    3609913   both     1
12066       ANY     USA     4937392 2025-01-06    4937391   both     1
12067       ANY     USA     4546102 2025-01-13    4546101   both     1

--- Processing TOT Weekly ---
Rows missing from new:

     ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
7750       TOT     NAM       14605 2024-04-01       <NA>  left_only
7751       TOT     NAM       17990 2024-04-08       <NA>  left_only
7752       TOT     NAM       17192 2024-04-15       <NA>  left_only
7753       TOT     NAM       11728 2024-04-22       <NA>  left_only
7754       TOT     NAM       11252 2024-04-29       <NA>  left_only
7755       TOT     NAM       12493 2024-05-06       <NA>  left_only
7756       TOT     NAM       24665 2024-05-13       <NA>  left_only
7757       TOT     NAM       19773 2024-05-20       <NA>  left_only
7758       TOT     NAM       19507 2024-05-27       <NA>  left_only
7759       TOT     NAM       12640 2024-06-03       <NA>  left_only
7760       TOT     NAM       14767 2024-06-10       <NA>  left_only
7761       TOT     NAM       11903 2024-06-17       <NA>  left_only
7762       TOT     NAM       13639 2024-06-24       <NA>  left_only
7763       TOT     NAM       11989 2024-07-01       <NA>  left_only
7764       TOT     NAM       22113 2024-07-08       <NA>  left_only
7765       TOT     NAM       22040 2024-07-15       <NA>  left_only
7766       TOT     NAM       20495 2024-07-22       <NA>  left_only
7767       TOT     NAM       13891 2024-07-29       <NA>  left_only
7768       TOT     NAM       15366 2024-08-05       <NA>  left_only
7769       TOT     NAM       19155 2024-08-12       <NA>  left_only
7770       TOT     NAM       15304 2024-08-19       <NA>  left_only
7771       TOT     NAM       11534 2024-08-26       <NA>  left_only
7772       TOT     NAM       14052 2024-09-02       <NA>  left_only
7773       TOT     NAM       14984 2024-09-09       <NA>  left_only
7774       TOT     NAM       18048 2024-09-16       <NA>  left_only
7775       TOT     NAM       13207 2024-09-23       <NA>  left_only
7776       TOT     NAM       15718 2024-09-30       <NA>  left_only
7777       TOT     NAM       12472 2024-10-07       <NA>  left_only
7778       TOT     NAM       14326 2024-10-14       <NA>  left_only
7779       TOT     NAM       11834 2024-10-21       <NA>  left_only
7780       TOT     NAM       11953 2024-10-28       <NA>  left_only
7781       TOT     NAM       20612 2024-11-04       <NA>  left_only
7782       TOT     NAM       14475 2024-11-11       <NA>  left_only
7783       TOT     NAM       20146 2024-11-18       <NA>  left_only
7784       TOT     NAM       16367 2024-11-25       <NA>  left_only
7785       TOT     NAM       13097 2024-12-02       <NA>  left_only
7786       TOT     NAM       13492 2024-12-09       <NA>  left_only
7787       TOT     NAM       16622 2024-12-16       <NA>  left_only
7788       TOT     NAM       17130 2024-12-23       <NA>  left_only
7789       TOT     NAM       14305 2024-12-30       <NA>  left_only
7790       TOT     NAM       16722 2025-01-06       <NA>  left_only
7791       TOT     NAM       17960 2025-01-13       <NA>  left_only
7792       TOT     NAM       14693 2025-01-20       <NA>  left_only
7793       TOT     NAM       19419 2025-01-27       <NA>  left_only
7794       TOT     NAM       24413 2025-02-03       <NA>  left_only
7795       TOT     NAM       26319 2025-02-10       <NA>  left_only
7796       TOT     NAM       24140 2025-02-17       <NA>  left_only
7797       TOT     NAM       28166 2025-02-24       <NA>  left_only
7798       TOT     NAM       29423 2025-03-03       <NA>  left_only
7799       TOT     NAM       17235 2025-03-10       <NA>  left_only
7800       TOT     NAM       16583 2025-03-17       <NA>  left_only
7801       TOT     NAM       18229 2025-03-24       <NA>  left_only

Rows with differences:

     ServiceID PlaceID  Reach_orig        w/c  Reach_new _merge     diff
5163       TOT     INO     4212752 2024-07-01     734479   both  3478273
5179       TOT     INO     3383714 2024-10-21    1240250   both  2143464
5155       TOT     INO     3424182 2024-05-06    1471208   both  1952974
5154       TOT     INO     3104940 2024-04-29    1390596   both  1714344
5178       TOT     INO     2314827 2024-10-14     775412   both  1539415
...        ...     ...         ...        ...        ...    ...      ...
7927       TOT     NEP      374314 2024-08-26     409188   both   -34874
7928       TOT     NEP      334150 2024-09-02     376447   both   -42297
5160       TOT     INO      482141 2024-06-10     577068   both   -94927
5159       TOT     INO      585143 2024-06-03     684623   both   -99480
5161       TOT     INO      542210 2024-06-17     680943   both  -138733

[1305 rows x 7 columns]

--- Processing ALL Weekly ---
Rows missing from new:

     ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
7783       ALL     NAM       30629 2024-04-01       <NA>  left_only
7784       ALL     NAM       34168 2024-04-08       <NA>  left_only
7785       ALL     NAM       36136 2024-04-15       <NA>  left_only
7786       ALL     NAM       30285 2024-04-22       <NA>  left_only
7787       ALL     NAM       30779 2024-04-29       <NA>  left_only
7788       ALL     NAM       29790 2024-05-06       <NA>  left_only
7789       ALL     NAM       40292 2024-05-13       <NA>  left_only
7790       ALL     NAM       37524 2024-05-20       <NA>  left_only
7791       ALL     NAM       44329 2024-05-27       <NA>  left_only
7792       ALL     NAM       41505 2024-06-03       <NA>  left_only
7793       ALL     NAM       38338 2024-06-10       <NA>  left_only
7794       ALL     NAM       33582 2024-06-17       <NA>  left_only
7795       ALL     NAM       35231 2024-06-24       <NA>  left_only
7796       ALL     NAM       32623 2024-07-01       <NA>  left_only
7797       ALL     NAM       41161 2024-07-08       <NA>  left_only
7798       ALL     NAM       39033 2024-07-15       <NA>  left_only
7799       ALL     NAM       35740 2024-07-22       <NA>  left_only
7800       ALL     NAM       30392 2024-07-29       <NA>  left_only
7801       ALL     NAM       30294 2024-08-05       <NA>  left_only
7802       ALL     NAM       33530 2024-08-12       <NA>  left_only
7803       ALL     NAM       28371 2024-08-19       <NA>  left_only
7804       ALL     NAM       25326 2024-08-26       <NA>  left_only
7805       ALL     NAM       30162 2024-09-02       <NA>  left_only
7806       ALL     NAM       33218 2024-09-09       <NA>  left_only
7807       ALL     NAM       34317 2024-09-16       <NA>  left_only
7808       ALL     NAM       31364 2024-09-23       <NA>  left_only
7809       ALL     NAM       33102 2024-09-30       <NA>  left_only
7810       ALL     NAM       31880 2024-10-07       <NA>  left_only
7811       ALL     NAM       32363 2024-10-14       <NA>  left_only
7812       ALL     NAM       28422 2024-10-21       <NA>  left_only
7813       ALL     NAM       28187 2024-10-28       <NA>  left_only
7814       ALL     NAM       34296 2024-11-04       <NA>  left_only
7815       ALL     NAM       30975 2024-11-11       <NA>  left_only
7816       ALL     NAM       40522 2024-11-18       <NA>  left_only
7817       ALL     NAM       37702 2024-11-25       <NA>  left_only
7818       ALL     NAM       30799 2024-12-02       <NA>  left_only
7819       ALL     NAM       29806 2024-12-09       <NA>  left_only
7820       ALL     NAM       33021 2024-12-16       <NA>  left_only
7821       ALL     NAM       30674 2024-12-23       <NA>  left_only
7822       ALL     NAM       31531 2024-12-30       <NA>  left_only
7823       ALL     NAM       38727 2025-01-06       <NA>  left_only
7824       ALL     NAM       39453 2025-01-13       <NA>  left_only
7825       ALL     NAM       33259 2025-01-20       <NA>  left_only
7826       ALL     NAM       35824 2025-01-27       <NA>  left_only
7827       ALL     NAM       38580 2025-02-03       <NA>  left_only
7828       ALL     NAM       39245 2025-02-10       <NA>  left_only
7829       ALL     NAM       37814 2025-02-17       <NA>  left_only
7830       ALL     NAM       43102 2025-02-24       <NA>  left_only
7831       ALL     NAM       44498 2025-03-03       <NA>  left_only
7832       ALL     NAM       33524 2025-03-10       <NA>  left_only
7833       ALL     NAM       32991 2025-03-17       <NA>  left_only
7834       ALL     NAM       33940 2025-03-24       <NA>  left_only

Rows with differences:

     ServiceID PlaceID  Reach_orig        w/c  Reach_new _merge     diff
5194       ALL     INO     4740326 2024-07-01    1270869   both  3469457
5210       ALL     INO     4149460 2024-10-21    2013851   both  2135609
5186       ALL     INO     4026366 2024-05-06    2079021   both  1947345
5185       ALL     INO     3784267 2024-04-29    2075488   both  1708779
5209       ALL     INO     3383347 2024-10-14    1851764   both  1531583
...        ...     ...         ...        ...        ...    ...      ...
7960       ALL     NEP      414045 2024-08-26     448855   both   -34810
7961       ALL     NEP      398624 2024-09-02     440794   both   -42170
5191       ALL     INO     1279813 2024-06-10    1374383   both   -94570
5190       ALL     INO     2006742 2024-06-03    2105554   both   -98812
5192       ALL     INO     1099810 2024-06-17    1238178   both  -138368

[1299 rows x 7 columns]

--- Processing ENG Weekly ---
Rows missing from new:

             w/c ServiceID PlaceID  Reach_orig  Reach_new     _merge
149   2024-04-01       ENG     NAM       11191       <NA>  left_only
390   2024-04-08       ENG     NAM       13970       <NA>  left_only
635   2024-04-15       ENG     NAM       13461       <NA>  left_only
878   2024-04-22       ENG     NAM        7873       <NA>  left_only
1120  2024-04-29       ENG     NAM        7424       <NA>  left_only
1363  2024-05-06       ENG     NAM        9288       <NA>  left_only
1606  2024-05-13       ENG     NAM       17939       <NA>  left_only
1849  2024-05-20       ENG     NAM       14074       <NA>  left_only
2092  2024-05-27       ENG     NAM       13609       <NA>  left_only
2334  2024-06-03       ENG     NAM        8574       <NA>  left_only
2577  2024-06-10       ENG     NAM        9831       <NA>  left_only
2821  2024-06-17       ENG     NAM        7620       <NA>  left_only
3064  2024-06-24       ENG     NAM        8905       <NA>  left_only
3306  2024-07-01       ENG     NAM        8285       <NA>  left_only
3550  2024-07-08       ENG     NAM       16552       <NA>  left_only
3793  2024-07-15       ENG     NAM       18004       <NA>  left_only
4035  2024-07-22       ENG     NAM       11497       <NA>  left_only
4278  2024-07-29       ENG     NAM        9599       <NA>  left_only
4521  2024-08-05       ENG     NAM       10254       <NA>  left_only
4764  2024-08-12       ENG     NAM       14962       <NA>  left_only
5006  2024-08-19       ENG     NAM       11825       <NA>  left_only
5249  2024-08-26       ENG     NAM        7920       <NA>  left_only
5492  2024-09-02       ENG     NAM        9758       <NA>  left_only
5735  2024-09-09       ENG     NAM       11656       <NA>  left_only
5977  2024-09-16       ENG     NAM       12767       <NA>  left_only
6220  2024-09-23       ENG     NAM        9431       <NA>  left_only
6463  2024-09-30       ENG     NAM       11814       <NA>  left_only
6706  2024-10-07       ENG     NAM        9367       <NA>  left_only
6948  2024-10-14       ENG     NAM       10090       <NA>  left_only
7190  2024-10-21       ENG     NAM        8295       <NA>  left_only
7433  2024-10-28       ENG     NAM        8612       <NA>  left_only
7677  2024-11-04       ENG     NAM       15622       <NA>  left_only
7922  2024-11-11       ENG     NAM        8666       <NA>  left_only
8165  2024-11-18       ENG     NAM       15655       <NA>  left_only
8407  2024-11-25       ENG     NAM       10651       <NA>  left_only
8649  2024-12-02       ENG     NAM        9374       <NA>  left_only
8893  2024-12-09       ENG     NAM        9871       <NA>  left_only
9134  2024-12-16       ENG     NAM       10036       <NA>  left_only
9377  2024-12-23       ENG     NAM       12257       <NA>  left_only
9619  2024-12-30       ENG     NAM       10320       <NA>  left_only
9860  2025-01-06       ENG     NAM       12327       <NA>  left_only
10102 2025-01-13       ENG     NAM       14394       <NA>  left_only
10345 2025-01-20       ENG     NAM        9837       <NA>  left_only
10587 2025-01-27       ENG     NAM       11640       <NA>  left_only
10831 2025-02-03       ENG     NAM       18502       <NA>  left_only
11075 2025-02-10       ENG     NAM       23006       <NA>  left_only
11315 2025-02-17       ENG     NAM       20777       <NA>  left_only
11560 2025-02-24       ENG     NAM       23894       <NA>  left_only
11804 2025-03-03       ENG     NAM       24158       <NA>  left_only
12047 2025-03-10       ENG     NAM       13919       <NA>  left_only
12289 2025-03-17       ENG     NAM       10036       <NA>  left_only
12529 2025-03-24       ENG     NAM       11540       <NA>  left_only

Rows with differences:

             w/c ServiceID PlaceID  Reach_orig  Reach_new _merge  diff
356   2024-04-08       ENG     KRG        4352       4351   both     1
1572  2024-05-13       ENG     KRG        3393       3392   both     1
4244  2024-07-29       ENG     KRG        2812       2811   both     1
8615  2024-12-02       ENG     KRG        7288       7287   both     1
9100  2024-12-16       ENG     KRG        4968       4967   both     1
9826  2025-01-06       ENG     KRG        6658       6657   both     1
10068 2025-01-13       ENG     KRG        5702       5701   both     1
12255 2025-03-17       ENG     KRG        3464       3463   both     1
12495 2025-03-24       ENG     KRG        5620       5619   both     1

--- Processing ENW Weekly ---
Rows missing from new:

             w/c ServiceID PlaceID  Reach_orig  Reach_new     _merge
147   2024-04-01       ENW     NAM        4776       <NA>  left_only
385   2024-04-08       ENW     NAM        6226       <NA>  left_only
627   2024-04-15       ENW     NAM        5513       <NA>  left_only
863   2024-04-22       ENW     NAM        3844       <NA>  left_only
1099  2024-04-29       ENW     NAM        4525       <NA>  left_only
1334  2024-05-06       ENW     NAM        3642       <NA>  left_only
1573  2024-05-13       ENW     NAM        8097       <NA>  left_only
1811  2024-05-20       ENW     NAM        6988       <NA>  left_only
2051  2024-05-27       ENW     NAM        7036       <NA>  left_only
2290  2024-06-03       ENW     NAM        6489       <NA>  left_only
2531  2024-06-10       ENW     NAM        6210       <NA>  left_only
2773  2024-06-17       ENW     NAM        5317       <NA>  left_only
3012  2024-06-24       ENW     NAM        5837       <NA>  left_only
3250  2024-07-01       ENW     NAM        4697       <NA>  left_only
3489  2024-07-08       ENW     NAM        6500       <NA>  left_only
3727  2024-07-15       ENW     NAM        7303       <NA>  left_only
3966  2024-07-22       ENW     NAM       11256       <NA>  left_only
4206  2024-07-29       ENW     NAM        5472       <NA>  left_only
4445  2024-08-05       ENW     NAM        6523       <NA>  left_only
4683  2024-08-12       ENW     NAM        5790       <NA>  left_only
4922  2024-08-19       ENW     NAM        4852       <NA>  left_only
5161  2024-08-26       ENW     NAM        4740       <NA>  left_only
5397  2024-09-02       ENW     NAM        5490       <NA>  left_only
5638  2024-09-09       ENW     NAM        4251       <NA>  left_only
5875  2024-09-16       ENW     NAM        6334       <NA>  left_only
6113  2024-09-23       ENW     NAM        4461       <NA>  left_only
6349  2024-09-30       ENW     NAM        4887       <NA>  left_only
6588  2024-10-07       ENW     NAM        4079       <NA>  left_only
6826  2024-10-14       ENW     NAM        5197       <NA>  left_only
7064  2024-10-21       ENW     NAM        4301       <NA>  left_only
7302  2024-10-28       ENW     NAM        3847       <NA>  left_only
7543  2024-11-04       ENW     NAM        5866       <NA>  left_only
7783  2024-11-11       ENW     NAM        6803       <NA>  left_only
8021  2024-11-18       ENW     NAM        5380       <NA>  left_only
8259  2024-11-25       ENW     NAM        6656       <NA>  left_only
8497  2024-12-02       ENW     NAM        4194       <NA>  left_only
8735  2024-12-09       ENW     NAM        4398       <NA>  left_only
8971  2024-12-16       ENW     NAM        8210       <NA>  left_only
9208  2024-12-23       ENW     NAM        9196       <NA>  left_only
9447  2024-12-30       ENW     NAM        6735       <NA>  left_only
9685  2025-01-06       ENW     NAM        5758       <NA>  left_only
9923  2025-01-13       ENW     NAM        5042       <NA>  left_only
10161 2025-01-20       ENW     NAM        6164       <NA>  left_only
10401 2025-01-27       ENW     NAM        9263       <NA>  left_only
10643 2025-02-03       ENW     NAM        7803       <NA>  left_only
10884 2025-02-10       ENW     NAM        4855       <NA>  left_only
11123 2025-02-17       ENW     NAM        4971       <NA>  left_only
11363 2025-02-24       ENW     NAM        5325       <NA>  left_only
11602 2025-03-03       ENW     NAM        6598       <NA>  left_only
11843 2025-03-10       ENW     NAM        4938       <NA>  left_only
12083 2025-03-17       ENW     NAM        7998       <NA>  left_only
12322 2025-03-24       ENW     NAM        7601       <NA>  left_only

Rows with differences:

Empty DataFrame
Columns: [w/c, ServiceID, PlaceID, Reach_orig, Reach_new, _merge]
Index: []

--- Processing EN2 Weekly ---
Rows missing from new:

             w/c ServiceID PlaceID  Reach_orig  Reach_new     _merge
149   2024-04-01       EN2     NAM       26866       <NA>  left_only
392   2024-04-08       EN2     NAM       29718       <NA>  left_only
637   2024-04-15       EN2     NAM       32024       <NA>  left_only
881   2024-04-22       EN2     NAM       26221       <NA>  left_only
1123  2024-04-29       EN2     NAM       26765       <NA>  left_only
1366  2024-05-06       EN2     NAM       26307       <NA>  left_only
1609  2024-05-13       EN2     NAM       32164       <NA>  left_only
1852  2024-05-20       EN2     NAM       31430       <NA>  left_only
2096  2024-05-27       EN2     NAM       38155       <NA>  left_only
2341  2024-06-03       EN2     NAM       37314       <NA>  left_only
2586  2024-06-10       EN2     NAM       33200       <NA>  left_only
2831  2024-06-17       EN2     NAM       29134       <NA>  left_only
3077  2024-06-24       EN2     NAM       30298       <NA>  left_only
3320  2024-07-01       EN2     NAM       28715       <NA>  left_only
3565  2024-07-08       EN2     NAM       35139       <NA>  left_only
3810  2024-07-15       EN2     NAM       33461       <NA>  left_only
4053  2024-07-22       EN2     NAM       26442       <NA>  left_only
4296  2024-07-29       EN2     NAM       25821       <NA>  left_only
4540  2024-08-05       EN2     NAM       24873       <NA>  left_only
4786  2024-08-12       EN2     NAM       27996       <NA>  left_only
5029  2024-08-19       EN2     NAM       24487       <NA>  left_only
5273  2024-08-26       EN2     NAM       21459       <NA>  left_only
5517  2024-09-02       EN2     NAM       25578       <NA>  left_only
5760  2024-09-09       EN2     NAM       29545       <NA>  left_only
6004  2024-09-16       EN2     NAM       28656       <NA>  left_only
6249  2024-09-23       EN2     NAM       27322       <NA>  left_only
6492  2024-09-30       EN2     NAM       28848       <NA>  left_only
6737  2024-10-07       EN2     NAM       28515       <NA>  left_only
6980  2024-10-14       EN2     NAM       27846       <NA>  left_only
7224  2024-10-21       EN2     NAM       24639       <NA>  left_only
7469  2024-10-28       EN2     NAM       24584       <NA>  left_only
7714  2024-11-04       EN2     NAM       28038       <NA>  left_only
7959  2024-11-11       EN2     NAM       24936       <NA>  left_only
8202  2024-11-18       EN2     NAM       35603       <NA>  left_only
8445  2024-11-25       EN2     NAM       31746       <NA>  left_only
8689  2024-12-02       EN2     NAM       26806       <NA>  left_only
8934  2024-12-09       EN2     NAM       25884       <NA>  left_only
9177  2024-12-16       EN2     NAM       26170       <NA>  left_only
9420  2024-12-23       EN2     NAM       25415       <NA>  left_only
9664  2024-12-30       EN2     NAM       27253       <NA>  left_only
9907  2025-01-06       EN2     NAM       34031       <NA>  left_only
10152 2025-01-13       EN2     NAM       35504       <NA>  left_only
10396 2025-01-20       EN2     NAM       28146       <NA>  left_only
10641 2025-01-27       EN2     NAM       27739       <NA>  left_only
10886 2025-02-03       EN2     NAM       31405       <NA>  left_only
11130 2025-02-10       EN2     NAM       34800       <NA>  left_only
11371 2025-02-17       EN2     NAM       33230       <NA>  left_only
11616 2025-02-24       EN2     NAM       37531       <NA>  left_only
11860 2025-03-03       EN2     NAM       37938       <NA>  left_only
12104 2025-03-10       EN2     NAM       29770       <NA>  left_only
12349 2025-03-17       EN2     NAM       26178       <NA>  left_only
12592 2025-03-24       EN2     NAM       26922       <NA>  left_only

Rows with differences:

Empty DataFrame
Columns: [w/c, ServiceID, PlaceID, Reach_orig, Reach_new, _merge]
Index: []