In [1]:
from IPython.display import display

import pandas as pd

In [2]:
import sys
from pathlib import Path

try:
    # Works in Python scripts
    helper_path = Path(__file__).resolve().parent.parent / "helper"
except NameError:
    # Works in Jupyter notebooks
    helper_path = Path().resolve().parent / "helper"

sys.path.insert(0, str(helper_path))

# Now import your modules
from config import gam_info
import functions

In [3]:
# Load country mapping
country_map = pd.read_excel(f"../../{gam_info['lookup_file']}", sheet_name='CountryID')[['PlaceID', 'YT-_FBE_codes']]
# Load country mapping
week_map = pd.read_excel(f"../../{gam_info['lookup_file']}", sheet_name='GAM Period')[['w/c', 'WeekNumber_finYear']]

In [4]:
# Utility functions
def load_excel(path):
    return pd.read_excel(path, engine='openpyxl')

def load_csv(path):
    return pd.read_csv(path)

def standardize_country_codes(df, column='Country Code'):
    return df.replace({column: {'WLF': 'WFI', '* Total': 'Total'}})

def run_comparison(original_df, new_df, column_mapping, key_columns, method='integer', threshold=0.0001):
    if method == 'integer':
        return compare_dataframes_integer(original_df, new_df, column_mapping, key_columns)
    elif method == 'percentage':
        return compare_dataframes_percentage(original_df, new_df, column_mapping, key_columns, threshold)
    else:
        raise ValueError("Unknown comparison method")

In [5]:
def compare_dataframes_integer(original_df, new_df, column_mapping, key_columns_new):
    """
    Compare two DataFrames and return rows that are missing or different.

    Parameters:
    - original_df: DataFrame from the original source
    - new_df: DataFrame from the new source
    - column_mapping: dict mapping original_df column names to new_df column names
    - key_columns_new: list of key columns using new_df naming

    Returns:
    - missing_from_new: rows in original_df not found in new_df
    - differing_rows: rows where key matches but mapped columns differ
    """

    # Rename original_df to match new_df column names
    original_df_renamed = original_df.rename(columns=column_mapping)

    # Ensure all required columns exist
    all_columns = list(column_mapping.values())
    original_subset = original_df_renamed[all_columns].copy()
    new_subset = new_df[all_columns].copy()

    # Round numeric columns to nearest integer
    for col in all_columns:
        if pd.api.types.is_numeric_dtype(original_subset[col]) and pd.api.types.is_numeric_dtype(new_subset[col]):
            original_subset[col] = original_subset[col].round(0).astype('Int64')
            new_subset[col] = new_subset[col].round(0).astype('Int64')
        
    # Merge to find differences
    merged = pd.merge(
        original_subset,
        new_subset,
        on=key_columns_new,
        how='outer',
        suffixes=('_orig', '_new'),
        indicator=True
    )

    # Missing rows: present in original but not in new
    missing_from_new = merged[merged['_merge'] == 'left_only']

    # Differing rows: same keys but different values
    comparison_cols = [col for col in all_columns if col not in key_columns_new]
        
    differing_rows = merged[
        (merged['_merge'] == 'both') &
        merged[[f"{col}_orig" for col in comparison_cols]].ne(
            merged[[f"{col}_new" for col in comparison_cols]].values
        ).any(axis=1)
    ]

    return missing_from_new, differing_rows

In [6]:
def compare_dataframes_percentage(original_df, new_df, column_mapping, key_columns_new, threshold=0.0001):
    """
    Compare two DataFrames and return rows that are missing or have percentage differences.

    Parameters:
    - original_df: DataFrame from the original source
    - new_df: DataFrame from the new source
    - column_mapping: dict mapping original_df column names to new_df column names
    - key_columns_new: list of key columns using new_df naming
    - threshold: minimum absolute difference to consider as significant

    Returns:
    - missing_from_new: rows in original_df not found in new_df
    - differing_rows: rows where key matches but mapped columns differ beyond threshold
    """

    # Rename original_df to match new_df column names
    original_df_renamed = original_df.rename(columns=column_mapping)

    # Ensure all required columns exist
    all_columns = list(column_mapping.values())
    original_subset = original_df_renamed[all_columns].copy()
    new_subset = new_df[all_columns].copy()

    # Merge to find differences
    merged = pd.merge(
        original_subset,
        new_subset,
        on=key_columns_new,
        how='outer',
        suffixes=('_orig', '_new'),
        indicator=True
    )

    # Missing rows: present in original but not in new
    missing_from_new = merged[merged['_merge'] == 'left_only']

    # Compute differences
    comparison_cols = [col for col in all_columns if col not in key_columns_new]
    for col in comparison_cols:
        merged[f"{col}_diff"] = merged[f"{col}_new"] - merged[f"{col}_orig"]

    # Filter rows where any difference exceeds threshold
    diff_mask = merged['_merge'] == 'both'
    for col in comparison_cols:
        diff_mask &= merged[f"{col}_diff"].abs() > threshold

    differing_rows = merged[diff_mask]

    return missing_from_new, differing_rows

In [9]:
datasets = [
    {
        "name": "Unique Viewers",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/data/Final Raw/YouTube Unique Viewers.xlsx",
        "new_path": f"../data/processed/YT-/_{gam_info['file_timeinfo']}_uniqueViewer_withAds.csv",
        "column_mapping": {
            "Channel": "Channel ID",
            "YT Service Code": "ServiceID",
            "w/c": "w/c",
            "Unique viewers": "Unique viewers"
        },
        "key_columns": ["Channel ID", "ServiceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": False
        }
    },
    {
        "name": "Country Percentage",
        "original_path": "../data/interim/yt_country_processed_interim.csv",
        "new_path": f"../data/processed/YT-/{gam_info['file_timeinfo']}_country_new.csv",
        "column_mapping": {
            "Channel": "Channel ID",
            "Country": "PlaceID",
            "Date": "w/c",
            "Country %": "country_%"
        },
        "key_columns": ["Channel ID", "w/c", "PlaceID"],
        "method": "percentage",
        "threshold": 0.0001,
        "preprocess": {
            "standardize_country": False,
            "week_mapping": False
        },
        "notes": '''
        there is one cahnnel missing that has NaN as country - checking countries there is for that 
        channel & date both UNK and NaN.
        '''
    },
    {
        "name": "GNL Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - GNL by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_GNLbyCountry.xlsx",
        "column_mapping": {
            "Service Code": "ServiceID",
            "Country Code": "PlaceID",
            "YouTube Engaged Reach": "Reach",
            "w/c": "w/c"
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "WSL Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - WSL by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_WSLbyCountry.xlsx",
        "column_mapping": {
            "Service Code": "ServiceID",
            "Country Code": "PlaceID",
            "YouTube Engaged Reach": "Reach",
            "w/c": "w/c"
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        },
        "notes": """
        missing are SER & SIN because I have placeID for them and with minnie they are missing
        """
    },
    {
        "name": "WOR Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - WOR by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_WORbyCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        },
        "notes": """
        missing are additional rows in minnie's dataset that have missing values for placeid and reach
        """
        
    },
    {
        "name": "WSE Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - WSE by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_WSEbyCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
        {
        "name": "MA- Weekly",
        "original_path": "../test/alteryx_datasets/mk_weekly_MA_YT.csv",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_MA-byCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        },
        "notes": """
            total should have been filtered out
        """
    },
    {
        "name": "FOA Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - FOA by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_FOAbyCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "AXE Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - AXE by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_AXEbyCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "AX2 Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - AX2 by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_AX2byCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "ANW Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - ANW by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_ANWbyCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "ANY Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - ANY by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_ANYbyCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "TOT Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - TOT by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_TOTbyCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "ALL Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - ALL by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_ALLbyCountry.xlsx",
        "column_mapping": {
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
            'w/c': 'w/c'
        },
        "key_columns": ["ServiceID", "PlaceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "ENG Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - ENG by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_ENGbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c',
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
        },
        "key_columns": ["w/c", "ServiceID", "PlaceID"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "ENW Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - ENW by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_ENWbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c',
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
        },
        "key_columns": ["w/c", "ServiceID", "PlaceID"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
    {
        "name": "EN2 Weekly",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/WEEKLY YouTube - EN2 by country.xlsx",
        "new_path": "../data/singlePlatform/YT-/weekly/GAM2025_WEEKLY_YT-_EN2byCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c',
            'Service Code': 'ServiceID', 
            'Country Code': 'PlaceID',
            'YouTube Engaged Reach': 'Reach',
        },
        "key_columns": ["w/c", "ServiceID", "PlaceID"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": True
        }
    },
]

In [10]:

# Execute comparisons
for ds in datasets:
    # TODO - test currently doesn't catch additional things in my dataset that are not in minnie's 
    # e.g. I included Studios for UK / Youtube and Minnie did not - that did not show up here
    print(f"\n--- Processing {ds['name']} ---")

    orig = load_excel(ds["original_path"]) if ds["original_path"].endswith(".xlsx") else load_csv(ds["original_path"])
    new  = load_excel(ds["new_path"]) if ds["new_path"].endswith(".xlsx") else load_csv(ds["new_path"])

    # Special preprocessing for Country Percentage dataset
    if ds["name"] == "Country Percentage":
        
        # Rename 'Country' to 'YouTube Codes' in original data and merge with mapping
        orig = orig.rename(columns={'Country': 'YT-_FBE_codes'})
        orig = orig.merge(country_map, on='YT-_FBE_codes', how='left').drop(columns=['YT-_FBE_codes'])

    if "Country Code" in orig.columns:
        orig = standardize_country_codes(orig)
    if "Country Code" in new.columns:
        new = standardize_country_codes(new)

    # Rename columns according to mapping
    orig = orig.rename(columns={k: v for k, v in ds["column_mapping"].items() if k in orig.columns})
    new  = new.rename(columns={k: v for k, v in ds["column_mapping"].items() if k in new.columns})

    # Special preprocessing for Country Percentage dataset
    if ds['preprocess']['week_mapping']:
        # add w/c using Week Number
        orig = orig.merge(week_map, left_on='Week Number', right_on='WeekNumber_finYear',
                                              how='left').drop(columns=['Week Number', 'WeekNumber_finYear'])
        
    # Ensure 'w/c' columns are datetime in both DataFrames
    if 'w/c' in orig.columns:
        orig['w/c'] = pd.to_datetime(orig['w/c'], errors='coerce')
    if 'w/c' in new.columns:
        new['w/c'] = pd.to_datetime(new['w/c'], errors='coerce')

    missing, different = run_comparison(
        orig, new,
        ds["column_mapping"],
        ds["key_columns"],
        method=ds.get("method", "integer"),
        threshold=ds.get("threshold", 0.0001)
    )

    print("Rows missing from new:")
    display(missing)
    print("Rows with differences:")
    if len(different) > 0:
        different['diff'] = different['Reach_orig'] - different['Reach_new']
        display(different.sort_values('diff', ascending=False))
    else:
        display(different)

--- Processing Unique Viewers ---
Rows missing from new:

Empty DataFrame
Columns: [Channel ID, ServiceID, w/c, Unique viewers_orig, Unique viewers_new, _merge]
Index: []

Rows with differences:

Empty DataFrame
Columns: [Channel ID, ServiceID, w/c, Unique viewers_orig, Unique viewers_new, _merge]
Index: []

--- Processing Country Percentage ---
Rows missing from new:

,Channel ID,PlaceID,w/c,country_%_orig,country_%_new,_merge
741823,UCjOl2AUblVmg2rA_cRgZkFg,NaN,2024-07-08,2.657304e-07,NaN,left_only

Rows with differences:

Empty DataFrame
Columns: [Channel ID, PlaceID, w/c, country_%_orig, country_%_new, _merge, country_%_diff]
Index: []

--- Processing GNL Weekly ---
Rows missing from new:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

Rows with differences:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

--- Processing WSL Weekly ---
Rows missing from new:

       ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
194654       SER     NaN           0 2024-04-01       <NA>  left_only
194655       SER     NaN           0 2024-04-01       <NA>  left_only
194656       SER     NaN           8 2024-04-01       <NA>  left_only
194657       SER     NaN           0 2024-04-01       <NA>  left_only
194658       SER     NaN         546 2024-04-01       <NA>  left_only
...          ...     ...         ...        ...        ...        ...
199229       SIN     NaN           0 2025-03-17       <NA>  left_only
199230       SIN     NaN          30 2025-03-17       <NA>  left_only
199231       SIN     NaN          77 2025-03-17       <NA>  left_only
199232       SIN     NaN         951 2025-03-17       <NA>  left_only
199233       SIN     NaN        1082 2025-03-17       <NA>  left_only

[4279 rows x 6 columns]

Rows with differences:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

--- Processing WOR Weekly ---
Rows missing from new:

      ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
12550       WOR     NaN        <NA> 2024-04-01       <NA>  left_only
12551       WOR     NaN        <NA> 2024-04-08       <NA>  left_only
12552       WOR     NaN        <NA> 2024-04-15       <NA>  left_only
12553       WOR     NaN        <NA> 2024-04-22       <NA>  left_only
12554       WOR     NaN        <NA> 2024-04-29       <NA>  left_only
12555       WOR     NaN        <NA> 2024-05-06       <NA>  left_only
12556       WOR     NaN        <NA> 2024-05-13       <NA>  left_only
12557       WOR     NaN        <NA> 2024-05-20       <NA>  left_only
12558       WOR     NaN        <NA> 2024-05-27       <NA>  left_only
12559       WOR     NaN        <NA> 2024-06-03       <NA>  left_only
12560       WOR     NaN        <NA> 2024-06-10       <NA>  left_only
12561       WOR     NaN        <NA> 2024-06-17       <NA>  left_only
12562       WOR     NaN        <NA> 2024-06-24       <NA>  left_only
12563       WOR     NaN        <NA> 2024-07-01       <NA>  left_only
12564       WOR     NaN        <NA> 2024-07-08       <NA>  left_only
12565       WOR     NaN        <NA> 2024-07-15       <NA>  left_only
12566       WOR     NaN        <NA> 2024-07-22       <NA>  left_only
12567       WOR     NaN        <NA> 2024-07-29       <NA>  left_only
12568       WOR     NaN        <NA> 2024-08-05       <NA>  left_only
12569       WOR     NaN        <NA> 2024-08-12       <NA>  left_only
12570       WOR     NaN        <NA> 2024-08-19       <NA>  left_only
12571       WOR     NaN        <NA> 2024-08-26       <NA>  left_only
12572       WOR     NaN        <NA> 2024-09-02       <NA>  left_only
12573       WOR     NaN        <NA> 2024-09-09       <NA>  left_only
12574       WOR     NaN        <NA> 2024-09-16       <NA>  left_only
12575       WOR     NaN        <NA> 2024-09-23       <NA>  left_only
12576       WOR     NaN        <NA> 2024-09-30       <NA>  left_only
12577       WOR     NaN        <NA> 2024-10-07       <NA>  left_only
12578       WOR     NaN        <NA> 2024-10-14       <NA>  left_only
12579       WOR     NaN        <NA> 2024-10-21       <NA>  left_only
12580       WOR     NaN        <NA> 2024-10-28       <NA>  left_only
12581       WOR     NaN        <NA> 2024-11-04       <NA>  left_only
12582       WOR     NaN        <NA> 2024-11-11       <NA>  left_only
12583       WOR     NaN        <NA> 2024-11-18       <NA>  left_only
12584       WOR     NaN        <NA> 2024-11-25       <NA>  left_only
12585       WOR     NaN        <NA> 2024-12-02       <NA>  left_only
12586       WOR     NaN        <NA> 2024-12-09       <NA>  left_only
12587       WOR     NaN        <NA> 2024-12-16       <NA>  left_only
12588       WOR     NaN        <NA> 2024-12-23       <NA>  left_only
12589       WOR     NaN        <NA> 2024-12-30       <NA>  left_only
12590       WOR     NaN        <NA> 2025-01-06       <NA>  left_only
12591       WOR     NaN        <NA> 2025-01-13       <NA>  left_only
12592       WOR     NaN        <NA> 2025-01-20       <NA>  left_only
12593       WOR     NaN        <NA> 2025-01-27       <NA>  left_only
12594       WOR     NaN        <NA> 2025-02-03       <NA>  left_only
12595       WOR     NaN        <NA> 2025-02-10       <NA>  left_only
12596       WOR     NaN        <NA> 2025-02-17       <NA>  left_only
12597       WOR     NaN        <NA> 2025-02-24       <NA>  left_only
12598       WOR     NaN        <NA> 2025-03-03       <NA>  left_only
12599       WOR     NaN        <NA> 2025-03-10       <NA>  left_only
12600       WOR     NaN        <NA> 2025-03-17       <NA>  left_only
12601       WOR     NaN        <NA> 2025-03-24       <NA>  left_only

Rows with differences:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

--- Processing WSE Weekly ---
Rows missing from new:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

Rows with differences:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

--- Processing MA- Weekly ---
Rows missing from new:

     ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
3068       MA-   Total       66566 2024-04-01       <NA>  left_only
3069       MA-   Total       53222 2024-04-08       <NA>  left_only
3070       MA-   Total       70504 2024-04-15       <NA>  left_only
3071       MA-   Total       69262 2024-04-22       <NA>  left_only
3072       MA-   Total       92958 2024-04-29       <NA>  left_only
3073       MA-   Total       72930 2024-05-06       <NA>  left_only
3074       MA-   Total       83665 2024-05-13       <NA>  left_only
3075       MA-   Total       84758 2024-05-20       <NA>  left_only
3076       MA-   Total       76328 2024-05-27       <NA>  left_only
3077       MA-   Total      187175 2024-06-03       <NA>  left_only
3078       MA-   Total      180652 2024-06-10       <NA>  left_only
3079       MA-   Total      273216 2024-06-17       <NA>  left_only
3080       MA-   Total      282322 2024-06-24       <NA>  left_only
3081       MA-   Total      348451 2024-07-01       <NA>  left_only
3082       MA-   Total      225474 2024-07-08       <NA>  left_only
3083       MA-   Total      152333 2024-07-15       <NA>  left_only
3084       MA-   Total      125535 2024-07-22       <NA>  left_only
3085       MA-   Total      150006 2024-07-29       <NA>  left_only
3086       MA-   Total      215169 2024-08-05       <NA>  left_only
3087       MA-   Total      235531 2024-08-12       <NA>  left_only
3088       MA-   Total      312654 2024-08-19       <NA>  left_only
3089       MA-   Total      322060 2024-08-26       <NA>  left_only
3090       MA-   Total      222038 2024-09-02       <NA>  left_only
3091       MA-   Total      304854 2024-09-09       <NA>  left_only
3092       MA-   Total      175660 2024-09-16       <NA>  left_only
3093       MA-   Total      140433 2024-09-23       <NA>  left_only
3094       MA-   Total       92867 2024-09-30       <NA>  left_only
3095       MA-   Total       87657 2024-10-07       <NA>  left_only
3096       MA-   Total      118730 2024-10-14       <NA>  left_only
3097       MA-   Total       98895 2024-10-21       <NA>  left_only
3098       MA-   Total      102150 2024-10-28       <NA>  left_only
3099       MA-   Total      201840 2024-11-04       <NA>  left_only
3100       MA-   Total      173838 2024-11-11       <NA>  left_only
3101       MA-   Total       90136 2024-11-18       <NA>  left_only
3102       MA-   Total       98585 2024-11-25       <NA>  left_only
3103       MA-   Total      129224 2024-12-02       <NA>  left_only
3104       MA-   Total      115904 2024-12-09       <NA>  left_only
3105       MA-   Total      132798 2024-12-16       <NA>  left_only
3106       MA-   Total      171255 2024-12-23       <NA>  left_only
3107       MA-   Total      102160 2024-12-30       <NA>  left_only
3108       MA-   Total      125138 2025-01-06       <NA>  left_only
3109       MA-   Total      101489 2025-01-13       <NA>  left_only
3110       MA-   Total       94647 2025-01-20       <NA>  left_only
3111       MA-   Total      111228 2025-01-27       <NA>  left_only
3112       MA-   Total      104668 2025-02-03       <NA>  left_only
3113       MA-   Total       69881 2025-02-10       <NA>  left_only
3114       MA-   Total       63820 2025-02-17       <NA>  left_only
3115       MA-   Total       66925 2025-02-24       <NA>  left_only
3116       MA-   Total       97235 2025-03-03       <NA>  left_only
3117       MA-   Total       98904 2025-03-10       <NA>  left_only
3118       MA-   Total       83865 2025-03-17       <NA>  left_only
3119       MA-   Total       78646 2025-03-24       <NA>  left_only

Rows with differences:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

--- Processing FOA Weekly ---
Rows missing from new:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

Rows with differences:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

--- Processing AXE Weekly ---
Rows missing from new:

      ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
12442       AXE     NaN       19566 2024-04-01       <NA>  left_only
12443       AXE     NaN       12305 2024-04-08       <NA>  left_only
12444       AXE     NaN       46857 2024-04-15       <NA>  left_only
12445       AXE     NaN       46758 2024-04-22       <NA>  left_only
12446       AXE     NaN       40455 2024-04-29       <NA>  left_only
12447       AXE     NaN       94361 2024-05-06       <NA>  left_only
12448       AXE     NaN       40575 2024-05-13       <NA>  left_only
12449       AXE     NaN       58900 2024-05-20       <NA>  left_only
12450       AXE     NaN       36068 2024-05-27       <NA>  left_only
12451       AXE     NaN       26795 2024-06-03       <NA>  left_only
12452       AXE     NaN       23017 2024-06-10       <NA>  left_only
12453       AXE     NaN       30617 2024-06-17       <NA>  left_only
12454       AXE     NaN       35930 2024-06-24       <NA>  left_only
12455       AXE     NaN       24380 2024-07-01       <NA>  left_only
12456       AXE     NaN       21261 2024-07-08       <NA>  left_only
12457       AXE     NaN      148460 2024-07-15       <NA>  left_only
12458       AXE     NaN      109363 2024-07-22       <NA>  left_only
12459       AXE     NaN       28997 2024-07-29       <NA>  left_only
12460       AXE     NaN       35569 2024-08-05       <NA>  left_only
12461       AXE     NaN       15732 2024-08-12       <NA>  left_only
12462       AXE     NaN       16129 2024-08-19       <NA>  left_only
12463       AXE     NaN       12903 2024-08-26       <NA>  left_only
12464       AXE     NaN       15878 2024-09-02       <NA>  left_only
12465       AXE     NaN        7602 2024-09-09       <NA>  left_only
12466       AXE     NaN        9459 2024-09-16       <NA>  left_only
12467       AXE     NaN        8509 2024-09-23       <NA>  left_only
12468       AXE     NaN       31572 2024-09-30       <NA>  left_only
12469       AXE     NaN       29071 2024-10-07       <NA>  left_only
12470       AXE     NaN        9094 2024-10-14       <NA>  left_only
12471       AXE     NaN       17327 2024-10-21       <NA>  left_only
12472       AXE     NaN        6667 2024-10-28       <NA>  left_only
12473       AXE     NaN       31286 2024-11-04       <NA>  left_only
12474       AXE     NaN       18419 2024-11-11       <NA>  left_only
12475       AXE     NaN       11313 2024-11-18       <NA>  left_only
12476       AXE     NaN       43553 2024-11-25       <NA>  left_only
12477       AXE     NaN        6496 2024-12-02       <NA>  left_only
12478       AXE     NaN        6347 2024-12-09       <NA>  left_only
12479       AXE     NaN        6872 2024-12-16       <NA>  left_only
12480       AXE     NaN        6824 2024-12-23       <NA>  left_only
12481       AXE     NaN        6232 2024-12-30       <NA>  left_only
12482       AXE     NaN       25320 2025-01-06       <NA>  left_only
12483       AXE     NaN       26211 2025-01-13       <NA>  left_only
12484       AXE     NaN       46637 2025-01-20       <NA>  left_only
12485       AXE     NaN       52644 2025-01-27       <NA>  left_only
12486       AXE     NaN       26201 2025-02-03       <NA>  left_only
12487       AXE     NaN       71821 2025-02-10       <NA>  left_only
12488       AXE     NaN       48441 2025-02-17       <NA>  left_only
12489       AXE     NaN       30355 2025-02-24       <NA>  left_only
12490       AXE     NaN       50526 2025-03-03       <NA>  left_only
12491       AXE     NaN      139235 2025-03-10       <NA>  left_only
12492       AXE     NaN      248064 2025-03-17       <NA>  left_only

Rows with differences:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

--- Processing AX2 Weekly ---
Rows missing from new:

      ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
12510       AX2     NaN       19566 2024-04-01       <NA>  left_only
12511       AX2     NaN       12305 2024-04-08       <NA>  left_only
12512       AX2     NaN       46857 2024-04-15       <NA>  left_only
12513       AX2     NaN       46758 2024-04-22       <NA>  left_only
12514       AX2     NaN       40455 2024-04-29       <NA>  left_only
12515       AX2     NaN       94361 2024-05-06       <NA>  left_only
12516       AX2     NaN       40575 2024-05-13       <NA>  left_only
12517       AX2     NaN       58900 2024-05-20       <NA>  left_only
12518       AX2     NaN       36068 2024-05-27       <NA>  left_only
12519       AX2     NaN       26795 2024-06-03       <NA>  left_only
12520       AX2     NaN       23017 2024-06-10       <NA>  left_only
12521       AX2     NaN       30617 2024-06-17       <NA>  left_only
12522       AX2     NaN       35930 2024-06-24       <NA>  left_only
12523       AX2     NaN       24380 2024-07-01       <NA>  left_only
12524       AX2     NaN       21261 2024-07-08       <NA>  left_only
12525       AX2     NaN      148460 2024-07-15       <NA>  left_only
12526       AX2     NaN      109363 2024-07-22       <NA>  left_only
12527       AX2     NaN       28997 2024-07-29       <NA>  left_only
12528       AX2     NaN       35569 2024-08-05       <NA>  left_only
12529       AX2     NaN       15732 2024-08-12       <NA>  left_only
12530       AX2     NaN       16129 2024-08-19       <NA>  left_only
12531       AX2     NaN       12903 2024-08-26       <NA>  left_only
12532       AX2     NaN       15878 2024-09-02       <NA>  left_only
12533       AX2     NaN        7602 2024-09-09       <NA>  left_only
12534       AX2     NaN        9459 2024-09-16       <NA>  left_only
12535       AX2     NaN        8509 2024-09-23       <NA>  left_only
12536       AX2     NaN       31572 2024-09-30       <NA>  left_only
12537       AX2     NaN       29071 2024-10-07       <NA>  left_only
12538       AX2     NaN        9094 2024-10-14       <NA>  left_only
12539       AX2     NaN       17327 2024-10-21       <NA>  left_only
12540       AX2     NaN        6667 2024-10-28       <NA>  left_only
12541       AX2     NaN       31286 2024-11-04       <NA>  left_only
12542       AX2     NaN       18419 2024-11-11       <NA>  left_only
12543       AX2     NaN       11313 2024-11-18       <NA>  left_only
12544       AX2     NaN       43553 2024-11-25       <NA>  left_only
12545       AX2     NaN        6496 2024-12-02       <NA>  left_only
12546       AX2     NaN        6347 2024-12-09       <NA>  left_only
12547       AX2     NaN        6872 2024-12-16       <NA>  left_only
12548       AX2     NaN        6824 2024-12-23       <NA>  left_only
12549       AX2     NaN        6232 2024-12-30       <NA>  left_only
12550       AX2     NaN       25320 2025-01-06       <NA>  left_only
12551       AX2     NaN       26211 2025-01-13       <NA>  left_only
12552       AX2     NaN       46637 2025-01-20       <NA>  left_only
12553       AX2     NaN       52644 2025-01-27       <NA>  left_only
12554       AX2     NaN       26201 2025-02-03       <NA>  left_only
12555       AX2     NaN       71821 2025-02-10       <NA>  left_only
12556       AX2     NaN       48441 2025-02-17       <NA>  left_only
12557       AX2     NaN       30355 2025-02-24       <NA>  left_only
12558       AX2     NaN       50526 2025-03-03       <NA>  left_only
12559       AX2     NaN      139235 2025-03-10       <NA>  left_only
12560       AX2     NaN      248064 2025-03-17       <NA>  left_only

Rows with differences:

     ServiceID PlaceID  Reach_orig        w/c  Reach_new _merge  diff
3262       AX2     EGY      429879 2024-07-29     429878   both     1
5072       AX2     IND    18110495 2024-05-20   18110494   both     1

--- Processing ANW Weekly ---
Rows missing from new:

      ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
12584       ANW     NaN       19566 2024-04-01       <NA>  left_only
12585       ANW     NaN       12305 2024-04-08       <NA>  left_only
12586       ANW     NaN       46857 2024-04-15       <NA>  left_only
12587       ANW     NaN       46758 2024-04-22       <NA>  left_only
12588       ANW     NaN       40455 2024-04-29       <NA>  left_only
12589       ANW     NaN       94361 2024-05-06       <NA>  left_only
12590       ANW     NaN       40575 2024-05-13       <NA>  left_only
12591       ANW     NaN       58900 2024-05-20       <NA>  left_only
12592       ANW     NaN       36068 2024-05-27       <NA>  left_only
12593       ANW     NaN       26795 2024-06-03       <NA>  left_only
12594       ANW     NaN       23017 2024-06-10       <NA>  left_only
12595       ANW     NaN       30617 2024-06-17       <NA>  left_only
12596       ANW     NaN       35930 2024-06-24       <NA>  left_only
12597       ANW     NaN       24380 2024-07-01       <NA>  left_only
12598       ANW     NaN       21261 2024-07-08       <NA>  left_only
12599       ANW     NaN      148460 2024-07-15       <NA>  left_only
12600       ANW     NaN      109363 2024-07-22       <NA>  left_only
12601       ANW     NaN       28997 2024-07-29       <NA>  left_only
12602       ANW     NaN       35569 2024-08-05       <NA>  left_only
12603       ANW     NaN       15732 2024-08-12       <NA>  left_only
12604       ANW     NaN       16129 2024-08-19       <NA>  left_only
12605       ANW     NaN       12903 2024-08-26       <NA>  left_only
12606       ANW     NaN       15878 2024-09-02       <NA>  left_only
12607       ANW     NaN        7602 2024-09-09       <NA>  left_only
12608       ANW     NaN        9459 2024-09-16       <NA>  left_only
12609       ANW     NaN        8509 2024-09-23       <NA>  left_only
12610       ANW     NaN       31572 2024-09-30       <NA>  left_only
12611       ANW     NaN       29071 2024-10-07       <NA>  left_only
12612       ANW     NaN        9094 2024-10-14       <NA>  left_only
12613       ANW     NaN       17327 2024-10-21       <NA>  left_only
12614       ANW     NaN        6667 2024-10-28       <NA>  left_only
12615       ANW     NaN       31286 2024-11-04       <NA>  left_only
12616       ANW     NaN       18419 2024-11-11       <NA>  left_only
12617       ANW     NaN       11313 2024-11-18       <NA>  left_only
12618       ANW     NaN       43553 2024-11-25       <NA>  left_only
12619       ANW     NaN        6496 2024-12-02       <NA>  left_only
12620       ANW     NaN        6347 2024-12-09       <NA>  left_only
12621       ANW     NaN        6872 2024-12-16       <NA>  left_only
12622       ANW     NaN        6824 2024-12-23       <NA>  left_only
12623       ANW     NaN        6232 2024-12-30       <NA>  left_only
12624       ANW     NaN       25320 2025-01-06       <NA>  left_only
12625       ANW     NaN       26211 2025-01-13       <NA>  left_only
12626       ANW     NaN       46637 2025-01-20       <NA>  left_only
12627       ANW     NaN       52644 2025-01-27       <NA>  left_only
12628       ANW     NaN       26201 2025-02-03       <NA>  left_only
12629       ANW     NaN       71821 2025-02-10       <NA>  left_only
12630       ANW     NaN       48441 2025-02-17       <NA>  left_only
12631       ANW     NaN       30355 2025-02-24       <NA>  left_only
12632       ANW     NaN       50526 2025-03-03       <NA>  left_only
12633       ANW     NaN      139235 2025-03-10       <NA>  left_only
12634       ANW     NaN      248064 2025-03-17       <NA>  left_only

Rows with differences:

      ServiceID PlaceID  Reach_orig        w/c  Reach_new _merge  diff
715         ANW     AUS      293555 2024-12-30     293554   both     1
870         ANW     BAN     1792265 2024-12-23    1792264   both     1
2045        ANW     CAN      487222 2024-07-29     487221   both     1
2072        ANW     CAN      636626 2025-02-03     636625   both     1
2073        ANW     CAN      621037 2025-02-10     621036   both     1
4306        ANW     GRE       31888 2024-07-15      31887   both     1
5102        ANW     IND    13637958 2024-11-04   13637957   both     1
5114        ANW     IND    19342822 2025-01-27   19342821   both     1
5116        ANW     IND    20236022 2025-02-10   20236021   both     1
5117        ANW     IND    15622104 2025-02-17   15622103   both     1
5118        ANW     IND    17849387 2025-02-24   17849386   both     1
5119        ANW     IND    17500248 2025-03-03   17500247   both     1
5120        ANW     IND    19390152 2025-03-10   19390151   both     1
5124        ANW     INO      796041 2024-04-08     796040   both     1
5125        ANW     INO     1128956 2024-04-15    1128955   both     1
5130        ANW     INO     1341818 2024-05-20    1341817   both     1
5153        ANW     INO      936438 2024-10-28     936437   both     1
5167        ANW     INO     1045958 2025-02-03    1045957   both     1
5168        ANW     INO     2022599 2025-02-10    2022598   both     1
5542        ANW     JAP      211874 2024-04-22     211873   both     1
5558        ANW     JAP      186740 2024-08-12     186739   both     1
5704        ANW     KAZ      130686 2024-06-03     130685   both     1
5918        ANW     KOS      738346 2024-07-15     738345   both     1
5935        ANW     KOS      438788 2024-11-11     438787   both     1
5950        ANW     KOS      934195 2025-02-24     934194   both     1
6666        ANW     MAL      203385 2024-12-02     203384   both     1
7235        ANW     MLT        3822 2024-11-11       3821   both     1
7975        ANW     NET      207090 2025-02-03     207089   both     1
8365        ANW      NZ       36110 2024-09-02      36109   both     1
8496        ANW     OST       50245 2025-03-10      50244   both     1
8515        ANW     PAK      826439 2024-07-22     826438   both     1
8840        ANW     PHI      423214 2024-04-29     423213   both     1
8896        ANW     POL       60235 2024-05-27      60234   both     1
8922        ANW     POL       62643 2024-11-25      62642   both     1
8943        ANW     POR       56613 2024-04-22      56612   both     1
9395        ANW     SAF      125341 2024-12-30     125340   both     1
10723       ANW     SWE       82037 2024-06-17      82036   both     1
11089       ANW     THA     1080815 2024-07-01    1080814   both     1
11716       ANW      UK      490839 2024-05-06     490838   both     1
11727       ANW      UK      750897 2024-07-22     750896   both     1
11751       ANW      UK      749512 2025-01-06     749511   both     1
11752       ANW      UK      719892 2025-01-13     719891   both     1
11758       ANW      UK      740897 2025-02-24     740896   both     1
11794       ANW     UKR      882684 2024-11-04     882683   both     1
11958       ANW     USA     1809085 2024-04-15    1809084   both     1
11982       ANW     USA     1451825 2024-09-30    1451824   both     1
11987       ANW     USA     2345571 2024-11-04    2345570   both     1
11995       ANW     USA     1912763 2024-12-30    1912762   both     1
12000       ANW     USA     2060301 2025-02-03    2060300   both     1
12003       ANW     USA     2058314 2025-02-24    2058313   both     1
12004       ANW     USA     1882907 2025-03-03    1882906   both     1
12251       ANW     VIE     1906002 2024-10-14    1906001   both     1

--- Processing ANY Weekly ---
Rows missing from new:

      ServiceID PlaceID  Reach_orig        w/c  Reach_new     _merge
12669       ANY     NaN       19566 2024-04-01       <NA>  left_only
12670       ANY     NaN       12305 2024-04-08       <NA>  left_only
12671       ANY     NaN       46857 2024-04-15       <NA>  left_only
12672       ANY     NaN       46758 2024-04-22       <NA>  left_only
12673       ANY     NaN       40455 2024-04-29       <NA>  left_only
12674       ANY     NaN       94361 2024-05-06       <NA>  left_only
12675       ANY     NaN       40575 2024-05-13       <NA>  left_only
12676       ANY     NaN       58900 2024-05-20       <NA>  left_only
12677       ANY     NaN       36068 2024-05-27       <NA>  left_only
12678       ANY     NaN       26795 2024-06-03       <NA>  left_only
12679       ANY     NaN       23017 2024-06-10       <NA>  left_only
12680       ANY     NaN       30617 2024-06-17       <NA>  left_only
12681       ANY     NaN       35930 2024-06-24       <NA>  left_only
12682       ANY     NaN       24380 2024-07-01       <NA>  left_only
12683       ANY     NaN       21261 2024-07-08       <NA>  left_only
12684       ANY     NaN      148460 2024-07-15       <NA>  left_only
12685       ANY     NaN      109363 2024-07-22       <NA>  left_only
12686       ANY     NaN       28997 2024-07-29       <NA>  left_only
12687       ANY     NaN       35569 2024-08-05       <NA>  left_only
12688       ANY     NaN       15732 2024-08-12       <NA>  left_only
12689       ANY     NaN       16129 2024-08-19       <NA>  left_only
12690       ANY     NaN       12903 2024-08-26       <NA>  left_only
12691       ANY     NaN       15878 2024-09-02       <NA>  left_only
12692       ANY     NaN        7602 2024-09-09       <NA>  left_only
12693       ANY     NaN        9459 2024-09-16       <NA>  left_only
12694       ANY     NaN        8509 2024-09-23       <NA>  left_only
12695       ANY     NaN       31572 2024-09-30       <NA>  left_only
12696       ANY     NaN       29071 2024-10-07       <NA>  left_only
12697       ANY     NaN        9094 2024-10-14       <NA>  left_only
12698       ANY     NaN       17327 2024-10-21       <NA>  left_only
12699       ANY     NaN        6667 2024-10-28       <NA>  left_only
12700       ANY     NaN       31286 2024-11-04       <NA>  left_only
12701       ANY     NaN       18419 2024-11-11       <NA>  left_only
12702       ANY     NaN       11313 2024-11-18       <NA>  left_only
12703       ANY     NaN       43553 2024-11-25       <NA>  left_only
12704       ANY     NaN        6496 2024-12-02       <NA>  left_only
12705       ANY     NaN        6347 2024-12-09       <NA>  left_only
12706       ANY     NaN        6872 2024-12-16       <NA>  left_only
12707       ANY     NaN        6824 2024-12-23       <NA>  left_only
12708       ANY     NaN        6232 2024-12-30       <NA>  left_only
12709       ANY     NaN       25320 2025-01-06       <NA>  left_only
12710       ANY     NaN       26211 2025-01-13       <NA>  left_only
12711       ANY     NaN       46637 2025-01-20       <NA>  left_only
12712       ANY     NaN       52644 2025-01-27       <NA>  left_only
12713       ANY     NaN       26201 2025-02-03       <NA>  left_only
12714       ANY     NaN       71821 2025-02-10       <NA>  left_only
12715       ANY     NaN       48441 2025-02-17       <NA>  left_only
12716       ANY     NaN       30355 2025-02-24       <NA>  left_only
12717       ANY     NaN       50526 2025-03-03       <NA>  left_only
12718       ANY     NaN      139235 2025-03-10       <NA>  left_only
12719       ANY     NaN      248064 2025-03-17       <NA>  left_only

Rows with differences:

      ServiceID PlaceID  Reach_orig        w/c  Reach_new _merge  diff
707         ANY     AUS      751045 2024-11-04     751044   both     1
1619        ANY     BRA     1368522 2024-05-20    1368521   both     1
2036        ANY     CAN      739510 2024-05-27     739509   both     1
2040        ANY     CAN      698034 2024-06-24     698033   both     1
2054        ANY     CAN      939441 2024-09-30     939440   both     1
3868        ANY     FIN       59331 2024-08-05      59330   both     1
4199        ANY     GER     1242763 2024-12-16    1242762   both     1
4904        ANY      HK      567607 2024-07-08     567606   both     1
5117        ANY     IND    17020550 2024-08-12   17020549   both     1
5120        ANY     IND    15618738 2024-09-02   15618737   both     1
5139        ANY     IND    19182268 2025-01-13   19182267   both     1
5143        ANY     IND    21410303 2025-02-10   21410302   both     1
5145        ANY     IND    18906088 2025-02-24   18906087   both     1
5146        ANY     IND    18589049 2025-03-03   18589048   both     1
5147        ANY     IND    20231940 2025-03-10   20231939   both     1
5148        ANY     IND    26350087 2025-03-17   26350086   both     1
5151        ANY     INO      892512 2024-04-08     892511   both     1
5154        ANY     INO     1334176 2024-04-29    1334175   both     1
5157        ANY     INO     1468737 2024-05-20    1468736   both     1
5195        ANY     INO     2089206 2025-02-10    2089205   both     1
5245        ANY     IRE      144263 2025-01-27     144262   both     1
5349        ANY     IRQ      400118 2025-01-27     400117   both     1
5405        ANY     ISR       85375 2025-02-24      85374   both     1
5459        ANY     ITA      231453 2025-03-10     231452   both     1
5570        ANY     JAP      771496 2024-04-29     771495   both     1
5758        ANY     KAZ      259720 2024-12-09     259719   both     1
5956        ANY     KOS      368352 2024-09-30     368351   both     1
5960        ANY     KOS      335634 2024-10-28     335633   both     1
5976        ANY     KOS     1114201 2025-02-17    1114200   both     1
6483        ANY     LTV       29662 2024-11-18      29661   both     1
7541        ANY     MON       10606 2025-03-24      10605   both     1
7553        ANY     MOR      474310 2024-06-17     474309   both     1
8301        ANY     NOR       82667 2024-11-04      82666   both     1
8531        ANY     PAK     1880514 2024-04-08    1880513   both     1
8875        ANY     PHI      315682 2024-05-27     315681   both     1
8901        ANY     PHI      324568 2024-11-25     324567   both     1
9396        ANY     SAF      243130 2024-06-03     243129   both     1
9900        ANY     SIN      223649 2024-12-23     223648   both     1
10849       ANY     SWI       99816 2025-03-24      99815   both     1
11117       ANY     THA     1592899 2024-05-20    1592898   both     1
11783       ANY      UK      490839 2024-05-06     490838   both     1
11794       ANY      UK      750897 2024-07-22     750896   both     1
11818       ANY      UK      749512 2025-01-06     749511   both     1
11819       ANY      UK      719892 2025-01-13     719891   both     1
11825       ANY      UK      740897 2025-02-24     740896   both     1
12027       ANY     USA     4315851 2024-04-08    4315850   both     1
12033       ANY     USA     4042032 2024-05-20    4042031   both     1
12043       ANY     USA     3609914 2024-07-29    3609913   both     1
12066       ANY     USA     4937392 2025-01-06    4937391   both     1
12067       ANY     USA     4546102 2025-01-13    4546101   both     1

--- Processing TOT Weekly ---
Rows missing from new:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

Rows with differences:

     ServiceID PlaceID  Reach_orig        w/c  Reach_new _merge     diff
5163       TOT     INO     4212752 2024-07-01     734479   both  3478273
5179       TOT     INO     3383714 2024-10-21    1240250   both  2143464
5155       TOT     INO     3424182 2024-05-06    1471208   both  1952974
5154       TOT     INO     3104940 2024-04-29    1390596   both  1714344
5178       TOT     INO     2314827 2024-10-14     775412   both  1539415
...        ...     ...         ...        ...        ...    ...      ...
7927       TOT     NEP      374314 2024-08-26     409188   both   -34874
7928       TOT     NEP      334150 2024-09-02     376447   both   -42297
5160       TOT     INO      482141 2024-06-10     577068   both   -94927
5159       TOT     INO      585143 2024-06-03     684623   both   -99480
5161       TOT     INO      542210 2024-06-17     680943   both  -138733

[1305 rows x 7 columns]

--- Processing ALL Weekly ---
Rows missing from new:

Empty DataFrame
Columns: [ServiceID, PlaceID, Reach_orig, w/c, Reach_new, _merge]
Index: []

Rows with differences:

     ServiceID PlaceID  Reach_orig        w/c  Reach_new _merge     diff
5194       ALL     INO     4740326 2024-07-01    1270869   both  3469457
5210       ALL     INO     4149460 2024-10-21    2013851   both  2135609
5186       ALL     INO     4026366 2024-05-06    2079021   both  1947345
5185       ALL     INO     3784267 2024-04-29    2075488   both  1708779
5209       ALL     INO     3383347 2024-10-14    1851764   both  1531583
...        ...     ...         ...        ...        ...    ...      ...
7960       ALL     NEP      414045 2024-08-26     448855   both   -34810
7961       ALL     NEP      398624 2024-09-02     440794   both   -42170
5191       ALL     INO     1279813 2024-06-10    1374383   both   -94570
5190       ALL     INO     2006742 2024-06-03    2105554   both   -98812
5192       ALL     INO     1099810 2024-06-17    1238178   both  -138368

[1299 rows x 7 columns]

--- Processing ENG Weekly ---
Rows missing from new:

Empty DataFrame
Columns: [w/c, ServiceID, PlaceID, Reach_orig, Reach_new, _merge]
Index: []

Rows with differences:

             w/c ServiceID PlaceID  Reach_orig  Reach_new _merge  diff
356   2024-04-08       ENG     KRG        4352       4351   both     1
1572  2024-05-13       ENG     KRG        3393       3392   both     1
4244  2024-07-29       ENG     KRG        2812       2811   both     1
8615  2024-12-02       ENG     KRG        7288       7287   both     1
9100  2024-12-16       ENG     KRG        4968       4967   both     1
9826  2025-01-06       ENG     KRG        6658       6657   both     1
10068 2025-01-13       ENG     KRG        5702       5701   both     1
12255 2025-03-17       ENG     KRG        3464       3463   both     1
12495 2025-03-24       ENG     KRG        5620       5619   both     1

--- Processing ENW Weekly ---
Rows missing from new:

Empty DataFrame
Columns: [w/c, ServiceID, PlaceID, Reach_orig, Reach_new, _merge]
Index: []

Rows with differences:

Empty DataFrame
Columns: [w/c, ServiceID, PlaceID, Reach_orig, Reach_new, _merge]
Index: []

--- Processing EN2 Weekly ---
Rows missing from new:

Empty DataFrame
Columns: [w/c, ServiceID, PlaceID, Reach_orig, Reach_new, _merge]
Index: []

Rows with differences:

Empty DataFrame
Columns: [w/c, ServiceID, PlaceID, Reach_orig, Reach_new, _merge]
Index: []