In [66]:
platformID = 'TTK'

In [67]:
from IPython.display import display

import pandas as pd

In [68]:
import sys
from pathlib import Path

try:
    # Works in Python scripts
    helper_path = Path(__file__).resolve().parent.parent / "helper"
except NameError:
    # Works in Jupyter notebooks
    helper_path = Path().resolve().parent / "helper"

sys.path.insert(0, str(helper_path))

# Now import your modules
from config_GAM2025 import gam_info
import functions

In [69]:
# Load country mapping
country_map = pd.read_excel(f"../../{gam_info['lookup_file']}", sheet_name='CountryID')[['PlaceID', 'YT-_FBE_codes']]
# Load country mapping
week_map = pd.read_excel(f"../../{gam_info['lookup_file']}", sheet_name='GAM Period')[['w/c', 'WeekNumber_finYear']]

In [70]:
# Utility functions
def load_excel(path):
    return pd.read_excel(path, engine='openpyxl')

def load_csv(path):
    return pd.read_csv(path)

def standardize_country_codes(df, column='Country Code'):
    return df.replace({column: {'WLF': 'WFI', '* Total': 'Total'}})

def run_comparison(original_df, new_df, column_mapping, key_columns, method='integer', threshold=0.0001):
    if method == 'integer':
        return compare_dataframes_integer(original_df, new_df, column_mapping, key_columns)
    elif method == 'percentage':
        return compare_dataframes_percentage(original_df, new_df, column_mapping, key_columns, threshold)
    else:
        raise ValueError("Unknown comparison method")

In [71]:
def compare_dataframes_integer(original_df, new_df, column_mapping, key_columns_new):
    """
    Compare two DataFrames and return rows that are missing or different.

    Parameters:
    - original_df: DataFrame from the original source
    - new_df: DataFrame from the new source
    - column_mapping: dict mapping original_df column names to new_df column names
    - key_columns_new: list of key columns using new_df naming

    Returns:
    - missing_from_new: rows in original_df not found in new_df
    - differing_rows: rows where key matches but mapped columns differ
    """
    for key in key_columns_new:
        # Convert both original and new key columns to string
        original_df[key] = original_df[key].astype(str).str.replace(r"\.0$", "", regex=True)
        new_df[key] = new_df[key].astype(str).str.replace(r"\.0$", "", regex=True)
    
    # Rename original_df to match new_df column names
    original_df_renamed = original_df.rename(columns=column_mapping)

    # Ensure all required columns exist
    all_columns = list(column_mapping.values())
    original_subset = original_df_renamed[all_columns].copy()
    new_subset = new_df[all_columns].copy()

        
    # Round numeric columns to nearest integer
    for col in all_columns:
        if pd.api.types.is_numeric_dtype(original_subset[col]) and pd.api.types.is_numeric_dtype(new_subset[col]):
            original_subset[col] = original_subset[col].round(0).astype('Int64')
            new_subset[col] = new_subset[col].round(0).astype('Int64')
        
    # Merge to find differences
    merged = pd.merge(
        original_subset,
        new_subset,
        on=key_columns_new,
        how='outer',
        suffixes=('_orig', '_new'),
        indicator=True
    )

    # Missing rows: present in original but not in new
    missing_from_new = merged[merged['_merge'] == 'left_only']

    # Differing rows: same keys but different values
    comparison_cols = [col for col in all_columns if col not in key_columns_new]
        
    differing_rows = merged[
        (merged['_merge'] == 'both') &
        merged[[f"{col}_orig" for col in comparison_cols]].ne(
            merged[[f"{col}_new" for col in comparison_cols]].values
        ).any(axis=1)
    ]

    return missing_from_new, differing_rows

In [72]:
def compare_dataframes_percentage(original_df, new_df, column_mapping, key_columns_new, 
                                  threshold=0.0001):
    """
    Compare two DataFrames and return rows that are missing or have percentage differences.

    Parameters:
    - original_df: DataFrame from the original source
    - new_df: DataFrame from the new source
    - column_mapping: dict mapping original_df column names to new_df column names
    - key_columns_new: list of key columns using new_df naming
    - threshold: minimum absolute difference to consider as significant

    Returns:
    - missing_from_new: rows in original_df not found in new_df
    - differing_rows: rows where key matches but mapped columns differ beyond threshold
    """

    # Rename original_df to match new_df column names
    original_df_renamed = original_df.rename(columns=column_mapping)

    # Ensure all required columns exist
    all_columns = list(column_mapping.values())
    original_subset = original_df_renamed[all_columns].copy()
    new_subset = new_df[all_columns].copy()

    # Merge to find differences
    merged = pd.merge(
        original_subset,
        new_subset,
        on=key_columns_new,
        how='outer',
        suffixes=('_orig', '_new'),
        indicator=True
    )

    # Missing rows: present in original but not in new
    missing_from_new = merged[merged['_merge'] == 'left_only']

    # Compute differences
    comparison_cols = [col for col in all_columns if col not in key_columns_new]
    for col in comparison_cols:
        #print(col)
        merged[f"{col}_diff"] = merged[f"{col}_new"] - merged[f"{col}_orig"]

    # Filter rows where any difference exceeds threshold
    diff_mask = merged['_merge'] == 'both'
    for col in comparison_cols:
        diff_mask &= merged[f"{col}_diff"].abs() > threshold

    differing_rows = merged[diff_mask]

    return missing_from_new, differing_rows

In [73]:
# Dataset configuration
datasets = [
    {
        "name": "Country",
        "original_path": "../../../../Research Projects/GAM/Digital GAM/2025/Social Media/data/TT country %.xlsx",
        "new_path": f"../data/processed/TTK/{gam_info['file_timeinfo']}_TTK_country.csv",
        "column_mapping": {
            "PlaceID (GAM Pivot)": "PlaceID",
            "Profile ID": "Channel ID",
            "% country": "percentage",
            },
        "key_columns": ["Channel ID", "PlaceID"],
        "method": "percentage",
        "threshold": 0.0001,
        "preprocess": {
            "standardize_country": True,
            "week_mapping": False
        },
        "notes": "perfect match"
    },
    {
        "name": "Unique Viewers",
        "original_path": "../data/interim/Tiktok raw data 10s test.xlsx",
        "new_path": f"../data/processed/TTK/GAM2025_TTK_views.csv",
        "column_mapping": {
            "w/c": "w/c",
            "Content ID": "content_id",
            "Tik Tok Service Code": "ServiceID",
            "Profile name": "Channel Name",
            "Final Video Views": "final_video_views"
        },
        "key_columns": ["content_id","Channel Name", "ServiceID", "w/c"],
        "method": "integer",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": False
        },
        "notes": ""
    },
    {
        "name": "Unique Viewers + FB Views to Viewer",
        "original_path": "../test/alteryx_datasets/mk_ttk_viewerFB_join.csv",
        "new_path": f"../test/alteryx_datasets/db_ttk_viewerFB_join.csv",
        "column_mapping": {
            "w/c": "w/c",
            "Tik Tok Service Code": "ServiceID",
            "Profile ID": "Channel ID",
            "Views per viewer": "Views per viewer",
            #"Final Video Views": "Final Video Views"
        },
        "key_columns": ["Channel ID", "ServiceID", "w/c"],
        "method": "percentage",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": False
        },
        "notes": "Difference because Minnie has a mismatch in her join because of GNL vs * BBC GN"
    },
    {
        "name": "Unique Viewers + Country",
        "original_path": "../test/alteryx_datasets/mk_ttk_views_country.csv",
        "new_path": f"../test/alteryx_datasets/db_ttk_views_country.csv",
        "column_mapping": {
            "w/c": "w/c",
            "Tik Tok Service Code": "ServiceID",
            "Profile ID": "Channel ID",
            "PLACEID1": "PlaceID",
            "% country": "% country",
            },
        "key_columns": ["Channel ID", "ServiceID", "PlaceID", "w/c"],
        "method": "percentage",
        "preprocess": {
            "standardize_country": True,
            "week_mapping": False
        },
        "notes": "Missing because Alteryx Workflow joins over name rather than ID"
    },
        {
        "name": "TikTok ALL Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly TikTok ALL.xlsx",
        "new_path": f"../data/singlePlatform/TTK/weekly/GAM2025_WEEKLY_TTK_ALLbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "TikTok ANW Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly TikTok ANW.xlsx",
        "new_path": f"../data/singlePlatform/TTK/weekly/GAM2025_WEEKLY_TTK_ANWbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "TikTok ANY Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly TikTok ANY.xlsx",
        "new_path": f"../data/singlePlatform/TTK/weekly/GAM2025_WEEKLY_TTK_ANYbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "TikTok AX2 Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly TikTok AX2.xlsx",
        "new_path": f"../data/singlePlatform/TTK/weekly/GAM2025_WEEKLY_TTK_AX2byCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "TikTok AXE Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly TikTok AXE.xlsx",
        "new_path": f"../data/singlePlatform/TTK/weekly/GAM2025_WEEKLY_TTK_AXEbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "TikTok EN2 Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly TikTok EN2 by country.xlsx",
        "new_path": f"../data/singlePlatform/TTK/weekly/GAM2025_WEEKLY_TTK_EN2byCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "TikTok ENG Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly TikTok ENG by country.xlsx",
        "new_path": f"../data/singlePlatform/TTK/weekly/GAM2025_WEEKLY_TTK_ENGbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "TikTok GNL Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly TikTok GNL.xlsx",
        "new_path": f"../data/singlePlatform/TTK/weekly/GAM2025_WEEKLY_TTK_GNLbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "TikTok MA- Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly TikTok MA.xlsx",
        "new_path": f"../data/singlePlatform/TTK/weekly/GAM2025_WEEKLY_TTK_MA-byCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "TikTok TOT Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly TikTok TOT.xlsx",
        "new_path": f"../data/singlePlatform/TTK/weekly/GAM2025_WEEKLY_TTK_TOTbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "TikTok WOR Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly TikTok WOR.xlsx",
        "new_path": f"../data/singlePlatform/TTK/weekly/GAM2025_WEEKLY_TTK_WORbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
    {
        "name": "TikTok WSL Platform",
        "original_path": f"../../../../Research Projects/GAM/Digital GAM/2025/Social Media/Output/Weekly/Weekly TikTok WSL.xlsx",
        "new_path": f"../data/singlePlatform/TTK/weekly/GAM2025_WEEKLY_TTK_WSLbyCountry.xlsx",
        "column_mapping": {
            'w/c': 'w/c', 
            'Country Code': 'PlaceID', 
            'Service Code': 'ServiceID', 
            'Platform': 'PlatformID',
            'Reach': 'Reach',
        },
        "key_columns": ['w/c', 'PlaceID', 'ServiceID', 'PlatformID'],
        "method": "integer",
        "preprocess": {
            "standardize_country": False,
            "week_mapping": True
        },
        "comment": """  
        
        """
    },
]

In [74]:

# Execute comparisons
for ds in datasets:
    print(f"\n--- Processing {ds['name']} ---")

    orig = load_excel(ds["original_path"]) if ds["original_path"].endswith(".xlsx") else load_csv(ds["original_path"])
    new  = load_excel(ds["new_path"]) if ds["new_path"].endswith(".xlsx") else load_csv(ds["new_path"])

    # Special preprocessing for Country Percentage dataset
    if ds["name"] == "Country Percentage":
        
        # Rename 'Country' to 'YouTube Codes' in original data and merge with mapping
        orig = orig.rename(columns={'Country': 'YouTube Codes'})
        orig = orig.merge(country_map, on='YouTube Codes', how='left').drop(columns=['YouTube Codes'])

    if "Country Code" in orig.columns:
        orig = standardize_country_codes(orig)
    if "Country Code" in new.columns:
        new = standardize_country_codes(new)

    # Rename columns according to mapping
    orig = orig.rename(columns={k: v for k, v in ds["column_mapping"].items() if k in orig.columns})
    new  = new.rename(columns={k: v for k, v in ds["column_mapping"].items() if k in new.columns})

    # Special preprocessing for Country Percentage dataset
    if ds['preprocess']['week_mapping']:
        # add w/c using Week Number
        orig = orig.merge(week_map, left_on='Week Number', right_on='WeekNumber_finYear',
                                              how='left').drop(columns=['Week Number', 'WeekNumber_finYear'])

    # Ensure 'w/c' columns are datetime in both DataFrames
    if 'w/c' in orig.columns:
        orig['w/c'] = pd.to_datetime(orig['w/c'], errors='coerce')
    if 'w/c' in new.columns:
        new['w/c'] = pd.to_datetime(new['w/c'], errors='coerce')

    missing, different = run_comparison(
        orig, new,
        ds["column_mapping"],
        ds["key_columns"],
        method=ds.get("method", "integer"),
        threshold=ds.get("threshold", 0.0001)
    )

    print("Rows missing from new:")
    display(missing)
    print("Rows with differences:")
    if 'Reach_new' in different.columns:
        if len(different) > 0:
            different['Reach_new'] = different['Reach_new'].fillna(0)
            different['diff'] = different['Reach_orig'] - different['Reach_new']
            display(different.sort_values('diff', ascending=False))
        else:
            display(different)
    else:
        display(different)

--- Processing TikTok ALL Platform ---
Rows missing from new:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge
1,2024-04-01,AGU,ALL,TTK,0,<NA>,left_only
4,2024-04-01,AND,ALL,TTK,0,<NA>,left_only
6,2024-04-01,ANT,ALL,TTK,5,<NA>,left_only
9,2024-04-01,ARU,ALL,TTK,0,<NA>,left_only
16,2024-04-01,BEN,ALL,TTK,5,<NA>,left_only
...,...,...,...,...,...,...,...
10798,2025-03-24,TON,ALL,TTK,1,<NA>,left_only
10800,2025-03-24,TUC,ALL,TTK,0,<NA>,left_only
10809,2025-03-24,USV,ALL,TTK,0,<NA>,left_only
10810,2025-03-24,UZB,ALL,TTK,15,<NA>,left_only
10811,2025-03-24,VAN,ALL,TTK,17,<NA>,left_only

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,diff
4137,2024-08-12,USA,ALL,TTK,7146509,5047358,both,2099151
8714,2025-01-13,USA,ALL,TTK,9879740,8394933,both,1484807
1849,2024-05-27,UK,ALL,TTK,1480470,37514,both,1442956
817,2024-04-22,USA,ALL,TTK,4351379,2964470,both,1386909
8088,2024-12-23,USA,ALL,TTK,10989113,9725704,both,1263409
...,...,...,...,...,...,...,...,...
10808,2025-03-24,USA,ALL,TTK,5939192,7536445,both,-1597253
9966,2025-02-24,UKR,ALL,TTK,8281797,9967416,both,-1685619
9646,2025-02-17,INO,ALL,TTK,6956667,8735579,both,-1778912
9757,2025-02-17,UKR,ALL,TTK,8542618,10410885,both,-1868267
10485,2025-03-17,INO,ALL,TTK,4892690,7485743,both,-2593053

--- Processing TikTok ANW Platform ---
Rows missing from new:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge
40,2024-04-01,GUM,ANW,TTK,0,<NA>,left_only
148,2024-04-08,GUM,ANW,TTK,0,<NA>,left_only
256,2024-04-15,GUM,ANW,TTK,0,<NA>,left_only
364,2024-04-22,GUM,ANW,TTK,1,<NA>,left_only
472,2024-04-29,GUM,ANW,TTK,0,<NA>,left_only
580,2024-05-06,GUM,ANW,TTK,0,<NA>,left_only
688,2024-05-13,GUM,ANW,TTK,1,<NA>,left_only
796,2024-05-20,GUM,ANW,TTK,0,<NA>,left_only
904,2024-05-27,GUM,ANW,TTK,0,<NA>,left_only
1012,2024-06-03,GUM,ANW,TTK,0,<NA>,left_only
1120,2024-06-10,GUM,ANW,TTK,0,<NA>,left_only
1231,2024-06-17,GUM,ANW,TTK,0,<NA>,left_only
1353,2024-06-24,GUM,ANW,TTK,0,<NA>,left_only
1472,2024-07-01,GUM,ANW,TTK,0,<NA>,left_only
1583,2024-07-08,GUM,ANW,TTK,0,<NA>,left_only
1705,2024-07-15,GUM,ANW,TTK,2,<NA>,left_only
1827,2024-07-22,GUM,ANW,TTK,0,<NA>,left_only
1949,2024-07-29,GUM,ANW,TTK,0,<NA>,left_only
2071,2024-08-05,GUM,ANW,TTK,0,<NA>,left_only
2193,2024-08-12,GUM,ANW,TTK,0,<NA>,left_only
2314,2024-08-19,GUM,ANW,TTK,0,<NA>,left_only
2436,2024-08-26,GUM,ANW,TTK,0,<NA>,left_only
2554,2024-09-02,GUM,ANW,TTK,1,<NA>,left_only
2664,2024-09-09,GUM,ANW,TTK,0,<NA>,left_only
2786,2024-09-16,GUM,ANW,TTK,1,<NA>,left_only
2908,2024-09-23,GUM,ANW,TTK,1,<NA>,left_only
3030,2024-09-30,GUM,ANW,TTK,1,<NA>,left_only
3151,2024-10-07,GUM,ANW,TTK,3,<NA>,left_only
3273,2024-10-14,GUM,ANW,TTK,1,<NA>,left_only
3395,2024-10-21,GUM,ANW,TTK,1,<NA>,left_only
3517,2024-10-28,GUM,ANW,TTK,0,<NA>,left_only
3639,2024-11-04,GUM,ANW,TTK,0,<NA>,left_only
3761,2024-11-11,GUM,ANW,TTK,1,<NA>,left_only
3883,2024-11-18,GUM,ANW,TTK,0,<NA>,left_only
4005,2024-11-25,GUM,ANW,TTK,1,<NA>,left_only
4127,2024-12-02,GUM,ANW,TTK,3,<NA>,left_only
4249,2024-12-09,GUM,ANW,TTK,3,<NA>,left_only
4371,2024-12-16,GUM,ANW,TTK,1,<NA>,left_only
4493,2024-12-23,GUM,ANW,TTK,1,<NA>,left_only
4615,2024-12-30,GUM,ANW,TTK,1,<NA>,left_only
4738,2025-01-06,GUM,ANW,TTK,3,<NA>,left_only
4861,2025-01-13,GUM,ANW,TTK,5,<NA>,left_only
4984,2025-01-20,GUM,ANW,TTK,5,<NA>,left_only
5107,2025-01-27,GUM,ANW,TTK,1,<NA>,left_only
5230,2025-02-03,GUM,ANW,TTK,3,<NA>,left_only
5353,2025-02-10,GUM,ANW,TTK,2,<NA>,left_only
5476,2025-02-17,GUM,ANW,TTK,2,<NA>,left_only
5599,2025-02-24,GUM,ANW,TTK,5,<NA>,left_only
5723,2025-03-03,GUM,ANW,TTK,2,<NA>,left_only
5849,2025-03-10,GUM,ANW,TTK,0,<NA>,left_only
5975,2025-03-17,GUM,ANW,TTK,1,<NA>,left_only
6101,2025-03-24,GUM,ANW,TTK,1,<NA>,left_only

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,diff
4254,2024-12-09,INO,ANW,TTK,527452,436922,both,90530
1911,2024-07-29,AZE,ANW,TTK,215661,152194,both,63467
1588,2024-07-08,INO,ANW,TTK,68897,6858,both,62039
4287,2024-12-09,PAK,ANW,TTK,1383283,1335448,both,47835
3888,2024-11-18,INO,ANW,TTK,216218,173623,both,42595
...,...,...,...,...,...,...,...,...
6106,2025-03-24,INO,ANW,TTK,2349101,3776401,both,-1427300
5670,2025-02-24,UKR,ANW,TTK,8246678,9930084,both,-1683406
5481,2025-02-17,INO,ANW,TTK,6841838,8589998,both,-1748160
5547,2025-02-17,UKR,ANW,TTK,8522019,10390450,both,-1868431
5980,2025-03-17,INO,ANW,TTK,4814320,7349581,both,-2535261

--- Processing TikTok ANY Platform ---
Rows missing from new:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge
80,2024-04-01,GUM,ANY,TTK,0,<NA>,left_only
307,2024-04-08,GUM,ANY,TTK,0,<NA>,left_only
534,2024-04-15,GUM,ANY,TTK,0,<NA>,left_only
761,2024-04-22,GUM,ANY,TTK,1,<NA>,left_only
988,2024-04-29,GUM,ANY,TTK,0,<NA>,left_only
1215,2024-05-06,GUM,ANY,TTK,0,<NA>,left_only
1442,2024-05-13,GUM,ANY,TTK,1,<NA>,left_only
1669,2024-05-20,GUM,ANY,TTK,0,<NA>,left_only
1896,2024-05-27,GUM,ANY,TTK,0,<NA>,left_only
2123,2024-06-03,GUM,ANY,TTK,0,<NA>,left_only
2350,2024-06-10,GUM,ANY,TTK,0,<NA>,left_only
2580,2024-06-17,GUM,ANY,TTK,0,<NA>,left_only
2821,2024-06-24,GUM,ANY,TTK,0,<NA>,left_only
3059,2024-07-01,GUM,ANY,TTK,0,<NA>,left_only
3289,2024-07-08,GUM,ANY,TTK,0,<NA>,left_only
3530,2024-07-15,GUM,ANY,TTK,2,<NA>,left_only
3771,2024-07-22,GUM,ANY,TTK,0,<NA>,left_only
4012,2024-07-29,GUM,ANY,TTK,0,<NA>,left_only
4253,2024-08-05,GUM,ANY,TTK,0,<NA>,left_only
4494,2024-08-12,GUM,ANY,TTK,0,<NA>,left_only
4734,2024-08-19,GUM,ANY,TTK,0,<NA>,left_only
4975,2024-08-26,GUM,ANY,TTK,0,<NA>,left_only
5212,2024-09-02,GUM,ANY,TTK,1,<NA>,left_only
5441,2024-09-09,GUM,ANY,TTK,0,<NA>,left_only
5682,2024-09-16,GUM,ANY,TTK,1,<NA>,left_only
5923,2024-09-23,GUM,ANY,TTK,1,<NA>,left_only
6164,2024-09-30,GUM,ANY,TTK,1,<NA>,left_only
6404,2024-10-07,GUM,ANY,TTK,3,<NA>,left_only
6645,2024-10-14,GUM,ANY,TTK,1,<NA>,left_only
6886,2024-10-21,GUM,ANY,TTK,1,<NA>,left_only
7127,2024-10-28,GUM,ANY,TTK,0,<NA>,left_only
7368,2024-11-04,GUM,ANY,TTK,0,<NA>,left_only
7609,2024-11-11,GUM,ANY,TTK,1,<NA>,left_only
7850,2024-11-18,GUM,ANY,TTK,0,<NA>,left_only
8091,2024-11-25,GUM,ANY,TTK,1,<NA>,left_only
8332,2024-12-02,GUM,ANY,TTK,3,<NA>,left_only
8573,2024-12-09,GUM,ANY,TTK,3,<NA>,left_only
8814,2024-12-16,GUM,ANY,TTK,1,<NA>,left_only
9055,2024-12-23,GUM,ANY,TTK,1,<NA>,left_only
9296,2024-12-30,GUM,ANY,TTK,1,<NA>,left_only
9538,2025-01-06,GUM,ANY,TTK,3,<NA>,left_only
9780,2025-01-13,GUM,ANY,TTK,5,<NA>,left_only
10022,2025-01-20,GUM,ANY,TTK,5,<NA>,left_only
10264,2025-01-27,GUM,ANY,TTK,1,<NA>,left_only
10506,2025-02-03,GUM,ANY,TTK,3,<NA>,left_only
10748,2025-02-10,GUM,ANY,TTK,2,<NA>,left_only
10990,2025-02-17,GUM,ANY,TTK,2,<NA>,left_only
11232,2025-02-24,GUM,ANY,TTK,5,<NA>,left_only
11475,2025-03-03,GUM,ANY,TTK,2,<NA>,left_only
11720,2025-03-10,GUM,ANY,TTK,0,<NA>,left_only
11965,2025-03-17,GUM,ANY,TTK,1,<NA>,left_only
12210,2025-03-24,GUM,ANY,TTK,1,<NA>,left_only

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,diff
7756,2024-11-11,USA,ANY,TTK,17815898,327630,both,17488268
6551,2024-10-07,USA,ANY,TTK,13768165,242117,both,13526048
10169,2025-01-20,USA,ANY,TTK,14327081,811963,both,13515118
10653,2025-02-03,USA,ANY,TTK,12532984,700066,both,11832918
9685,2025-01-06,USA,ANY,TTK,12170508,1695471,both,10475037
...,...,...,...,...,...,...,...,...
12219,2025-03-24,INO,ANY,TTK,2457960,3776401,both,-1318441
11375,2025-02-24,UKR,ANY,TTK,8278844,9930084,both,-1651240
10999,2025-02-17,INO,ANY,TTK,6930426,8589998,both,-1659572
11133,2025-02-17,UKR,ANY,TTK,8539725,10390450,both,-1850725
11974,2025-03-17,INO,ANY,TTK,4882756,7349581,both,-2466825

--- Processing TikTok AX2 Platform ---
Rows missing from new:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge
40,2024-04-01,GUM,AX2,TTK,0,<NA>,left_only
148,2024-04-08,GUM,AX2,TTK,0,<NA>,left_only
256,2024-04-15,GUM,AX2,TTK,0,<NA>,left_only
364,2024-04-22,GUM,AX2,TTK,1,<NA>,left_only
472,2024-04-29,GUM,AX2,TTK,0,<NA>,left_only
580,2024-05-06,GUM,AX2,TTK,0,<NA>,left_only
688,2024-05-13,GUM,AX2,TTK,1,<NA>,left_only
796,2024-05-20,GUM,AX2,TTK,0,<NA>,left_only
904,2024-05-27,GUM,AX2,TTK,0,<NA>,left_only
1012,2024-06-03,GUM,AX2,TTK,0,<NA>,left_only
1120,2024-06-10,GUM,AX2,TTK,0,<NA>,left_only
1231,2024-06-17,GUM,AX2,TTK,0,<NA>,left_only
1353,2024-06-24,GUM,AX2,TTK,0,<NA>,left_only
1472,2024-07-01,GUM,AX2,TTK,0,<NA>,left_only
1583,2024-07-08,GUM,AX2,TTK,0,<NA>,left_only
1705,2024-07-15,GUM,AX2,TTK,2,<NA>,left_only
1827,2024-07-22,GUM,AX2,TTK,0,<NA>,left_only
1949,2024-07-29,GUM,AX2,TTK,0,<NA>,left_only
2071,2024-08-05,GUM,AX2,TTK,0,<NA>,left_only
2193,2024-08-12,GUM,AX2,TTK,0,<NA>,left_only
2314,2024-08-19,GUM,AX2,TTK,0,<NA>,left_only
2436,2024-08-26,GUM,AX2,TTK,0,<NA>,left_only
2554,2024-09-02,GUM,AX2,TTK,1,<NA>,left_only
2664,2024-09-09,GUM,AX2,TTK,0,<NA>,left_only
2786,2024-09-16,GUM,AX2,TTK,1,<NA>,left_only
2908,2024-09-23,GUM,AX2,TTK,1,<NA>,left_only
3030,2024-09-30,GUM,AX2,TTK,1,<NA>,left_only
3151,2024-10-07,GUM,AX2,TTK,3,<NA>,left_only
3273,2024-10-14,GUM,AX2,TTK,1,<NA>,left_only
3395,2024-10-21,GUM,AX2,TTK,1,<NA>,left_only
3517,2024-10-28,GUM,AX2,TTK,0,<NA>,left_only
3639,2024-11-04,GUM,AX2,TTK,0,<NA>,left_only
3761,2024-11-11,GUM,AX2,TTK,1,<NA>,left_only
3883,2024-11-18,GUM,AX2,TTK,0,<NA>,left_only
4005,2024-11-25,GUM,AX2,TTK,1,<NA>,left_only
4127,2024-12-02,GUM,AX2,TTK,3,<NA>,left_only
4249,2024-12-09,GUM,AX2,TTK,3,<NA>,left_only
4371,2024-12-16,GUM,AX2,TTK,1,<NA>,left_only
4493,2024-12-23,GUM,AX2,TTK,1,<NA>,left_only
4615,2024-12-30,GUM,AX2,TTK,1,<NA>,left_only
4738,2025-01-06,GUM,AX2,TTK,3,<NA>,left_only
4861,2025-01-13,GUM,AX2,TTK,5,<NA>,left_only
4984,2025-01-20,GUM,AX2,TTK,5,<NA>,left_only
5107,2025-01-27,GUM,AX2,TTK,1,<NA>,left_only
5230,2025-02-03,GUM,AX2,TTK,3,<NA>,left_only
5353,2025-02-10,GUM,AX2,TTK,2,<NA>,left_only
5476,2025-02-17,GUM,AX2,TTK,2,<NA>,left_only
5599,2025-02-24,GUM,AX2,TTK,5,<NA>,left_only
5723,2025-03-03,GUM,AX2,TTK,2,<NA>,left_only
5849,2025-03-10,GUM,AX2,TTK,0,<NA>,left_only
5975,2025-03-17,GUM,AX2,TTK,1,<NA>,left_only
6101,2025-03-24,GUM,AX2,TTK,1,<NA>,left_only

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,diff
4254,2024-12-09,INO,AX2,TTK,527452,436922,both,90530
1911,2024-07-29,AZE,AX2,TTK,215661,152194,both,63467
1588,2024-07-08,INO,AX2,TTK,68897,6858,both,62039
4287,2024-12-09,PAK,AX2,TTK,1383283,1335448,both,47835
3888,2024-11-18,INO,AX2,TTK,216218,173623,both,42595
...,...,...,...,...,...,...,...,...
6106,2025-03-24,INO,AX2,TTK,2349101,3776401,both,-1427300
5670,2025-02-24,UKR,AX2,TTK,8246678,9930084,both,-1683406
5481,2025-02-17,INO,AX2,TTK,6841838,8589998,both,-1748160
5547,2025-02-17,UKR,AX2,TTK,8522019,10390450,both,-1868431
5980,2025-03-17,INO,AX2,TTK,4814320,7349581,both,-2535261

--- Processing TikTok AXE Platform ---
Rows missing from new:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge
40,2024-04-01,GUM,AXE,TTK,0,<NA>,left_only
148,2024-04-08,GUM,AXE,TTK,0,<NA>,left_only
256,2024-04-15,GUM,AXE,TTK,0,<NA>,left_only
364,2024-04-22,GUM,AXE,TTK,1,<NA>,left_only
472,2024-04-29,GUM,AXE,TTK,0,<NA>,left_only
580,2024-05-06,GUM,AXE,TTK,0,<NA>,left_only
688,2024-05-13,GUM,AXE,TTK,1,<NA>,left_only
796,2024-05-20,GUM,AXE,TTK,0,<NA>,left_only
904,2024-05-27,GUM,AXE,TTK,0,<NA>,left_only
1012,2024-06-03,GUM,AXE,TTK,0,<NA>,left_only
1120,2024-06-10,GUM,AXE,TTK,0,<NA>,left_only
1231,2024-06-17,GUM,AXE,TTK,0,<NA>,left_only
1353,2024-06-24,GUM,AXE,TTK,0,<NA>,left_only
1472,2024-07-01,GUM,AXE,TTK,0,<NA>,left_only
1583,2024-07-08,GUM,AXE,TTK,0,<NA>,left_only
1705,2024-07-15,GUM,AXE,TTK,2,<NA>,left_only
1827,2024-07-22,GUM,AXE,TTK,0,<NA>,left_only
1949,2024-07-29,GUM,AXE,TTK,0,<NA>,left_only
2071,2024-08-05,GUM,AXE,TTK,0,<NA>,left_only
2193,2024-08-12,GUM,AXE,TTK,0,<NA>,left_only
2314,2024-08-19,GUM,AXE,TTK,0,<NA>,left_only
2436,2024-08-26,GUM,AXE,TTK,0,<NA>,left_only
2554,2024-09-02,GUM,AXE,TTK,1,<NA>,left_only
2664,2024-09-09,GUM,AXE,TTK,0,<NA>,left_only
2786,2024-09-16,GUM,AXE,TTK,1,<NA>,left_only
2908,2024-09-23,GUM,AXE,TTK,1,<NA>,left_only
3030,2024-09-30,GUM,AXE,TTK,1,<NA>,left_only
3151,2024-10-07,GUM,AXE,TTK,3,<NA>,left_only
3273,2024-10-14,GUM,AXE,TTK,1,<NA>,left_only
3395,2024-10-21,GUM,AXE,TTK,1,<NA>,left_only
3517,2024-10-28,GUM,AXE,TTK,0,<NA>,left_only
3639,2024-11-04,GUM,AXE,TTK,0,<NA>,left_only
3761,2024-11-11,GUM,AXE,TTK,1,<NA>,left_only
3883,2024-11-18,GUM,AXE,TTK,0,<NA>,left_only
4005,2024-11-25,GUM,AXE,TTK,1,<NA>,left_only
4127,2024-12-02,GUM,AXE,TTK,3,<NA>,left_only
4249,2024-12-09,GUM,AXE,TTK,3,<NA>,left_only
4371,2024-12-16,GUM,AXE,TTK,1,<NA>,left_only
4493,2024-12-23,GUM,AXE,TTK,1,<NA>,left_only
4615,2024-12-30,GUM,AXE,TTK,1,<NA>,left_only
4738,2025-01-06,GUM,AXE,TTK,3,<NA>,left_only
4861,2025-01-13,GUM,AXE,TTK,5,<NA>,left_only
4984,2025-01-20,GUM,AXE,TTK,5,<NA>,left_only
5107,2025-01-27,GUM,AXE,TTK,1,<NA>,left_only
5230,2025-02-03,GUM,AXE,TTK,3,<NA>,left_only
5353,2025-02-10,GUM,AXE,TTK,2,<NA>,left_only
5476,2025-02-17,GUM,AXE,TTK,2,<NA>,left_only
5599,2025-02-24,GUM,AXE,TTK,5,<NA>,left_only
5723,2025-03-03,GUM,AXE,TTK,2,<NA>,left_only
5849,2025-03-10,GUM,AXE,TTK,0,<NA>,left_only
5975,2025-03-17,GUM,AXE,TTK,1,<NA>,left_only
6101,2025-03-24,GUM,AXE,TTK,1,<NA>,left_only

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,diff
4254,2024-12-09,INO,AXE,TTK,527452,436922,both,90530
1911,2024-07-29,AZE,AXE,TTK,215661,152194,both,63467
1588,2024-07-08,INO,AXE,TTK,68897,6858,both,62039
4287,2024-12-09,PAK,AXE,TTK,1383283,1335448,both,47835
3888,2024-11-18,INO,AXE,TTK,216218,173623,both,42595
...,...,...,...,...,...,...,...,...
6106,2025-03-24,INO,AXE,TTK,2349101,3776401,both,-1427300
5670,2025-02-24,UKR,AXE,TTK,8246678,9930084,both,-1683406
5481,2025-02-17,INO,AXE,TTK,6841838,8589998,both,-1748160
5547,2025-02-17,UKR,AXE,TTK,8522019,10390450,both,-1868431
5980,2025-03-17,INO,AXE,TTK,4814320,7349581,both,-2535261

--- Processing TikTok EN2 Platform ---
Rows missing from new:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge
1,2024-04-01,AGU,EN2,TTK,0,<NA>,left_only
4,2024-04-01,AND,EN2,TTK,0,<NA>,left_only
5,2024-04-01,ANG,EN2,TTK,35,<NA>,left_only
6,2024-04-01,ANT,EN2,TTK,5,<NA>,left_only
8,2024-04-01,ARM,EN2,TTK,79,<NA>,left_only
...,...,...,...,...,...,...,...
10703,2025-03-24,UZB,EN2,TTK,15,<NA>,left_only
10704,2025-03-24,VAN,EN2,TTK,17,<NA>,left_only
10705,2025-03-24,VEN,EN2,TTK,31,<NA>,left_only
10707,2025-03-24,WBG,EN2,TTK,0,<NA>,left_only
10708,2025-03-24,YEM,EN2,TTK,5,<NA>,left_only

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,diff
4109,2024-08-12,USA,EN2,TTK,6714764,4786104,both,1928660
8641,2025-01-13,USA,EN2,TTK,9322158,7702285,both,1619873
8023,2024-12-23,USA,EN2,TTK,9793957,8499996,both,1293961
813,2024-04-22,USA,EN2,TTK,4138904,2869556,both,1269348
7405,2024-12-02,USA,EN2,TTK,8375736,7350027,both,1025709
...,...,...,...,...,...,...,...,...
8676,2025-01-20,BOT,EN2,TTK,9340,369707,both,-360367
5586,2024-10-07,BOT,EN2,TTK,9262,371235,both,-361973
10495,2025-03-17,USA,EN2,TTK,3596490,4046840,both,-450350
6616,2024-11-11,BOT,EN2,TTK,11901,479572,both,-467671
10701,2025-03-24,USA,EN2,TTK,5489748,6797591,both,-1307843

--- Processing TikTok ENG Platform ---
Rows missing from new:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge
40,2024-04-01,GUA,ENG,TTK,146,<NA>,left_only
160,2024-04-08,GUA,ENG,TTK,429,<NA>,left_only
280,2024-04-15,GUA,ENG,TTK,375,<NA>,left_only
400,2024-04-22,GUA,ENG,TTK,632,<NA>,left_only
520,2024-04-29,GUA,ENG,TTK,380,<NA>,left_only
640,2024-05-06,GUA,ENG,TTK,393,<NA>,left_only
760,2024-05-13,GUA,ENG,TTK,358,<NA>,left_only
880,2024-05-20,GUA,ENG,TTK,438,<NA>,left_only
1000,2024-05-27,GUA,ENG,TTK,316,<NA>,left_only
1120,2024-06-03,GUA,ENG,TTK,346,<NA>,left_only
1240,2024-06-10,GUA,ENG,TTK,266,<NA>,left_only
1360,2024-06-17,GUA,ENG,TTK,211,<NA>,left_only
1480,2024-06-24,GUA,ENG,TTK,438,<NA>,left_only
1600,2024-07-01,GUA,ENG,TTK,1136,<NA>,left_only
1720,2024-07-08,GUA,ENG,TTK,662,<NA>,left_only
1840,2024-07-15,GUA,ENG,TTK,979,<NA>,left_only
1960,2024-07-22,GUA,ENG,TTK,509,<NA>,left_only
2080,2024-07-29,GUA,ENG,TTK,449,<NA>,left_only
2200,2024-08-05,GUA,ENG,TTK,579,<NA>,left_only
2320,2024-08-12,GUA,ENG,TTK,1030,<NA>,left_only
2440,2024-08-19,GUA,ENG,TTK,848,<NA>,left_only
2560,2024-08-26,GUA,ENG,TTK,364,<NA>,left_only
2680,2024-09-02,GUA,ENG,TTK,459,<NA>,left_only
2800,2024-09-09,GUA,ENG,TTK,590,<NA>,left_only
2920,2024-09-16,GUA,ENG,TTK,420,<NA>,left_only
3040,2024-09-23,GUA,ENG,TTK,448,<NA>,left_only
3160,2024-09-30,GUA,ENG,TTK,1016,<NA>,left_only
3280,2024-10-07,GUA,ENG,TTK,2971,<NA>,left_only
3400,2024-10-14,GUA,ENG,TTK,1434,<NA>,left_only
3520,2024-10-21,GUA,ENG,TTK,1545,<NA>,left_only
3640,2024-10-28,GUA,ENG,TTK,1220,<NA>,left_only
3760,2024-11-04,GUA,ENG,TTK,1540,<NA>,left_only
3880,2024-11-11,GUA,ENG,TTK,3842,<NA>,left_only
4000,2024-11-18,GUA,ENG,TTK,1727,<NA>,left_only
4120,2024-11-25,GUA,ENG,TTK,1946,<NA>,left_only
4240,2024-12-02,GUA,ENG,TTK,1631,<NA>,left_only
4360,2024-12-09,GUA,ENG,TTK,1578,<NA>,left_only
4480,2024-12-16,GUA,ENG,TTK,2034,<NA>,left_only
4600,2024-12-23,GUA,ENG,TTK,1887,<NA>,left_only
4720,2024-12-30,GUA,ENG,TTK,1128,<NA>,left_only
4840,2025-01-06,GUA,ENG,TTK,2398,<NA>,left_only
4960,2025-01-13,GUA,ENG,TTK,1925,<NA>,left_only
5080,2025-01-20,GUA,ENG,TTK,3011,<NA>,left_only
5200,2025-01-27,GUA,ENG,TTK,1244,<NA>,left_only
5320,2025-02-03,GUA,ENG,TTK,2633,<NA>,left_only
5440,2025-02-10,GUA,ENG,TTK,2183,<NA>,left_only
5560,2025-02-17,GUA,ENG,TTK,939,<NA>,left_only
5680,2025-02-24,GUA,ENG,TTK,1706,<NA>,left_only
5800,2025-03-03,GUA,ENG,TTK,1250,<NA>,left_only
5920,2025-03-10,GUA,ENG,TTK,1094,<NA>,left_only
6040,2025-03-17,GUA,ENG,TTK,725,<NA>,left_only
6160,2025-03-24,GUA,ENG,TTK,1154,<NA>,left_only

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,diff
5035,2025-01-13,USA,ENG,TTK,8785698,7702285,both,1083413
5155,2025-01-20,USA,ENG,TTK,13739594,13446523,both,293071
4075,2024-11-18,USA,ENG,TTK,7879280,7716009,both,163271
5275,2025-01-27,USA,ENG,TTK,5676943,5519231,both,157712
5395,2025-02-03,USA,ENG,TTK,12016069,11860440,both,155629
...,...,...,...,...,...,...,...,...
3254,2024-10-07,BOT,ENG,TTK,9141,371235,both,-362094
5875,2025-03-03,USA,ENG,TTK,5702187,6141212,both,-439025
3854,2024-11-11,BOT,ENG,TTK,11822,479572,both,-467750
6115,2025-03-17,USA,ENG,TTK,3310273,4046840,both,-736567
6235,2025-03-24,USA,ENG,TTK,5265571,6797591,both,-1532020

--- Processing TikTok GNL Platform ---
Rows missing from new:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge
40,2024-04-01,GUA,GNL,TTK,146,<NA>,left_only
160,2024-04-08,GUA,GNL,TTK,429,<NA>,left_only
280,2024-04-15,GUA,GNL,TTK,375,<NA>,left_only
400,2024-04-22,GUA,GNL,TTK,632,<NA>,left_only
520,2024-04-29,GUA,GNL,TTK,380,<NA>,left_only
640,2024-05-06,GUA,GNL,TTK,393,<NA>,left_only
760,2024-05-13,GUA,GNL,TTK,358,<NA>,left_only
880,2024-05-20,GUA,GNL,TTK,438,<NA>,left_only
1000,2024-05-27,GUA,GNL,TTK,316,<NA>,left_only
1120,2024-06-03,GUA,GNL,TTK,346,<NA>,left_only
1240,2024-06-10,GUA,GNL,TTK,266,<NA>,left_only
1360,2024-06-17,GUA,GNL,TTK,211,<NA>,left_only
1480,2024-06-24,GUA,GNL,TTK,438,<NA>,left_only
1600,2024-07-01,GUA,GNL,TTK,1136,<NA>,left_only
1720,2024-07-08,GUA,GNL,TTK,662,<NA>,left_only
1840,2024-07-15,GUA,GNL,TTK,979,<NA>,left_only
1960,2024-07-22,GUA,GNL,TTK,509,<NA>,left_only
2080,2024-07-29,GUA,GNL,TTK,449,<NA>,left_only
2200,2024-08-05,GUA,GNL,TTK,579,<NA>,left_only
2320,2024-08-12,GUA,GNL,TTK,1030,<NA>,left_only
2440,2024-08-19,GUA,GNL,TTK,848,<NA>,left_only
2560,2024-08-26,GUA,GNL,TTK,364,<NA>,left_only
2680,2024-09-02,GUA,GNL,TTK,459,<NA>,left_only
2800,2024-09-09,GUA,GNL,TTK,590,<NA>,left_only
2920,2024-09-16,GUA,GNL,TTK,420,<NA>,left_only
3040,2024-09-23,GUA,GNL,TTK,448,<NA>,left_only
3160,2024-09-30,GUA,GNL,TTK,1016,<NA>,left_only
3280,2024-10-07,GUA,GNL,TTK,2971,<NA>,left_only
3400,2024-10-14,GUA,GNL,TTK,1434,<NA>,left_only
3520,2024-10-21,GUA,GNL,TTK,1545,<NA>,left_only
3640,2024-10-28,GUA,GNL,TTK,1220,<NA>,left_only
3760,2024-11-04,GUA,GNL,TTK,1540,<NA>,left_only
3880,2024-11-11,GUA,GNL,TTK,3842,<NA>,left_only
4000,2024-11-18,GUA,GNL,TTK,1727,<NA>,left_only
4120,2024-11-25,GUA,GNL,TTK,1946,<NA>,left_only
4240,2024-12-02,GUA,GNL,TTK,1631,<NA>,left_only
4360,2024-12-09,GUA,GNL,TTK,1578,<NA>,left_only
4480,2024-12-16,GUA,GNL,TTK,2034,<NA>,left_only
4600,2024-12-23,GUA,GNL,TTK,1887,<NA>,left_only
4720,2024-12-30,GUA,GNL,TTK,1128,<NA>,left_only
4840,2025-01-06,GUA,GNL,TTK,2398,<NA>,left_only
4960,2025-01-13,GUA,GNL,TTK,1925,<NA>,left_only
5080,2025-01-20,GUA,GNL,TTK,3011,<NA>,left_only
5200,2025-01-27,GUA,GNL,TTK,1244,<NA>,left_only
5320,2025-02-03,GUA,GNL,TTK,2633,<NA>,left_only
5440,2025-02-10,GUA,GNL,TTK,2183,<NA>,left_only
5560,2025-02-17,GUA,GNL,TTK,939,<NA>,left_only
5680,2025-02-24,GUA,GNL,TTK,1706,<NA>,left_only
5800,2025-03-03,GUA,GNL,TTK,1250,<NA>,left_only
5920,2025-03-10,GUA,GNL,TTK,1094,<NA>,left_only
6040,2025-03-17,GUA,GNL,TTK,725,<NA>,left_only
6160,2025-03-24,GUA,GNL,TTK,1154,<NA>,left_only

Rows with differences:

,w/c,PlaceID,ServiceID,PlatformID,Reach_orig,Reach_new,_merge,diff
5035,2025-01-13,USA,GNL,TTK,8785698,7702285,both,1083413
5155,2025-01-20,USA,GNL,TTK,13739594,13446523,both,293071
4075,2024-11-18,USA,GNL,TTK,7879280,7716009,both,163271
5275,2025-01-27,USA,GNL,TTK,5676943,5519231,both,157712
5395,2025-02-03,USA,GNL,TTK,12016069,11860440,both,155629
...,...,...,...,...,...,...,...,...
3254,2024-10-07,BOT,GNL,TTK,9141,371235,both,-362094
5875,2025-03-03,USA,GNL,TTK,5702187,6141212,both,-439025
3854,2024-11-11,BOT,GNL,TTK,11822,479572,both,-467750
6115,2025-03-17,USA,GNL,TTK,3310273,4046840,both,-736567
6235,2025-03-24,USA,GNL,TTK,5265571,6797591,both,-1532020

--- Processing TikTok MA- Platform ---

FileNotFoundError: [Errno 2] No such file or directory: '../data/singlePlatform/TTK/weekly/GAM2025_WEEKLY_TTK_MAbyCountry.xlsx'